In [ ]:
!pip install -q FlagEmbedding

  Preparing metadata (setup.py) ... done
  Preparing metadata (setup.py) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 247.7/247.7 kB 11.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 866.1/866.1 kB 38.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 149.7/149.7 kB 13.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.6/45.6 kB 4.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.2/5.2 MB 92.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.4/1.4 MB 73.8 MB/s eta 0:00:00
  Building wheel for warc3-wet-clueweb09 (setup.py) ... done
  Building wheel for cbor (setup.py) ... done

In [ ]:
import os
import numpy as np
import pandas as pd
from sklearn.cluster import AgglomerativeClustering
from tqdm.notebook import tqdm
from FlagEmbedding import BGEM3FlagModel

In [ ]:
model = BGEM3FlagModel('BAAI/bge-m3',
                       use_fp16=False,
                       devices="cuda")

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:93: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

config.json:   0%|          | 0.00/687 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/444 [00:00<?, ?B/s]

sentencepiece.bpe.model:   0%|          | 0.00/5.07M [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

tokenizer.json:   0%|          | 0.00/17.1M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/964 [00:00<?, ?B/s]

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 30 files:   0%|          | 0/30 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/391 [00:00<?, ?it/s]

In [ ]:
def cluster(method, eng_path):
    method_path = os.path.join(eng_path, method)
    if method != "greedy":
        data1 = pd.read_csv(os.path.join(method_path, f"english-corpus1.tsv.gz"), sep="\t", compression="gzip")
        data2 = pd.read_csv(os.path.join(method_path, f"english-corpus2.tsv.gz"), sep="\t", compression="gzip")
    else:
        data1 = pd.read_csv(os.path.join(method_path, f"english-corpus1.tsv.gz"), sep="\t", compression="gzip", header=None, names=('0', '1', '2'))
        data2 = pd.read_csv(os.path.join(method_path, f"english-corpus2.tsv.gz"), sep="\t", compression="gzip", header=None, names=('0', '1', '2'))
    print(data1.head())
    data1["corpus"] = [1 for _ in range(data1.shape[0])]

    data2["corpus"] = [2 for _ in range(data2.shape[0])]
    data = pd.concat((data1, data2))
    to_concat = pd.DataFrame()
    for target, target_df in tqdm(data.groupby("0")):
        definitions = target_df["2"].unique()

        if len(definitions) > 1:
            # print(len(definitions))
            clustering = AgglomerativeClustering(
                n_clusters=None, metric="cosine", linkage="complete", distance_threshold=0.2, compute_full_tree=True,
            )
            embeddings = model.encode(definitions.tolist(),
                                    max_length=2048, # If you don't need such a long length, you can set a smaller value to speed up the encoding process.
                                    )['dense_vecs']
            labels = clustering.fit_predict(embeddings)
            labels_def = []
            for label in np.unique(labels):
                idx = np.where(labels == label)[0]
                first_definition = Counter(definitions[idx]).most_common()[0][0]
                labels_def.append(first_definition)
            # print(labels_def)

            labels_list = []
            for i, row in target_df.iterrows():
                idx = np.where(definitions == row["2"])
                label = labels[idx].tolist()[0]
                labels_list.append(labels_def[label])
            target_df["labels"] = labels_list
        else:
            target_df["labels"] = target_df["2"]

        to_concat = pd.concat([to_concat, target_df])
    assert len(to_concat) == len(data)
    to_concat = to_concat.reset_index(drop=True)
    print(len(to_concat["2"].unique()))
    print(len(to_concat["labels"].unique()))
    data1 = to_concat[to_concat["corpus"]==1]
    data2 = to_concat[to_concat["corpus"]==2]
    return data1, data2

In [ ]:
eng_path = "drive/MyDrive/generated_definitions/english"

In [ ]:
dpo1, dpo2 = cluster("dpo", eng_path)

  0%|          | 0/37 [00:00<?, ?it/s]

pre tokenize: 100%|██████████| 2/2 [00:00<00:00, 38.25it/s]


Inference Embeddings:   0%|          | 0/2 [00:00<?, ?it/s]

Inference Embeddings:  50%|█████     | 1/2 [00:02<00:02,  2.33s/it]

Inference Embeddings: 100%|██████████| 2/2 [00:03<00:00,  1.54s/it]


pre tokenize: 100%|██████████| 4/4 [00:00<00:00, 82.89it/s]


Inference Embeddings:   0%|          | 0/4 [00:00<?, ?it/s]

Inference Embeddings:  25%|██▌       | 1/4 [00:06<00:18,  6.26s/it]

Inference Embeddings:  50%|█████     | 2/4 [00:07<00:06,  3.15s/it]

Inference Embeddings:  75%|███████▌  | 3/4 [00:08<00:02,  2.07s/it]

Inference Embeddings: 100%|██████████| 4/4 [00:08<00:00,  2.10s/it]


pre tokenize: 100%|██████████| 4/4 [00:00<00:00, 59.79it/s]


Inference Embeddings:   0%|          | 0/4 [00:00<?, ?it/s]

Inference Embeddings:  25%|██▌       | 1/4 [00:07<00:21,  7.16s/it]

Inference Embeddings:  50%|█████     | 2/4 [00:08<00:07,  3.53s/it]

Inference Embeddings: 100%|██████████| 4/4 [00:08<00:00,  2.20s/it]


pre tokenize: 100%|██████████| 2/2 [00:00<00:00, 98.50it/s]


Inference Embeddings:   0%|          | 0/2 [00:00<?, ?it/s]

Inference Embeddings:  50%|█████     | 1/2 [00:04<00:04,  4.24s/it]

Inference Embeddings: 100%|██████████| 2/2 [00:04<00:00,  2.34s/it]


pre tokenize: 100%|██████████| 2/2 [00:00<00:00, 86.28it/s]


Inference Embeddings:   0%|          | 0/2 [00:00<?, ?it/s]

Inference Embeddings:  50%|█████     | 1/2 [00:04<00:04,  4.59s/it]

Inference Embeddings: 100%|██████████| 2/2 [00:05<00:00,  2.56s/it]


pre tokenize: 100%|██████████| 6/6 [00:00<00:00, 92.05it/s]


Inference Embeddings:   0%|          | 0/6 [00:00<?, ?it/s]

Inference Embeddings:  17%|█▋        | 1/6 [00:05<00:26,  5.21s/it]

Inference Embeddings:  33%|███▎      | 2/6 [00:06<00:11,  2.76s/it]

Inference Embeddings:  50%|█████     | 3/6 [00:07<00:05,  1.91s/it]

Inference Embeddings:  67%|██████▋   | 4/6 [00:07<00:02,  1.44s/it]

Inference Embeddings:  83%|████████▎ | 5/6 [00:08<00:01,  1.15s/it]

Inference Embeddings: 100%|██████████| 6/6 [00:08<00:00,  1.48s/it]


pre tokenize: 100%|██████████| 2/2 [00:00<00:00, 84.65it/s]


Inference Embeddings:   0%|          | 0/2 [00:00<?, ?it/s]

Inference Embeddings:  50%|█████     | 1/2 [00:07<00:07,  7.70s/it]

Inference Embeddings: 100%|██████████| 2/2 [00:07<00:00,  3.97s/it]


pre tokenize:   0%|          | 0/9 [00:00<?, ?it/s]

pre tokenize: 100%|██████████| 9/9 [00:00<00:00, 74.74it/s]


Inference Embeddings:   0%|          | 0/9 [00:00<?, ?it/s]

Inference Embeddings:  11%|█         | 1/9 [00:08<01:06,  8.28s/it]

Inference Embeddings:  22%|██▏       | 2/9 [00:09<00:29,  4.23s/it]

Inference Embeddings:  33%|███▎      | 3/9 [00:10<00:17,  2.84s/it]

Inference Embeddings:  44%|████▍     | 4/9 [00:11<00:10,  2.13s/it]

Inference Embeddings:  56%|█████▌    | 5/9 [00:12<00:06,  1.70s/it]

Inference Embeddings:  67%|██████▋   | 6/9 [00:13<00:04,  1.40s/it]

Inference Embeddings:  78%|███████▊  | 7/9 [00:14<00:02,  1.18s/it]

Inference Embeddings:  89%|████████▉ | 8/9 [00:15<00:01,  1.02s/it]

Inference Embeddings: 100%|██████████| 9/9 [00:15<00:00,  1.73s/it]


pre tokenize: 100%|██████████| 8/8 [00:00<00:00, 85.82it/s]


Inference Embeddings:   0%|          | 0/8 [00:00<?, ?it/s]

Inference Embeddings:  12%|█▎        | 1/8 [00:06<00:45,  6.47s/it]

Inference Embeddings:  25%|██▌       | 2/8 [00:07<00:21,  3.51s/it]

Inference Embeddings:  38%|███▊      | 3/8 [00:09<00:12,  2.46s/it]

Inference Embeddings:  50%|█████     | 4/8 [00:10<00:07,  1.89s/it]

Inference Embeddings:  62%|██████▎   | 5/8 [00:11<00:04,  1.54s/it]

Inference Embeddings:  75%|███████▌  | 6/8 [00:11<00:02,  1.33s/it]

Inference Embeddings:  88%|████████▊ | 7/8 [00:12<00:01,  1.12s/it]

Inference Embeddings: 100%|██████████| 8/8 [00:12<00:00,  1.60s/it]


pre tokenize: 100%|██████████| 8/8 [00:00<00:00, 94.35it/s]


Inference Embeddings:   0%|          | 0/8 [00:00<?, ?it/s]

Inference Embeddings:  12%|█▎        | 1/8 [00:05<00:35,  5.00s/it]

Inference Embeddings:  25%|██▌       | 2/8 [00:06<00:16,  2.70s/it]

Inference Embeddings:  38%|███▊      | 3/8 [00:07<00:09,  1.90s/it]

Inference Embeddings:  50%|█████     | 4/8 [00:07<00:05,  1.50s/it]

Inference Embeddings:  62%|██████▎   | 5/8 [00:08<00:03,  1.22s/it]

Inference Embeddings:  75%|███████▌  | 6/8 [00:09<00:02,  1.05s/it]

Inference Embeddings:  88%|████████▊ | 7/8 [00:09<00:00,  1.13it/s]

Inference Embeddings: 100%|██████████| 8/8 [00:10<00:00,  1.28s/it]


pre tokenize: 100%|██████████| 3/3 [00:00<00:00, 73.60it/s]


Inference Embeddings:   0%|          | 0/3 [00:00<?, ?it/s]

Inference Embeddings:  33%|███▎      | 1/3 [00:07<00:15,  7.67s/it]

Inference Embeddings:  67%|██████▋   | 2/3 [00:08<00:03,  3.70s/it]

Inference Embeddings: 100%|██████████| 3/3 [00:08<00:00,  2.96s/it]


pre tokenize: 100%|██████████| 2/2 [00:00<00:00, 110.33it/s]


Inference Embeddings:   0%|          | 0/2 [00:00<?, ?it/s]

Inference Embeddings:  50%|█████     | 1/2 [00:04<00:04,  4.51s/it]

Inference Embeddings: 100%|██████████| 2/2 [00:04<00:00,  2.39s/it]


pre tokenize: 100%|██████████| 3/3 [00:00<00:00, 76.90it/s]


Inference Embeddings:   0%|          | 0/3 [00:00<?, ?it/s]

Inference Embeddings:  33%|███▎      | 1/3 [00:04<00:09,  4.59s/it]

Inference Embeddings:  67%|██████▋   | 2/3 [00:05<00:02,  2.40s/it]

Inference Embeddings: 100%|██████████| 3/3 [00:05<00:00,  1.96s/it]


pre tokenize: 100%|██████████| 2/2 [00:00<00:00, 83.50it/s]


Inference Embeddings:   0%|          | 0/2 [00:00<?, ?it/s]

Inference Embeddings:  50%|█████     | 1/2 [00:09<00:09,  9.40s/it]

Inference Embeddings: 100%|██████████| 2/2 [00:09<00:00,  4.81s/it]


pre tokenize: 100%|██████████| 5/5 [00:00<00:00, 73.02it/s]


Inference Embeddings:   0%|          | 0/5 [00:00<?, ?it/s]

Inference Embeddings:  20%|██        | 1/5 [00:06<00:25,  6.34s/it]

Inference Embeddings:  40%|████      | 2/5 [00:07<00:10,  3.43s/it]

Inference Embeddings:  60%|██████    | 3/5 [00:08<00:04,  2.37s/it]

Inference Embeddings:  80%|████████  | 4/5 [00:09<00:01,  1.78s/it]

Inference Embeddings: 100%|██████████| 5/5 [00:10<00:00,  2.06s/it]


pre tokenize: 100%|██████████| 8/8 [00:00<00:00, 86.30it/s]


Inference Embeddings:   0%|          | 0/8 [00:00<?, ?it/s]

Inference Embeddings:  12%|█▎        | 1/8 [00:06<00:48,  6.96s/it]

Inference Embeddings:  25%|██▌       | 2/8 [00:08<00:22,  3.68s/it]

Inference Embeddings:  38%|███▊      | 3/8 [00:09<00:12,  2.50s/it]

Inference Embeddings:  50%|█████     | 4/8 [00:10<00:07,  1.88s/it]

Inference Embeddings:  62%|██████▎   | 5/8 [00:11<00:04,  1.53s/it]

Inference Embeddings:  75%|███████▌  | 6/8 [00:12<00:02,  1.27s/it]

Inference Embeddings: 100%|██████████| 8/8 [00:12<00:00,  1.61s/it]

18869
5777

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
len(dpo1["2"].unique())

9346

In [ ]:
len(dpo1["labels"].unique())

3273

In [ ]:
dpo1["2"] = dpo1["labels"]
dpo1 = dpo1[["0", "1", "2"]]
dpo1.head()

,0,1,2
0,attack,"tiring breeze , and the grief - like and hollo...","An attempt to harm, damage, debilitate, or des..."
1,attack,"Ik saai , Ik hab mien dout , "" and having thus...","A violent assault, whether physical or verbal."
2,attack,"Having determined instantly , in his own mind ...","A violent engagement of bodies, either by land..."
3,attack,What is remarkable in these and in all the oth...,"A violent assault, for example on a building; ..."
4,attack,Just as they had taken their seats around the ...,An attempt to detract from the worth or credib...

In [ ]:
dpo1.to_csv("drive/MyDrive/generated_definitions/english/dpo-clustered/english-corpus1.tsv.gz", sep='\t', index=False, compression="gzip")

In [ ]:
dpo2["2"] = dpo2["labels"]
dpo2 = dpo2[["0", "1", "2"]]
dpo2.to_csv("drive/MyDrive/generated_definitions/english/dpo-clustered/english-corpus2.tsv.gz", sep='\t', index=False, compression="gzip")
dpo2.head()

,0,1,2
447,attack,"to listen to words of peace , and avert by ful...",An attempt to detract from the worth or credib...
448,attack,"The tabloid TV shows , like "" Hard Copy "" and ...","An attempt to cause damage, injury to, or deat..."
449,attack,We believe that the United States should pursu...,An attempt to detract from the worth or credib...
450,attack,"However , when one discovers that Snyder 's ga...",An attempt to detract from the worth or credib...
451,attack,Yet the reality today is worse than fiction : ...,"(Medicine) An acute myocardial infarction, som..."

In [ ]:
from collections import Counter

In [ ]:
def cluster_sep(method, eng_path, n):
    method_path = os.path.join(eng_path, method)
    if method != "greedy":
        data = pd.read_csv(os.path.join(method_path, f"english-corpus{n}.tsv.gz"), sep="\t", compression="gzip")
    else:
        data = pd.read_csv(os.path.join(method_path, f"english-corpus{n}.tsv.gz"), sep="\t", compression="gzip", header=None, names=('0', '1', '2'))
    to_concat = pd.DataFrame()
    for target, target_df in tqdm(data.groupby("0")):
        definitions = target_df["2"].unique()

        if len(definitions) > 1:
            # print(len(definitions))
            clustering = AgglomerativeClustering(
                n_clusters=None, metric="cosine", linkage="complete", distance_threshold=0.2, compute_full_tree=True,
            )
            embeddings = model.encode(definitions.tolist(),
                                    max_length=2048, # If you don't need such a long length, you can set a smaller value to speed up the encoding process.
                                    )['dense_vecs']
            labels = clustering.fit_predict(embeddings)
            labels_def = []
            for label in np.unique(labels):
                idx = np.where(labels == label)[0]
                first_definition = Counter(definitions[idx]).most_common()[0][0]
                labels_def.append(first_definition)
            # print(labels_def)

            labels_list = []
            for i, row in target_df.iterrows():
                idx = np.where(definitions == row["2"])
                label = labels[idx].tolist()[0]
                labels_list.append(labels_def[label])
            target_df["labels"] = labels_list
        else:
            target_df["labels"] = target_df["2"]

        to_concat = pd.concat([to_concat, target_df])
    assert len(to_concat) == len(data)
    to_concat = to_concat.reset_index(drop=True)
    print(len(to_concat["2"].unique()))
    print(len(to_concat["labels"].unique()))
    return to_concat

In [ ]:
for method in ("dpo", "periti_2024", "periti_2025"):
    print(method)
    new_dir = os.path.join(eng_path, f"{method}-clustered-sep/")
    os.makedirs(new_dir, exist_ok=True)
    for n in (1, 2):
        print(n)
        method_result = cluster_sep(method, eng_path, n)
        method_result["2"] = method_result["labels"]
        method_result.drop("labels", inplace=True, axis=1)
        method_result.to_csv(f"{new_dir}english-corpus{n}.tsv.gz", sep='\t', index=False, compression="gzip")
        method_result.head()

dpo
1

  0%|          | 0/37 [00:00<?, ?it/s]

pre tokenize: 100%|██████████| 2/2 [00:00<00:00, 132.00it/s]

Inference Embeddings:   0%|          | 0/2 [00:00<?, ?it/s]
Inference Embeddings:  50%|█████     | 1/2 [00:09<00:09,  9.70s/it]
Inference Embeddings: 100%|██████████| 2/2 [00:09<00:00,  4.94s/it]

pre tokenize: 100%|██████████| 4/4 [00:00<00:00, 114.26it/s]

Inference Embeddings:   0%|          | 0/4 [00:00<?, ?it/s]
Inference Embeddings:  25%|██▌       | 1/4 [00:05<00:16,  5.42s/it]
Inference Embeddings:  50%|█████     | 2/4 [00:06<00:05,  2.80s/it]
Inference Embeddings: 100%|██████████| 4/4 [00:07<00:00,  1.78s/it]

pre tokenize: 100%|██████████| 6/6 [00:00<00:00, 97.15it/s]

Inference Embeddings:   0%|          | 0/6 [00:00<?, ?it/s]
Inference Embeddings:  17%|█▋        | 1/6 [00:07<00:39,  7.88s/it]
Inference Embeddings:  33%|███▎      | 2/6 [00:09<00:15,  3.93s/it]
Inference Embeddings:  50%|█████     | 3/6 [00:09<00:07,  2.55s/it]
Inference Embeddings:  67%|██████▋   | 4/6 [00:10<00:03,  1.84s/it]
Inference Embeddings: 100%|██████████| 6/6 [00:11<00:00,  1.90s/it]

pre tokenize: 100%|██████████| 5/5 [00:00<00:00, 88.55it/s]

Inference Embeddings:   0%|          | 0/5 [00:00<?, ?it/s]
Inference Embeddings:  20%|██        | 1/5 [00:05<00:23,  5.97s/it]
Inference Embeddings:  40%|████      | 2/5 [00:07<00:09,  3.16s/it]
Inference Embeddings:  60%|██████    | 3/5 [00:08<00:04,  2.14s/it]
Inference Embeddings:  80%|████████  | 4/5 [00:08<00:01,  1.63s/it]
Inference Embeddings: 100%|██████████| 5/5 [00:09<00:00,  1.89s/it]

pre tokenize: 100%|██████████| 6/6 [00:00<00:00, 97.89it/s]

Inference Embeddings:   0%|          | 0/6 [00:00<?, ?it/s]
Inference Embeddings:  17%|█▋        | 1/6 [00:04<00:24,  4.81s/it]
Inference Embeddings:  33%|███▎      | 2/6 [00:05<00:10,  2.53s/it]
Inference Embeddings:  50%|█████     | 3/6 [00:06<00:05,  1.76s/it]
Inference Embeddings:  67%|██████▋   | 4/6 [00:07<00:02,  1.32s/it]
Inference Embeddings: 100%|██████████| 6/6 [00:07<00:00,  1.30s/it]

pre tokenize: 100%|██████████| 3/3 [00:00<00:00, 67.21it/s]

Inference Embeddings:   0%|          | 0/3 [00:00<?, ?it/s]
Inference Embeddings:  33%|███▎      | 1/3 [00:06<00:12,  6.26s/it]
Inference Embeddings:  67%|██████▋   | 2/3 [00:07<00:03,  3.29s/it]
Inference Embeddings: 100%|██████████| 3/3 [00:08<00:00,  2.76s/it]

pre tokenize: 100%|██████████| 5/5 [00:00<00:00, 87.91it/s]

Inference Embeddings:   0%|          | 0/5 [00:00<?, ?it/s]
Inference Embeddings:  20%|██        | 1/5 [00:05<00:20,  5.17s/it]
Inference Embeddings:  40%|████      | 2/5 [00:06<00:08,  2.78s/it]
Inference Embeddings:  60%|██████    | 3/5 [00:07<00:03,  1.92s/it]
Inference Embeddings:  80%|████████  | 4/5 [00:07<00:01,  1.45s/it]
Inference Embeddings: 100%|██████████| 5/5 [00:08<00:00,  1.61s/it]

9346
2836
2

  0%|          | 0/37 [00:00<?, ?it/s]

pre tokenize: 100%|██████████| 2/2 [00:00<00:00, 69.75it/s]

Inference Embeddings:   0%|          | 0/2 [00:00<?, ?it/s]
Inference Embeddings:  50%|█████     | 1/2 [00:05<00:05,  5.15s/it]
Inference Embeddings: 100%|██████████| 2/2 [00:05<00:00,  2.69s/it]

pre tokenize: 100%|██████████| 3/3 [00:00<00:00, 85.49it/s]

Inference Embeddings:   0%|          | 0/3 [00:00<?, ?it/s]
Inference Embeddings:  33%|███▎      | 1/3 [00:06<00:13,  6.98s/it]
Inference Embeddings:  67%|██████▋   | 2/3 [00:08<00:03,  3.55s/it]
Inference Embeddings: 100%|██████████| 3/3 [00:08<00:00,  2.93s/it]

pre tokenize: 100%|██████████| 3/3 [00:00<00:00, 116.86it/s]

Inference Embeddings:   0%|          | 0/3 [00:00<?, ?it/s]
Inference Embeddings:  33%|███▎      | 1/3 [00:07<00:15,  7.57s/it]
Inference Embeddings: 100%|██████████| 3/3 [00:08<00:00,  2.83s/it]

pre tokenize: 100%|██████████| 2/2 [00:00<00:00, 160.49it/s]

Inference Embeddings:   0%|          | 0/2 [00:00<?, ?it/s]
Inference Embeddings: 100%|██████████| 2/2 [00:04<00:00,  2.30s/it]

pre tokenize: 100%|██████████| 2/2 [00:00<00:00, 103.98it/s]

Inference Embeddings:   0%|          | 0/2 [00:00<?, ?it/s]
Inference Embeddings:  50%|█████     | 1/2 [00:04<00:04,  4.78s/it]
Inference Embeddings: 100%|██████████| 2/2 [00:05<00:00,  2.51s/it]

pre tokenize: 100%|██████████| 4/4 [00:00<00:00, 111.34it/s]

Inference Embeddings:   0%|          | 0/4 [00:00<?, ?it/s]
Inference Embeddings:  25%|██▌       | 1/4 [00:05<00:16,  5.42s/it]
Inference Embeddings:  50%|█████     | 2/4 [00:06<00:05,  2.79s/it]
Inference Embeddings:  75%|███████▌  | 3/4 [00:07<00:01,  1.84s/it]
Inference Embeddings: 100%|██████████| 4/4 [00:07<00:00,  1.80s/it]

pre tokenize: 100%|██████████| 2/2 [00:00<00:00, 106.46it/s]

Inference Embeddings:   0%|          | 0/2 [00:00<?, ?it/s]
Inference Embeddings: 100%|██████████| 2/2 [00:07<00:00,  3.90s/it]

pre tokenize: 100%|██████████| 5/5 [00:00<00:00, 98.93it/s]

Inference Embeddings:   0%|          | 0/5 [00:00<?, ?it/s]
Inference Embeddings:  20%|██        | 1/5 [00:05<00:23,  5.79s/it]
Inference Embeddings:  40%|████      | 2/5 [00:06<00:09,  3.02s/it]
Inference Embeddings:  60%|██████    | 3/5 [00:07<00:04,  2.04s/it]
Inference Embeddings:  80%|████████  | 4/5 [00:08<00:01,  1.50s/it]
Inference Embeddings: 100%|██████████| 5/5 [00:08<00:00,  1.75s/it]

pre tokenize: 100%|██████████| 4/4 [00:00<00:00, 57.28it/s]

Inference Embeddings:   0%|          | 0/4 [00:00<?, ?it/s]
Inference Embeddings:  25%|██▌       | 1/4 [00:06<00:18,  6.12s/it]
Inference Embeddings:  50%|█████     | 2/4 [00:07<00:06,  3.15s/it]
Inference Embeddings: 100%|██████████| 4/4 [00:08<00:00,  2.04s/it]

pre tokenize: 100%|██████████| 4/4 [00:00<00:00, 54.12it/s]

Inference Embeddings:   0%|          | 0/4 [00:00<?, ?it/s]
Inference Embeddings:  25%|██▌       | 1/4 [00:03<00:10,  3.63s/it]
Inference Embeddings:  50%|█████     | 2/4 [00:04<00:04,  2.01s/it]
Inference Embeddings:  75%|███████▌  | 3/4 [00:05<00:01,  1.39s/it]
Inference Embeddings: 100%|██████████| 4/4 [00:05<00:00,  1.37s/it]

pre tokenize: 100%|██████████| 2/2 [00:00<00:00, 70.61it/s]

Inference Embeddings:   0%|          | 0/2 [00:00<?, ?it/s]
Inference Embeddings:  50%|█████     | 1/2 [00:07<00:07,  7.65s/it]
Inference Embeddings: 100%|██████████| 2/2 [00:08<00:00,  4.25s/it]

pre tokenize: 100%|██████████| 2/2 [00:00<00:00, 117.77it/s]

Inference Embeddings:   0%|          | 0/2 [00:00<?, ?it/s]
Inference Embeddings: 100%|██████████| 2/2 [00:04<00:00,  2.32s/it]

pre tokenize: 100%|██████████| 2/2 [00:00<00:00, 36.86it/s]

Inference Embeddings:   0%|          | 0/2 [00:00<?, ?it/s]
Inference Embeddings:  50%|█████     | 1/2 [00:04<00:04,  4.64s/it]
Inference Embeddings: 100%|██████████| 2/2 [00:05<00:00,  2.75s/it]

pre tokenize: 100%|██████████| 2/2 [00:00<00:00, 91.66it/s]

Inference Embeddings:   0%|          | 0/2 [00:00<?, ?it/s]
Inference Embeddings: 100%|██████████| 2/2 [00:09<00:00,  4.72s/it]

pre tokenize: 100%|██████████| 3/3 [00:00<00:00, 86.02it/s]

Inference Embeddings:   0%|          | 0/3 [00:00<?, ?it/s]
Inference Embeddings:  33%|███▎      | 1/3 [00:04<00:09,  4.83s/it]
Inference Embeddings:  67%|██████▋   | 2/3 [00:05<00:02,  2.63s/it]
Inference Embeddings: 100%|██████████| 3/3 [00:06<00:00,  2.03s/it]

pre tokenize: 100%|██████████| 4/4 [00:00<00:00, 77.86it/s]

Inference Embeddings:   0%|          | 0/4 [00:00<?, ?it/s]
Inference Embeddings:  25%|██▌       | 1/4 [00:06<00:20,  6.89s/it]
Inference Embeddings:  50%|█████     | 2/4 [00:07<00:06,  3.48s/it]
Inference Embeddings:  75%|███████▌  | 3/4 [00:08<00:02,  2.29s/it]
Inference Embeddings: 100%|██████████| 4/4 [00:09<00:00,  2.33s/it]

11018
3885
periti_2024
1

  0%|          | 0/37 [00:00<?, ?it/s]

pre tokenize: 100%|██████████| 2/2 [00:00<00:00, 106.91it/s]

Inference Embeddings:   0%|          | 0/2 [00:00<?, ?it/s]
Inference Embeddings:  50%|█████     | 1/2 [00:03<00:03,  3.79s/it]
Inference Embeddings: 100%|██████████| 2/2 [00:03<00:00,  2.00s/it]

pre tokenize: 100%|██████████| 2/2 [00:00<00:00, 78.78it/s]

Inference Embeddings:   0%|          | 0/2 [00:00<?, ?it/s]
Inference Embeddings: 100%|██████████| 2/2 [00:06<00:00,  3.45s/it]

pre tokenize: 100%|██████████| 2/2 [00:00<00:00, 83.81it/s]

Inference Embeddings:   0%|          | 0/2 [00:00<?, ?it/s]
Inference Embeddings: 100%|██████████| 2/2 [00:04<00:00,  2.14s/it]

pre tokenize: 100%|██████████| 5/5 [00:00<00:00, 52.22it/s]

Inference Embeddings:   0%|          | 0/21 [00:00<?, ?it/s]
Inference Embeddings:   5%|▍         | 1/21 [01:00<20:02, 60.11s/it]
Inference Embeddings:  10%|▉         | 2/21 [01:00<07:57, 25.12s/it]
Inference Embeddings:  14%|█▍        | 3/21 [01:01<04:10, 13.91s/it]
Inference Embeddings:  19%|█▉        | 4/21 [01:01<02:26,  8.63s/it]
Inference Embeddings:  24%|██▍       | 5/21 [01:02<01:30,  5.67s/it]
Inference Embeddings:  29%|██▊       | 6/21 [01:02<00:58,  3.88s/it]
Inference Embeddings:  33%|███▎      | 7/21 [01:02<00:38,  2.72s/it]
Inference Embeddings:  38%|███▊      | 8/21 [01:03<00:25,  1.95s/it]
Inference Embeddings:  43%|████▎     | 9/21 [01:03<00:17,  1.45s/it]
Inference Embeddings:  48%|████▊     | 10/21 [01:03<00:12,  1.10s/it]
Inference Embeddings:  52%|█████▏    | 11/21 [01:04<00:08,  1.16it/s]
Inference Embeddings:  57%|█████▋    | 12/21 [01:04<00:06,  1.47it/s]
Inference Embeddings:  62%|██████▏   | 13/21 [01:04<00:04,  1.85it/s]
Inference Embeddings:  67%|██████▋   | 14/21 [01:05<00:03,  2.25it/s]
Inference Embeddings:  71%|███████▏  | 15/21 [01:05<00:02,  2.63it/s]
Inference Embeddings:  76%|███████▌  | 16/21 [01:05<00:01,  3.03it/s]
Inference Embeddings:  81%|████████  | 17/21 [01:05<00:01,  3.44it/s]
Inference Embeddings:  86%|████████▌ | 18/21 [01:05<00:00,  3.81it/s]
Inference Embeddings:  90%|█████████ | 19/21 [01:06<00:00,  4.33it/s]
Inference Embeddings:  95%|█████████▌| 20/21 [01:06<00:00,  5.09it/s]
Inference Embeddings: 100%|██████████| 21/21 [01:06<00:00,  3.15s/it]

pre tokenize: 100%|██████████| 6/6 [00:00<00:00, 74.09it/s]

Inference Embeddings:   0%|          | 0/23 [00:00<?, ?it/s]
Inference Embeddings:   4%|▍         | 1/23 [00:59<21:55, 59.80s/it]
Inference Embeddings:   9%|▊         | 2/23 [01:00<08:44, 24.96s/it]
Inference Embeddings:  13%|█▎        | 3/23 [01:00<04:35, 13.76s/it]
Inference Embeddings:  17%|█▋        | 4/23 [01:01<02:41,  8.49s/it]
Inference Embeddings:  22%|██▏       | 5/23 [01:01<01:39,  5.55s/it]
Inference Embeddings:  26%|██▌       | 6/23 [01:01<01:04,  3.78s/it]
Inference Embeddings:  30%|███       | 7/23 [01:02<00:42,  2.65s/it]
Inference Embeddings:  35%|███▍      | 8/23 [01:02<00:28,  1.89s/it]
Inference Embeddings:  39%|███▉      | 9/23 [01:02<00:19,  1.39s/it]
Inference Embeddings:  43%|████▎     | 10/23 [01:03<00:13,  1.03s/it]
Inference Embeddings:  48%|████▊     | 11/23 [01:03<00:09,  1.28it/s]
Inference Embeddings:  52%|█████▏    | 12/23 [01:03<00:06,  1.64it/s]
Inference Embeddings:  57%|█████▋    | 13/23 [01:03<00:04,  2.05it/s]
Inference Embeddings:  61%|██████    | 14/23 [01:03<00:03,  2.49it/s]
Inference Embeddings:  65%|██████▌   | 15/23 [01:04<00:02,  2.95it/s]
Inference Embeddings:  70%|██████▉   | 16/23 [01:04<00:02,  3.43it/s]
Inference Embeddings:  74%|███████▍  | 17/23 [01:04<00:01,  3.98it/s]
Inference Embeddings:  78%|███████▊  | 18/23 [01:04<00:01,  4.52it/s]
Inference Embeddings:  83%|████████▎ | 19/23 [01:04<00:00,  5.26it/s]
Inference Embeddings:  87%|████████▋ | 20/23 [01:04<00:00,  5.95it/s]
Inference Embeddings:  91%|█████████▏| 21/23 [01:04<00:00,  6.69it/s]
Inference Embeddings: 100%|██████████| 23/23 [01:04<00:00,  2.83s/it]

pre tokenize: 100%|██████████| 5/5 [00:00<00:00, 50.92it/s]

Inference Embeddings:   0%|          | 0/19 [00:00<?, ?it/s]
Inference Embeddings:   5%|▌         | 1/19 [01:00<18:00, 60.02s/it]
Inference Embeddings:  11%|█         | 2/19 [01:00<07:04, 24.96s/it]
Inference Embeddings:  16%|█▌        | 3/19 [01:00<03:39, 13.72s/it]
Inference Embeddings:  21%|██        | 4/19 [01:01<02:06,  8.44s/it]
Inference Embeddings:  26%|██▋       | 5/19 [01:01<01:17,  5.51s/it]
Inference Embeddings:  32%|███▏      | 6/19 [01:01<00:48,  3.73s/it]
Inference Embeddings:  37%|███▋      | 7/19 [01:01<00:30,  2.58s/it]
Inference Embeddings:  42%|████▏     | 8/19 [01:02<00:20,  1.83s/it]
Inference Embeddings:  47%|████▋     | 9/19 [01:02<00:13,  1.33s/it]
Inference Embeddings:  53%|█████▎    | 10/19 [01:02<00:08,  1.01it/s]
Inference Embeddings:  58%|█████▊    | 11/19 [01:02<00:05,  1.34it/s]
Inference Embeddings:  63%|██████▎   | 12/19 [01:03<00:04,  1.72it/s]
Inference Embeddings:  68%|██████▊   | 13/19 [01:03<00:02,  2.15it/s]
Inference Embeddings:  74%|███████▎  | 14/19 [01:03<00:01,  2.65it/s]
Inference Embeddings:  79%|███████▉  | 15/19 [01:03<00:01,  3.21it/s]
Inference Embeddings:  84%|████████▍ | 16/19 [01:03<00:00,  3.80it/s]
Inference Embeddings:  89%|████████▉ | 17/19 [01:03<00:00,  4.56it/s]
Inference Embeddings: 100%|██████████| 19/19 [01:03<00:00,  3.37s/it]

pre tokenize:   0%|          | 0/10 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 10/10 [00:00<00:00, 65.78it/s]

Inference Embeddings:   0%|          | 0/42 [00:00<?, ?it/s]
Inference Embeddings:   2%|▏         | 1/42 [00:59<40:50, 59.78s/it]
Inference Embeddings:   5%|▍         | 2/42 [01:00<16:35, 24.90s/it]
Inference Embeddings:   7%|▋         | 3/42 [01:00<08:55, 13.73s/it]
Inference Embeddings:  10%|▉         | 4/42 [01:01<05:20,  8.44s/it]
Inference Embeddings:  12%|█▏        | 5/42 [01:01<03:24,  5.52s/it]
Inference Embeddings:  14%|█▍        | 6/42 [01:01<02:15,  3.77s/it]
Inference Embeddings:  17%|█▋        | 7/42 [01:02<01:32,  2.64s/it]
Inference Embeddings:  19%|█▉        | 8/42 [01:02<01:04,  1.90s/it]
Inference Embeddings:  21%|██▏       | 9/42 [01:02<00:45,  1.39s/it]
Inference Embeddings:  24%|██▍       | 10/42 [01:02<00:33,  1.05s/it]
Inference Embeddings:  26%|██▌       | 11/42 [01:03<00:25,  1.23it/s]
Inference Embeddings:  29%|██▊       | 12/42 [01:03<00:18,  1.58it/s]
Inference Embeddings:  31%|███       | 13/42 [01:03<00:14,  1.97it/s]
Inference Embeddings:  33%|███▎      | 14/42 [01:03<00:11,  2.36it/s]
Inference Embeddings:  36%|███▌      | 15/42 [01:04<00:09,  2.74it/s]
Inference Embeddings:  38%|███▊      | 16/42 [01:04<00:08,  3.07it/s]
Inference Embeddings:  40%|████      | 17/42 [01:04<00:07,  3.35it/s]
Inference Embeddings:  43%|████▎     | 18/42 [01:04<00:06,  3.67it/s]
Inference Embeddings:  45%|████▌     | 19/42 [01:04<00:05,  3.97it/s]
Inference Embeddings:  48%|████▊     | 20/42 [01:05<00:05,  4.20it/s]
Inference Embeddings:  50%|█████     | 21/42 [01:05<00:04,  4.38it/s]
Inference Embeddings:  52%|█████▏    | 22/42 [01:05<00:04,  4.53it/s]
Inference Embeddings:  55%|█████▍    | 23/42 [01:05<00:04,  4.64it/s]
Inference Embeddings:  57%|█████▋    | 24/42 [01:05<00:03,  4.78it/s]
Inference Embeddings:  60%|█████▉    | 25/42 [01:06<00:03,  4.92it/s]
Inference Embeddings:  62%|██████▏   | 26/42 [01:06<00:03,  4.98it/s]
Inference Embeddings:  64%|██████▍   | 27/42 [01:06<00:02,  5.16it/s]
Inference Embeddings:  67%|██████▋   | 28/42 [01:06<00:02,  5.30it/s]
Inference Embeddings:  69%|██████▉   | 29/42 [01:06<00:02,  5.58it/s]
Inference Embeddings:  71%|███████▏  | 30/42 [01:07<00:02,  5.80it/s]
Inference Embeddings:  74%|███████▍  | 31/42 [01:07<00:01,  5.97it/s]
Inference Embeddings:  76%|███████▌  | 32/42 [01:07<00:01,  6.16it/s]
Inference Embeddings:  79%|███████▊  | 33/42 [01:07<00:01,  6.23it/s]
Inference Embeddings:  81%|████████  | 34/42 [01:07<00:01,  6.81it/s]
Inference Embeddings:  83%|████████▎ | 35/42 [01:07<00:00,  7.32it/s]
Inference Embeddings:  86%|████████▌ | 36/42 [01:07<00:00,  7.66it/s]
Inference Embeddings:  88%|████████▊ | 37/42 [01:07<00:00,  7.91it/s]
Inference Embeddings:  90%|█████████ | 38/42 [01:08<00:00,  8.32it/s]
Inference Embeddings:  93%|█████████▎| 39/42 [01:08<00:00,  8.61it/s]
Inference Embeddings: 100%|██████████| 42/42 [01:08<00:00,  1.63s/it]

pre tokenize: 100%|██████████| 2/2 [00:00<00:00, 91.65it/s]

Inference Embeddings:   0%|          | 0/2 [00:00<?, ?it/s]
Inference Embeddings: 100%|██████████| 2/2 [00:06<00:00,  3.10s/it]

pre tokenize: 100%|██████████| 2/2 [00:00<00:00, 68.48it/s]

Inference Embeddings:   0%|          | 0/2 [00:00<?, ?it/s]
Inference Embeddings:  50%|█████     | 1/2 [00:05<00:05,  5.40s/it]
Inference Embeddings: 100%|██████████| 2/2 [00:05<00:00,  2.92s/it]

pre tokenize:   0%|          | 0/7 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 7/7 [00:00<00:00, 66.15it/s]

Inference Embeddings:   0%|          | 0/7 [00:00<?, ?it/s]
Inference Embeddings:  14%|█▍        | 1/7 [00:14<01:27, 14.64s/it]
Inference Embeddings:  29%|██▊       | 2/7 [00:16<00:34,  6.97s/it]
Inference Embeddings:  43%|████▎     | 3/7 [00:17<00:17,  4.42s/it]
Inference Embeddings:  57%|█████▋    | 4/7 [00:18<00:09,  3.14s/it]
Inference Embeddings:  71%|███████▏  | 5/7 [00:19<00:04,  2.36s/it]
Inference Embeddings:  86%|████████▌ | 6/7 [00:20<00:01,  1.86s/it]
Inference Embeddings: 100%|██████████| 7/7 [00:20<00:00,  2.99s/it]

pre tokenize:   0%|          | 0/9 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 9/9 [00:00<00:00, 59.22it/s]

Inference Embeddings:   0%|          | 0/9 [00:00<?, ?it/s]
Inference Embeddings:  11%|█         | 1/9 [00:18<02:26, 18.32s/it]
Inference Embeddings:  22%|██▏       | 2/9 [00:20<01:02,  8.93s/it]
Inference Embeddings:  33%|███▎      | 3/9 [00:22<00:33,  5.61s/it]
Inference Embeddings:  44%|████▍     | 4/9 [00:23<00:19,  3.89s/it]
Inference Embeddings:  56%|█████▌    | 5/9 [00:24<00:11,  2.80s/it]
Inference Embeddings:  67%|██████▋   | 6/9 [00:25<00:06,  2.10s/it]
Inference Embeddings:  78%|███████▊  | 7/9 [00:25<00:03,  1.59s/it]
Inference Embeddings:  89%|████████▉ | 8/9 [00:26<00:01,  1.23s/it]
Inference Embeddings: 100%|██████████| 9/9 [00:26<00:00,  2.93s/it]

13937
3989
2

  0%|          | 0/37 [00:00<?, ?it/s]

pre tokenize: 100%|██████████| 3/3 [00:00<00:00, 65.16it/s]

Inference Embeddings:   0%|          | 0/11 [00:00<?, ?it/s]
Inference Embeddings:   9%|▉         | 1/11 [01:00<10:00, 60.07s/it]
Inference Embeddings:  18%|█▊        | 2/11 [01:00<03:44, 24.92s/it]
Inference Embeddings:  27%|██▋       | 3/11 [01:00<01:49, 13.68s/it]
Inference Embeddings:  36%|███▋      | 4/11 [01:00<00:58,  8.37s/it]
Inference Embeddings:  45%|████▌     | 5/11 [01:01<00:32,  5.43s/it]
Inference Embeddings:  55%|█████▍    | 6/11 [01:01<00:18,  3.66s/it]
Inference Embeddings:  64%|██████▎   | 7/11 [01:01<00:10,  2.53s/it]
Inference Embeddings:  73%|███████▎  | 8/11 [01:01<00:05,  1.78s/it]
Inference Embeddings:  82%|████████▏ | 9/11 [01:01<00:02,  1.28s/it]
Inference Embeddings: 100%|██████████| 11/11 [01:02<00:00,  5.65s/it]

pre tokenize: 100%|██████████| 3/3 [00:00<00:00, 68.58it/s]

Inference Embeddings:   0%|          | 0/3 [00:00<?, ?it/s]
Inference Embeddings:  33%|███▎      | 1/3 [00:08<00:16,  8.33s/it]
Inference Embeddings:  67%|██████▋   | 2/3 [00:09<00:04,  4.22s/it]
Inference Embeddings: 100%|██████████| 3/3 [00:10<00:00,  3.40s/it]

pre tokenize: 100%|██████████| 3/3 [00:00<00:00, 85.65it/s]

Inference Embeddings:   0%|          | 0/3 [00:00<?, ?it/s]
Inference Embeddings:  33%|███▎      | 1/3 [00:07<00:14,  7.09s/it]
Inference Embeddings:  67%|██████▋   | 2/3 [00:07<00:03,  3.43s/it]
Inference Embeddings: 100%|██████████| 3/3 [00:08<00:00,  2.72s/it]

pre tokenize:   0%|          | 0/3 [00:00<?, ?it/s]
pre tokenize:  33%|███▎      | 1/3 [00:00<00:00,  9.27it/s]
pre tokenize: 100%|██████████| 3/3 [00:00<00:00,  9.99it/s]

Inference Embeddings:   0%|          | 0/11 [00:00<?, ?it/s]
Inference Embeddings:   9%|▉         | 1/11 [01:00<10:07, 60.71s/it]
Inference Embeddings:  18%|█▊        | 2/11 [01:01<03:47, 25.24s/it]
Inference Embeddings:  27%|██▋       | 3/11 [01:01<01:50, 13.87s/it]
Inference Embeddings:  36%|███▋      | 4/11 [01:01<00:59,  8.53s/it]
Inference Embeddings:  45%|████▌     | 5/11 [01:02<00:33,  5.55s/it]
Inference Embeddings:  55%|█████▍    | 6/11 [01:02<00:18,  3.74s/it]
Inference Embeddings:  64%|██████▎   | 7/11 [01:02<00:10,  2.59s/it]
Inference Embeddings:  73%|███████▎  | 8/11 [01:02<00:05,  1.83s/it]
Inference Embeddings:  82%|████████▏ | 9/11 [01:02<00:02,  1.31s/it]
Inference Embeddings: 100%|██████████| 11/11 [01:03<00:00,  5.73s/it]

pre tokenize: 100%|██████████| 2/2 [00:00<00:00, 99.22it/s]

Inference Embeddings:   0%|          | 0/2 [00:00<?, ?it/s]
Inference Embeddings:  50%|█████     | 1/2 [00:04<00:04,  4.97s/it]
Inference Embeddings: 100%|██████████| 2/2 [00:05<00:00,  2.59s/it]

Inference Embeddings:   0%|          | 0/2 [00:00<?, ?it/s]
Inference Embeddings:  50%|█████     | 1/2 [01:19<01:19, 79.31s/it]
Inference Embeddings: 100%|██████████| 2/2 [01:19<00:00, 39.77s/it]

pre tokenize: 100%|██████████| 3/3 [00:00<00:00, 81.39it/s]

Inference Embeddings:   0%|          | 0/3 [00:00<?, ?it/s]
Inference Embeddings:  33%|███▎      | 1/3 [00:03<00:07,  3.68s/it]
Inference Embeddings:  67%|██████▋   | 2/3 [00:04<00:02,  2.03s/it]
Inference Embeddings: 100%|██████████| 3/3 [00:04<00:00,  1.66s/it]

pre tokenize:   0%|          | 0/8 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 8/8 [00:00<00:00, 37.66it/s]

Inference Embeddings:   0%|          | 0/23 [00:00<?, ?it/s]
Inference Embeddings:   4%|▍         | 1/23 [01:20<29:37, 80.78s/it]
Inference Embeddings:   9%|▊         | 2/23 [01:21<11:50, 33.83s/it]
Inference Embeddings:  13%|█▎        | 3/23 [01:22<06:14, 18.73s/it]
Inference Embeddings:  17%|█▋        | 4/23 [01:23<03:41, 11.64s/it]
Inference Embeddings:  22%|██▏       | 5/23 [01:24<02:18,  7.71s/it]
Inference Embeddings:  26%|██▌       | 6/23 [01:24<01:30,  5.30s/it]
Inference Embeddings:  30%|███       | 7/23 [01:25<00:59,  3.75s/it]
Inference Embeddings:  35%|███▍      | 8/23 [01:25<00:40,  2.71s/it]
Inference Embeddings:  39%|███▉      | 9/23 [01:26<00:28,  2.00s/it]
Inference Embeddings:  43%|████▎     | 10/23 [01:26<00:19,  1.53s/it]
Inference Embeddings:  48%|████▊     | 11/23 [01:27<00:14,  1.20s/it]
Inference Embeddings:  52%|█████▏    | 12/23 [01:27<00:10,  1.03it/s]
Inference Embeddings:  57%|█████▋    | 13/23 [01:27<00:07,  1.26it/s]
Inference Embeddings:  61%|██████    | 14/23 [01:28<00:05,  1.52it/s]
Inference Embeddings:  65%|██████▌   | 15/23 [01:28<00:04,  1.77it/s]
Inference Embeddings:  70%|██████▉   | 16/23 [01:28<00:03,  2.01it/s]
Inference Embeddings:  74%|███████▍  | 17/23 [01:29<00:02,  2.26it/s]
Inference Embeddings:  78%|███████▊  | 18/23 [01:29<00:01,  2.55it/s]
Inference Embeddings:  83%|████████▎ | 19/23 [01:29<00:01,  2.92it/s]
Inference Embeddings:  87%|████████▋ | 20/23 [01:29<00:00,  3.23it/s]
Inference Embeddings:  91%|█████████▏| 21/23 [01:30<00:00,  3.62it/s]
Inference Embeddings: 100%|██████████| 23/23 [01:30<00:00,  3.93s/it]

pre tokenize: 100%|██████████| 2/2 [00:00<00:00, 55.84it/s]

Inference Embeddings:   0%|          | 0/2 [00:00<?, ?it/s]
Inference Embeddings:  50%|█████     | 1/2 [00:05<00:05,  5.79s/it]
Inference Embeddings: 100%|██████████| 2/2 [00:06<00:00,  3.39s/it]

pre tokenize:   0%|          | 0/6 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 6/6 [00:00<00:00, 33.06it/s]

Inference Embeddings:   0%|          | 0/18 [00:00<?, ?it/s]
Inference Embeddings:   6%|▌         | 1/18 [01:21<23:06, 81.55s/it]
Inference Embeddings:  11%|█         | 2/18 [01:22<09:05, 34.07s/it]
Inference Embeddings:  17%|█▋        | 3/18 [01:23<04:42, 18.84s/it]
Inference Embeddings:  22%|██▏       | 4/18 [01:23<02:42, 11.64s/it]
Inference Embeddings:  28%|██▊       | 5/18 [01:24<01:39,  7.63s/it]
Inference Embeddings:  33%|███▎      | 6/18 [01:24<01:02,  5.20s/it]
Inference Embeddings:  39%|███▉      | 7/18 [01:25<00:40,  3.65s/it]
Inference Embeddings:  44%|████▍     | 8/18 [01:25<00:26,  2.62s/it]
Inference Embeddings:  50%|█████     | 9/18 [01:25<00:17,  1.91s/it]
Inference Embeddings:  56%|█████▌    | 10/18 [01:26<00:11,  1.43s/it]
Inference Embeddings:  61%|██████    | 11/18 [01:26<00:07,  1.08s/it]
Inference Embeddings:  67%|██████▋   | 12/18 [01:26<00:05,  1.20it/s]
Inference Embeddings:  72%|███████▏  | 13/18 [01:27<00:03,  1.54it/s]
Inference Embeddings:  78%|███████▊  | 14/18 [01:27<00:02,  1.90it/s]
Inference Embeddings:  83%|████████▎ | 15/18 [01:27<00:01,  2.32it/s]
Inference Embeddings:  89%|████████▉ | 16/18 [01:27<00:00,  2.81it/s]
Inference Embeddings: 100%|██████████| 18/18 [01:27<00:00,  4.88s/it]

pre tokenize: 100%|██████████| 4/4 [00:00<00:00, 60.92it/s]

Inference Embeddings:   0%|          | 0/12 [00:00<?, ?it/s]
Inference Embeddings:   8%|▊         | 1/12 [01:19<14:37, 79.75s/it]
Inference Embeddings:  17%|█▋        | 2/12 [01:20<05:31, 33.14s/it]
Inference Embeddings:  25%|██▌       | 3/12 [01:20<02:43, 18.21s/it]
Inference Embeddings:  33%|███▎      | 4/12 [01:21<01:29, 11.19s/it]
Inference Embeddings:  42%|████▏     | 5/12 [01:21<00:50,  7.28s/it]
Inference Embeddings:  50%|█████     | 6/12 [01:21<00:29,  4.92s/it]
Inference Embeddings:  58%|█████▊    | 7/12 [01:22<00:17,  3.40s/it]
Inference Embeddings:  67%|██████▋   | 8/12 [01:22<00:09,  2.39s/it]
Inference Embeddings:  75%|███████▌  | 9/12 [01:22<00:05,  1.72s/it]
Inference Embeddings:  83%|████████▎ | 10/12 [01:22<00:02,  1.25s/it]
Inference Embeddings: 100%|██████████| 12/12 [01:23<00:00,  6.92s/it]

Inference Embeddings:   0%|          | 0/3 [00:00<?, ?it/s]
Inference Embeddings:  33%|███▎      | 1/3 [01:19<02:39, 79.94s/it]
Inference Embeddings:  67%|██████▋   | 2/3 [01:20<00:33, 33.23s/it]
Inference Embeddings: 100%|██████████| 3/3 [01:20<00:00, 26.86s/it]

pre tokenize:   0%|          | 0/9 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 9/9 [00:00<00:00, 45.71it/s]

Inference Embeddings:   0%|          | 0/28 [00:00<?, ?it/s]
Inference Embeddings:   4%|▎         | 1/28 [01:20<36:22, 80.82s/it]
Inference Embeddings:   7%|▋         | 2/28 [01:21<14:34, 33.65s/it]
Inference Embeddings:  11%|█         | 3/28 [01:22<07:43, 18.55s/it]
Inference Embeddings:  14%|█▍        | 4/28 [01:22<04:34, 11.43s/it]
Inference Embeddings:  18%|█▊        | 5/28 [01:23<02:52,  7.48s/it]
Inference Embeddings:  21%|██▏       | 6/28 [01:23<01:52,  5.09s/it]
Inference Embeddings:  25%|██▌       | 7/28 [01:23<01:14,  3.56s/it]
Inference Embeddings:  29%|██▊       | 8/28 [01:24<00:50,  2.53s/it]
Inference Embeddings:  32%|███▏      | 9/28 [01:24<00:35,  1.85s/it]
Inference Embeddings:  36%|███▌      | 10/28 [01:24<00:24,  1.39s/it]
Inference Embeddings:  39%|███▉      | 11/28 [01:25<00:18,  1.06s/it]
Inference Embeddings:  43%|████▎     | 12/28 [01:25<00:13,  1.20it/s]
Inference Embeddings:  46%|████▋     | 13/28 [01:25<00:09,  1.50it/s]
Inference Embeddings:  50%|█████     | 14/28 [01:26<00:07,  1.82it/s]
Inference Embeddings:  54%|█████▎    | 15/28 [01:26<00:05,  2.22it/s]
Inference Embeddings:  57%|█████▋    | 16/28 [01:26<00:04,  2.62it/s]
Inference Embeddings:  61%|██████    | 17/28 [01:26<00:03,  2.98it/s]
Inference Embeddings:  64%|██████▍   | 18/28 [01:27<00:03,  3.29it/s]
Inference Embeddings:  68%|██████▊   | 19/28 [01:27<00:02,  3.53it/s]
Inference Embeddings:  71%|███████▏  | 20/28 [01:27<00:02,  3.86it/s]
Inference Embeddings:  75%|███████▌  | 21/28 [01:27<00:01,  4.10it/s]
Inference Embeddings:  79%|███████▊  | 22/28 [01:27<00:01,  4.33it/s]
Inference Embeddings:  82%|████████▏ | 23/28 [01:28<00:01,  4.62it/s]
Inference Embeddings:  86%|████████▌ | 24/28 [01:28<00:00,  4.85it/s]
Inference Embeddings:  89%|████████▉ | 25/28 [01:28<00:00,  5.22it/s]
Inference Embeddings:  93%|█████████▎| 26/28 [01:28<00:00,  5.57it/s]
Inference Embeddings: 100%|██████████| 28/28 [01:28<00:00,  3.17s/it]

Inference Embeddings:   0%|          | 0/3 [00:00<?, ?it/s]
Inference Embeddings:  33%|███▎      | 1/3 [01:19<02:39, 79.85s/it]
Inference Embeddings: 100%|██████████| 3/3 [01:20<00:00, 26.72s/it]

pre tokenize: 100%|██████████| 3/3 [00:00<00:00, 100.63it/s]

Inference Embeddings:   0%|          | 0/3 [00:00<?, ?it/s]
Inference Embeddings:  33%|███▎      | 1/3 [00:04<00:09,  4.93s/it]
Inference Embeddings: 100%|██████████| 3/3 [00:05<00:00,  1.94s/it]

pre tokenize: 100%|██████████| 4/4 [00:00<00:00, 73.47it/s]

Inference Embeddings:   0%|          | 0/4 [00:00<?, ?it/s]
Inference Embeddings:  25%|██▌       | 1/4 [00:07<00:22,  7.48s/it]
Inference Embeddings:  50%|█████     | 2/4 [00:08<00:07,  3.76s/it]
Inference Embeddings:  75%|███████▌  | 3/4 [00:09<00:02,  2.45s/it]
Inference Embeddings: 100%|██████████| 4/4 [00:09<00:00,  2.43s/it]

pre tokenize: 100%|██████████| 2/2 [00:00<00:00, 80.10it/s]

Inference Embeddings:   0%|          | 0/2 [00:00<?, ?it/s]
Inference Embeddings:  50%|█████     | 1/2 [00:04<00:04,  4.50s/it]
Inference Embeddings: 100%|██████████| 2/2 [00:04<00:00,  2.42s/it]

pre tokenize: 100%|██████████| 2/2 [00:00<00:00, 66.92it/s]

Inference Embeddings:   0%|          | 0/2 [00:00<?, ?it/s]
Inference Embeddings: 100%|██████████| 2/2 [00:05<00:00,  2.57s/it]

Inference Embeddings:   0%|          | 0/3 [00:00<?, ?it/s]
Inference Embeddings:  33%|███▎      | 1/3 [01:21<02:42, 81.31s/it]
Inference Embeddings: 100%|██████████| 3/3 [01:21<00:00, 27.26s/it]

Inference Embeddings:   0%|          | 0/3 [00:00<?, ?it/s]
Inference Embeddings:  33%|███▎      | 1/3 [01:19<02:39, 79.56s/it]
Inference Embeddings: 100%|██████████| 3/3 [01:19<00:00, 26.62s/it]

pre tokenize: 100%|██████████| 5/5 [00:00<00:00, 67.44it/s]

Inference Embeddings:   0%|          | 0/5 [00:00<?, ?it/s]
Inference Embeddings:  20%|██        | 1/5 [00:07<00:29,  7.36s/it]
Inference Embeddings:  40%|████      | 2/5 [00:08<00:11,  3.89s/it]
Inference Embeddings:  60%|██████    | 3/5 [00:10<00:05,  2.65s/it]
Inference Embeddings:  80%|████████  | 4/5 [00:10<00:01,  1.98s/it]
Inference Embeddings: 100%|██████████| 5/5 [00:11<00:00,  2.26s/it]

pre tokenize:   0%|          | 0/8 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 8/8 [00:00<00:00, 59.31it/s]

Inference Embeddings:   0%|          | 0/8 [00:00<?, ?it/s]
Inference Embeddings:  12%|█▎        | 1/8 [00:14<01:41, 14.47s/it]
Inference Embeddings:  25%|██▌       | 2/8 [00:16<00:42,  7.10s/it]
Inference Embeddings:  38%|███▊      | 3/8 [00:18<00:22,  4.59s/it]
Inference Embeddings:  50%|█████     | 4/8 [00:19<00:12,  3.21s/it]
Inference Embeddings:  62%|██████▎   | 5/8 [00:19<00:06,  2.32s/it]
Inference Embeddings:  75%|███████▌  | 6/8 [00:20<00:03,  1.75s/it]
Inference Embeddings: 100%|██████████| 8/8 [00:20<00:00,  2.62s/it]

17914
5191
periti_2025
1

  0%|          | 0/37 [00:00<?, ?it/s]

pre tokenize: 100%|██████████| 2/2 [00:00<00:00, 104.93it/s]

Inference Embeddings:   0%|          | 0/2 [00:00<?, ?it/s]
Inference Embeddings:  50%|█████     | 1/2 [00:08<00:08,  8.05s/it]
Inference Embeddings: 100%|██████████| 2/2 [00:08<00:00,  4.17s/it]

pre tokenize: 100%|██████████| 4/4 [00:00<00:00, 71.92it/s]

Inference Embeddings:   0%|          | 0/4 [00:00<?, ?it/s]
Inference Embeddings:  25%|██▌       | 1/4 [00:06<00:18,  6.25s/it]
Inference Embeddings:  50%|█████     | 2/4 [00:07<00:06,  3.26s/it]
Inference Embeddings:  75%|███████▌  | 3/4 [00:08<00:02,  2.18s/it]
Inference Embeddings: 100%|██████████| 4/4 [00:08<00:00,  2.21s/it]

pre tokenize: 100%|██████████| 7/7 [00:00<00:00, 87.54it/s]

Inference Embeddings:   0%|          | 0/7 [00:00<?, ?it/s]
Inference Embeddings:  14%|█▍        | 1/7 [00:05<00:35,  5.90s/it]
Inference Embeddings:  29%|██▊       | 2/7 [00:07<00:16,  3.27s/it]
Inference Embeddings:  43%|████▎     | 3/7 [00:08<00:09,  2.32s/it]
Inference Embeddings:  57%|█████▋    | 4/7 [00:09<00:05,  1.80s/it]
Inference Embeddings:  71%|███████▏  | 5/7 [00:10<00:02,  1.47s/it]
Inference Embeddings:  86%|████████▌ | 6/7 [00:11<00:01,  1.20s/it]
Inference Embeddings: 100%|██████████| 7/7 [00:11<00:00,  1.60s/it]

pre tokenize: 100%|██████████| 7/7 [00:00<00:00, 75.25it/s]

Inference Embeddings:   0%|          | 0/7 [00:00<?, ?it/s]
Inference Embeddings:  14%|█▍        | 1/7 [00:08<00:49,  8.17s/it]
Inference Embeddings:  29%|██▊       | 2/7 [00:09<00:21,  4.31s/it]
Inference Embeddings:  43%|████▎     | 3/7 [00:11<00:11,  2.94s/it]
Inference Embeddings:  57%|█████▋    | 4/7 [00:12<00:06,  2.21s/it]
Inference Embeddings:  71%|███████▏  | 5/7 [00:13<00:03,  1.75s/it]
Inference Embeddings: 100%|██████████| 7/7 [00:14<00:00,  2.01s/it]

pre tokenize: 100%|██████████| 8/8 [00:00<00:00, 82.17it/s]

Inference Embeddings:   0%|          | 0/8 [00:00<?, ?it/s]
Inference Embeddings:  12%|█▎        | 1/8 [00:06<00:46,  6.68s/it]
Inference Embeddings:  25%|██▌       | 2/8 [00:08<00:21,  3.55s/it]
Inference Embeddings:  38%|███▊      | 3/8 [00:09<00:12,  2.42s/it]
Inference Embeddings:  50%|█████     | 4/8 [00:10<00:07,  1.84s/it]
Inference Embeddings:  62%|██████▎   | 5/8 [00:10<00:04,  1.49s/it]
Inference Embeddings:  75%|███████▌  | 6/8 [00:11<00:02,  1.23s/it]
Inference Embeddings: 100%|██████████| 8/8 [00:12<00:00,  1.54s/it]

pre tokenize: 100%|██████████| 4/4 [00:00<00:00, 55.90it/s]

Inference Embeddings:   0%|          | 0/4 [00:00<?, ?it/s]
Inference Embeddings:  25%|██▌       | 1/4 [00:08<00:25,  8.42s/it]
Inference Embeddings:  50%|█████     | 2/4 [00:10<00:08,  4.44s/it]
Inference Embeddings:  75%|███████▌  | 3/4 [00:11<00:03,  3.04s/it]
Inference Embeddings: 100%|██████████| 4/4 [00:12<00:00,  3.08s/it]

pre tokenize: 100%|██████████| 5/5 [00:00<00:00, 64.79it/s]

Inference Embeddings:   0%|          | 0/5 [00:00<?, ?it/s]
Inference Embeddings:  20%|██        | 1/5 [00:06<00:26,  6.62s/it]
Inference Embeddings:  40%|████      | 2/5 [00:07<00:10,  3.46s/it]
Inference Embeddings:  60%|██████    | 3/5 [00:09<00:04,  2.40s/it]
Inference Embeddings:  80%|████████  | 4/5 [00:09<00:01,  1.80s/it]
Inference Embeddings: 100%|██████████| 5/5 [00:10<00:00,  2.09s/it]

11336
3244
2

  0%|          | 0/37 [00:00<?, ?it/s]

pre tokenize: 100%|██████████| 2/2 [00:00<00:00, 80.81it/s]

Inference Embeddings:   0%|          | 0/2 [00:00<?, ?it/s]
Inference Embeddings:  50%|█████     | 1/2 [00:06<00:06,  6.64s/it]
Inference Embeddings: 100%|██████████| 2/2 [00:06<00:00,  3.48s/it]

pre tokenize: 100%|██████████| 4/4 [00:00<00:00, 88.16it/s]

Inference Embeddings:   0%|          | 0/4 [00:00<?, ?it/s]
Inference Embeddings:  25%|██▌       | 1/4 [00:07<00:21,  7.27s/it]
Inference Embeddings:  50%|█████     | 2/4 [00:08<00:07,  3.68s/it]
Inference Embeddings: 100%|██████████| 4/4 [00:09<00:00,  2.34s/it]

pre tokenize: 100%|██████████| 3/3 [00:00<00:00, 46.26it/s]

Inference Embeddings:   0%|          | 0/3 [00:00<?, ?it/s]
Inference Embeddings:  33%|███▎      | 1/3 [00:12<00:25, 12.56s/it]
Inference Embeddings:  67%|██████▋   | 2/3 [00:13<00:05,  5.75s/it]
Inference Embeddings: 100%|██████████| 3/3 [00:13<00:00,  4.55s/it]

pre tokenize: 100%|██████████| 2/2 [00:00<00:00, 57.56it/s]

Inference Embeddings:   0%|          | 0/2 [00:00<?, ?it/s]
Inference Embeddings:  50%|█████     | 1/2 [00:05<00:05,  5.02s/it]
Inference Embeddings: 100%|██████████| 2/2 [00:05<00:00,  2.69s/it]

pre tokenize: 100%|██████████| 2/2 [00:00<00:00, 91.61it/s]

Inference Embeddings:   0%|          | 0/2 [00:00<?, ?it/s]
Inference Embeddings:  50%|█████     | 1/2 [00:06<00:06,  6.05s/it]
Inference Embeddings: 100%|██████████| 2/2 [00:06<00:00,  3.24s/it]

pre tokenize: 100%|██████████| 5/5 [00:00<00:00, 90.25it/s]

Inference Embeddings:   0%|          | 0/5 [00:00<?, ?it/s]
Inference Embeddings:  20%|██        | 1/5 [00:05<00:23,  5.80s/it]
Inference Embeddings:  40%|████      | 2/5 [00:07<00:09,  3.12s/it]
Inference Embeddings:  60%|██████    | 3/5 [00:08<00:04,  2.14s/it]
Inference Embeddings:  80%|████████  | 4/5 [00:08<00:01,  1.59s/it]
Inference Embeddings: 100%|██████████| 5/5 [00:08<00:00,  1.78s/it]

pre tokenize: 100%|██████████| 2/2 [00:00<00:00, 67.63it/s]

Inference Embeddings:   0%|          | 0/2 [00:00<?, ?it/s]
Inference Embeddings:  50%|█████     | 1/2 [00:08<00:08,  8.88s/it]
Inference Embeddings: 100%|██████████| 2/2 [00:09<00:00,  4.61s/it]

pre tokenize:   0%|          | 0/6 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 6/6 [00:00<00:00, 39.13it/s]

Inference Embeddings:   0%|          | 0/6 [00:00<?, ?it/s]
Inference Embeddings:  17%|█▋        | 1/6 [00:06<00:30,  6.01s/it]
Inference Embeddings:  33%|███▎      | 2/6 [00:07<00:13,  3.29s/it]
Inference Embeddings:  50%|█████     | 3/6 [00:08<00:06,  2.29s/it]
Inference Embeddings:  67%|██████▋   | 4/6 [00:09<00:03,  1.73s/it]
Inference Embeddings:  83%|████████▎ | 5/6 [00:10<00:01,  1.38s/it]
Inference Embeddings: 100%|██████████| 6/6 [00:10<00:00,  1.72s/it]

pre tokenize: 100%|██████████| 4/4 [00:00<00:00, 41.23it/s]

Inference Embeddings:   0%|          | 0/4 [00:00<?, ?it/s]
Inference Embeddings:  25%|██▌       | 1/4 [00:07<00:21,  7.18s/it]
Inference Embeddings:  50%|█████     | 2/4 [00:08<00:07,  3.76s/it]
Inference Embeddings:  75%|███████▌  | 3/4 [00:09<00:02,  2.54s/it]
Inference Embeddings: 100%|██████████| 4/4 [00:10<00:00,  2.59s/it]

pre tokenize: 100%|██████████| 6/6 [00:00<00:00, 80.05it/s]

Inference Embeddings:   0%|          | 0/6 [00:00<?, ?it/s]
Inference Embeddings:  17%|█▋        | 1/6 [00:05<00:27,  5.50s/it]
Inference Embeddings:  33%|███▎      | 2/6 [00:06<00:11,  2.96s/it]
Inference Embeddings:  50%|█████     | 3/6 [00:07<00:06,  2.05s/it]
Inference Embeddings:  67%|██████▋   | 4/6 [00:08<00:03,  1.59s/it]
Inference Embeddings: 100%|██████████| 6/6 [00:09<00:00,  1.55s/it]

pre tokenize: 100%|██████████| 2/2 [00:00<00:00, 59.27it/s]

Inference Embeddings:   0%|          | 0/2 [00:00<?, ?it/s]
Inference Embeddings:  50%|█████     | 1/2 [00:07<00:07,  7.74s/it]
Inference Embeddings: 100%|██████████| 2/2 [00:08<00:00,  4.35s/it]

pre tokenize: 100%|██████████| 2/2 [00:00<00:00, 76.34it/s]

Inference Embeddings:   0%|          | 0/2 [00:00<?, ?it/s]
Inference Embeddings:  50%|█████     | 1/2 [00:06<00:06,  6.17s/it]
Inference Embeddings: 100%|██████████| 2/2 [00:06<00:00,  3.36s/it]

pre tokenize: 100%|██████████| 3/3 [00:00<00:00, 53.78it/s]

Inference Embeddings:   0%|          | 0/3 [00:00<?, ?it/s]
Inference Embeddings:  33%|███▎      | 1/3 [00:07<00:14,  7.34s/it]
Inference Embeddings: 100%|██████████| 3/3 [00:08<00:00,  2.79s/it]

pre tokenize: 100%|██████████| 2/2 [00:00<00:00, 60.48it/s]

Inference Embeddings:   0%|          | 0/2 [00:00<?, ?it/s]
Inference Embeddings:  50%|█████     | 1/2 [00:14<00:14, 14.17s/it]
Inference Embeddings: 100%|██████████| 2/2 [00:14<00:00,  7.25s/it]

pre tokenize: 100%|██████████| 3/3 [00:00<00:00, 57.21it/s]

Inference Embeddings:   0%|          | 0/3 [00:00<?, ?it/s]
Inference Embeddings:  33%|███▎      | 1/3 [00:06<00:12,  6.46s/it]
Inference Embeddings:  67%|██████▋   | 2/3 [00:07<00:03,  3.53s/it]
Inference Embeddings: 100%|██████████| 3/3 [00:08<00:00,  2.89s/it]

pre tokenize: 100%|██████████| 4/4 [00:00<00:00, 63.25it/s]

Inference Embeddings:   0%|          | 0/4 [00:00<?, ?it/s]
Inference Embeddings:  25%|██▌       | 1/4 [00:07<00:23,  7.79s/it]
Inference Embeddings:  50%|█████     | 2/4 [00:09<00:08,  4.02s/it]
Inference Embeddings:  75%|███████▌  | 3/4 [00:10<00:02,  2.70s/it]
Inference Embeddings: 100%|██████████| 4/4 [00:11<00:00,  2.75s/it]

12988
4389

In [ ]:
for method in ("greedy", "periti_2024", "periti_2025"):
    print(method)
    new_dir = os.path.join(eng_path, f"{method}-clustered/")
    os.makedirs(new_dir, exist_ok=True)

    data1, data2 = cluster(method, eng_path)
    data1["2"] = data1["labels"]
    data1 = data1[["0", "1", "2"]]
    data1.to_csv(f"{new_dir}english-corpus1.tsv.gz", sep='\t', index=False, compression="gzip")

    data2["2"] = data2["labels"]
    data2 = data2[["0", "1", "2"]]
    data2.to_csv(f"{new_dir}english-corpus2.tsv.gz", sep='\t', index=False, compression="gzip")

greedy
      0                                                  1  \
0  part  Most of the asp * ing men of that part of Alab...
1  face  The faces are umajured , except that the color...
2   tip  The moon was in its western field , white and ...
3  tree  The well known fact that we may have a hundred...
4  face  Rising upon the instant in his stirrups , the ...

                                                   2
0              A portion ; some portion ; a section.
1                   The front surface of a painting.
2                  To cover the top of ; to overlay.
3  A plant that bears a given fruit or seed ; spe...
4  The front of the skull, especially the front o...

  0%|          | 0/37 [00:00<?, ?it/s]

pre tokenize: 100%|██████████| 4/4 [00:00<00:00, 107.02it/s]

Inference Embeddings:   0%|          | 0/4 [00:00<?, ?it/s]
Inference Embeddings:  25%|██▌       | 1/4 [00:03<00:09,  3.06s/it]
Inference Embeddings:  50%|█████     | 2/4 [00:03<00:03,  1.72s/it]
Inference Embeddings:  75%|███████▌  | 3/4 [00:04<00:01,  1.23s/it]
Inference Embeddings: 100%|██████████| 4/4 [00:04<00:00,  1.16s/it]

pre tokenize: 100%|██████████| 4/4 [00:00<00:00, 95.81it/s]

Inference Embeddings:   0%|          | 0/4 [00:00<?, ?it/s]
Inference Embeddings:  25%|██▌       | 1/4 [00:03<00:10,  3.62s/it]
Inference Embeddings:  50%|█████     | 2/4 [00:04<00:04,  2.01s/it]
Inference Embeddings:  75%|███████▌  | 3/4 [00:05<00:01,  1.41s/it]
Inference Embeddings: 100%|██████████| 4/4 [00:05<00:00,  1.35s/it]

pre tokenize:   0%|          | 0/4 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 4/4 [00:00<00:00, 23.14it/s]

Inference Embeddings:   0%|          | 0/4 [00:00<?, ?it/s]
Inference Embeddings:  25%|██▌       | 1/4 [00:03<00:10,  3.63s/it]
Inference Embeddings:  50%|█████     | 2/4 [00:04<00:03,  1.98s/it]
Inference Embeddings:  75%|███████▌  | 3/4 [00:05<00:01,  1.38s/it]
Inference Embeddings: 100%|██████████| 4/4 [00:05<00:00,  1.37s/it]

pre tokenize: 100%|██████████| 3/3 [00:00<00:00, 131.07it/s]

Inference Embeddings:   0%|          | 0/3 [00:00<?, ?it/s]
Inference Embeddings:  33%|███▎      | 1/3 [00:03<00:07,  3.65s/it]
Inference Embeddings:  67%|██████▋   | 2/3 [00:04<00:01,  1.81s/it]
Inference Embeddings: 100%|██████████| 3/3 [00:04<00:00,  1.45s/it]

pre tokenize: 100%|██████████| 2/2 [00:00<00:00, 91.82it/s]

Inference Embeddings:   0%|          | 0/2 [00:00<?, ?it/s]
Inference Embeddings:  50%|█████     | 1/2 [00:02<00:02,  2.14s/it]
Inference Embeddings: 100%|██████████| 2/2 [00:02<00:00,  1.13s/it]

pre tokenize: 100%|██████████| 4/4 [00:00<00:00, 96.48it/s]

Inference Embeddings:   0%|          | 0/4 [00:00<?, ?it/s]
Inference Embeddings:  25%|██▌       | 1/4 [00:03<00:09,  3.12s/it]
Inference Embeddings:  50%|█████     | 2/4 [00:03<00:03,  1.78s/it]
Inference Embeddings:  75%|███████▌  | 3/4 [00:04<00:01,  1.26s/it]
Inference Embeddings: 100%|██████████| 4/4 [00:05<00:00,  1.29s/it]

pre tokenize:   0%|          | 0/9 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 9/9 [00:00<00:00, 45.69it/s]

Inference Embeddings:   0%|          | 0/9 [00:00<?, ?it/s]
Inference Embeddings:  11%|█         | 1/9 [00:03<00:28,  3.62s/it]
Inference Embeddings:  22%|██▏       | 2/9 [00:04<00:15,  2.27s/it]
Inference Embeddings:  33%|███▎      | 3/9 [00:06<00:10,  1.72s/it]
Inference Embeddings:  44%|████▍     | 4/9 [00:06<00:07,  1.41s/it]
Inference Embeddings:  56%|█████▌    | 5/9 [00:07<00:04,  1.21s/it]
Inference Embeddings:  67%|██████▋   | 6/9 [00:08<00:03,  1.05s/it]
Inference Embeddings:  78%|███████▊  | 7/9 [00:09<00:01,  1.09it/s]
Inference Embeddings:  89%|████████▉ | 8/9 [00:09<00:00,  1.25it/s]
Inference Embeddings: 100%|██████████| 9/9 [00:10<00:00,  1.13s/it]

pre tokenize: 100%|██████████| 2/2 [00:00<00:00, 45.44it/s]

Inference Embeddings:   0%|          | 0/2 [00:00<?, ?it/s]
Inference Embeddings:  50%|█████     | 1/2 [00:04<00:04,  4.24s/it]
Inference Embeddings: 100%|██████████| 2/2 [00:04<00:00,  2.34s/it]

pre tokenize: 100%|██████████| 3/3 [00:00<00:00, 69.70it/s]

Inference Embeddings:   0%|          | 0/3 [00:00<?, ?it/s]
Inference Embeddings:  33%|███▎      | 1/3 [00:04<00:09,  4.51s/it]
Inference Embeddings:  67%|██████▋   | 2/3 [00:05<00:02,  2.55s/it]
Inference Embeddings: 100%|██████████| 3/3 [00:06<00:00,  2.18s/it]

pre tokenize:   0%|          | 0/20 [00:00<?, ?it/s]
pre tokenize:  25%|██▌       | 5/20 [00:00<00:00, 43.79it/s]
pre tokenize:  50%|█████     | 10/20 [00:00<00:00, 41.45it/s]
pre tokenize: 100%|██████████| 20/20 [00:00<00:00, 50.78it/s]

Inference Embeddings:   0%|          | 0/20 [00:00<?, ?it/s]
Inference Embeddings:   5%|▌         | 1/20 [00:04<01:28,  4.66s/it]
Inference Embeddings:  10%|█         | 2/20 [00:06<00:55,  3.06s/it]
Inference Embeddings:  15%|█▌        | 3/20 [00:08<00:39,  2.35s/it]
Inference Embeddings:  20%|██        | 4/20 [00:09<00:31,  1.96s/it]
Inference Embeddings:  25%|██▌       | 5/20 [00:10<00:25,  1.71s/it]
Inference Embeddings:  30%|███       | 6/20 [00:11<00:21,  1.54s/it]
Inference Embeddings:  35%|███▌      | 7/20 [00:13<00:18,  1.41s/it]
Inference Embeddings:  40%|████      | 8/20 [00:14<00:15,  1.32s/it]
Inference Embeddings:  45%|████▌     | 9/20 [00:15<00:13,  1.27s/it]
Inference Embeddings:  50%|█████     | 10/20 [00:16<00:11,  1.18s/it]
Inference Embeddings:  55%|█████▌    | 11/20 [00:17<00:09,  1.10s/it]
Inference Embeddings:  60%|██████    | 12/20 [00:18<00:08,  1.04s/it]
Inference Embeddings:  65%|██████▌   | 13/20 [00:19<00:07,  1.01s/it]
Inference Embeddings:  70%|███████   | 14/20 [00:19<00:05,  1.07it/s]
Inference Embeddings:  75%|███████▌  | 15/20 [00:20<00:04,  1.16it/s]
Inference Embeddings:  80%|████████  | 16/20 [00:21<00:03,  1.20it/s]
Inference Embeddings:  85%|████████▌ | 17/20 [00:21<00:02,  1.33it/s]
Inference Embeddings:  90%|█████████ | 18/20 [00:22<00:01,  1.47it/s]
Inference Embeddings:  95%|█████████▌| 19/20 [00:22<00:00,  1.63it/s]
Inference Embeddings: 100%|██████████| 20/20 [00:23<00:00,  1.15s/it]

pre tokenize:   0%|          | 0/11 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 11/11 [00:00<00:00, 81.16it/s]

Inference Embeddings:   0%|          | 0/11 [00:00<?, ?it/s]
Inference Embeddings:   9%|▉         | 1/11 [00:03<00:37,  3.71s/it]
Inference Embeddings:  18%|█▊        | 2/11 [00:05<00:21,  2.38s/it]
Inference Embeddings:  27%|██▋       | 3/11 [00:06<00:14,  1.86s/it]
Inference Embeddings:  36%|███▋      | 4/11 [00:07<00:10,  1.55s/it]
Inference Embeddings:  45%|████▌     | 5/11 [00:08<00:08,  1.34s/it]
Inference Embeddings:  55%|█████▍    | 6/11 [00:09<00:05,  1.19s/it]
Inference Embeddings:  64%|██████▎   | 7/11 [00:10<00:04,  1.09s/it]
Inference Embeddings:  73%|███████▎  | 8/11 [00:10<00:02,  1.03it/s]
Inference Embeddings:  82%|████████▏ | 9/11 [00:11<00:01,  1.11it/s]
Inference Embeddings: 100%|██████████| 11/11 [00:12<00:00,  1.11s/it]

pre tokenize: 100%|██████████| 2/2 [00:00<00:00, 130.53it/s]

Inference Embeddings:   0%|          | 0/2 [00:00<?, ?it/s]
Inference Embeddings: 100%|██████████| 2/2 [00:03<00:00,  1.96s/it]

pre tokenize: 100%|██████████| 2/2 [00:00<00:00, 117.53it/s]

Inference Embeddings:   0%|          | 0/2 [00:00<?, ?it/s]
Inference Embeddings: 100%|██████████| 2/2 [00:04<00:00,  2.14s/it]

pre tokenize: 100%|██████████| 10/10 [00:00<00:00, 111.07it/s]

Inference Embeddings:   0%|          | 0/10 [00:00<?, ?it/s]
Inference Embeddings:  10%|█         | 1/10 [00:03<00:34,  3.82s/it]
Inference Embeddings:  20%|██        | 2/10 [00:04<00:16,  2.12s/it]
Inference Embeddings:  30%|███       | 3/10 [00:05<00:10,  1.47s/it]
Inference Embeddings:  40%|████      | 4/10 [00:06<00:07,  1.19s/it]
Inference Embeddings:  50%|█████     | 5/10 [00:06<00:04,  1.04it/s]
Inference Embeddings:  60%|██████    | 6/10 [00:07<00:03,  1.23it/s]
Inference Embeddings:  70%|███████   | 7/10 [00:07<00:02,  1.43it/s]
Inference Embeddings:  80%|████████  | 8/10 [00:08<00:01,  1.60it/s]
Inference Embeddings:  90%|█████████ | 9/10 [00:08<00:00,  1.78it/s]
Inference Embeddings: 100%|██████████| 10/10 [00:08<00:00,  1.11it/s]

pre tokenize: 100%|██████████| 2/2 [00:00<00:00, 101.32it/s]

Inference Embeddings:   0%|          | 0/2 [00:00<?, ?it/s]
Inference Embeddings:  50%|█████     | 1/2 [00:04<00:04,  4.08s/it]
Inference Embeddings: 100%|██████████| 2/2 [00:04<00:00,  2.22s/it]

pre tokenize: 100%|██████████| 2/2 [00:00<00:00, 120.00it/s]

Inference Embeddings:   0%|          | 0/2 [00:00<?, ?it/s]
Inference Embeddings:  50%|█████     | 1/2 [00:03<00:03,  3.06s/it]
Inference Embeddings: 100%|██████████| 2/2 [00:03<00:00,  1.61s/it]

pre tokenize: 100%|██████████| 2/2 [00:00<00:00, 74.19it/s]

Inference Embeddings:   0%|          | 0/2 [00:00<?, ?it/s]
Inference Embeddings:  50%|█████     | 1/2 [00:03<00:03,  3.60s/it]
Inference Embeddings: 100%|██████████| 2/2 [00:03<00:00,  1.90s/it]

pre tokenize: 100%|██████████| 6/6 [00:00<00:00, 69.08it/s]

Inference Embeddings:   0%|          | 0/6 [00:00<?, ?it/s]
Inference Embeddings:  17%|█▋        | 1/6 [00:04<00:20,  4.10s/it]
Inference Embeddings:  33%|███▎      | 2/6 [00:05<00:09,  2.35s/it]
Inference Embeddings:  50%|█████     | 3/6 [00:06<00:05,  1.68s/it]
Inference Embeddings:  67%|██████▋   | 4/6 [00:06<00:02,  1.30s/it]
Inference Embeddings:  83%|████████▎ | 5/6 [00:07<00:01,  1.06s/it]
Inference Embeddings: 100%|██████████| 6/6 [00:07<00:00,  1.28s/it]

pre tokenize: 100%|██████████| 2/2 [00:00<00:00, 72.20it/s]

Inference Embeddings:   0%|          | 0/2 [00:00<?, ?it/s]
Inference Embeddings:  50%|█████     | 1/2 [00:03<00:03,  3.84s/it]
Inference Embeddings: 100%|██████████| 2/2 [00:04<00:00,  2.21s/it]

pre tokenize: 100%|██████████| 3/3 [00:00<00:00, 86.23it/s]

Inference Embeddings:   0%|          | 0/3 [00:00<?, ?it/s]
Inference Embeddings:  33%|███▎      | 1/3 [00:03<00:06,  3.23s/it]
Inference Embeddings: 100%|██████████| 3/3 [00:04<00:00,  1.40s/it]

pre tokenize: 100%|██████████| 2/2 [00:00<00:00, 104.06it/s]

Inference Embeddings:   0%|          | 0/2 [00:00<?, ?it/s]
Inference Embeddings:  50%|█████     | 1/2 [00:03<00:03,  3.23s/it]
Inference Embeddings: 100%|██████████| 2/2 [00:03<00:00,  1.72s/it]

pre tokenize: 100%|██████████| 2/2 [00:00<00:00, 65.46it/s]

Inference Embeddings:   0%|          | 0/2 [00:00<?, ?it/s]
Inference Embeddings:  50%|█████     | 1/2 [00:03<00:03,  3.20s/it]
Inference Embeddings: 100%|██████████| 2/2 [00:03<00:00,  1.66s/it]

pre tokenize:   0%|          | 0/14 [00:00<?, ?it/s]
pre tokenize:  43%|████▎     | 6/14 [00:00<00:00, 59.78it/s]
pre tokenize: 100%|██████████| 14/14 [00:00<00:00, 55.87it/s]

Inference Embeddings:   0%|          | 0/14 [00:00<?, ?it/s]
Inference Embeddings:   7%|▋         | 1/14 [00:04<00:57,  4.44s/it]
Inference Embeddings:  14%|█▍        | 2/14 [00:06<00:33,  2.79s/it]
Inference Embeddings:  21%|██▏       | 3/14 [00:07<00:24,  2.21s/it]
Inference Embeddings:  29%|██▊       | 4/14 [00:09<00:19,  1.92s/it]
Inference Embeddings:  36%|███▌      | 5/14 [00:10<00:15,  1.74s/it]
Inference Embeddings:  43%|████▎     | 6/14 [00:11<00:12,  1.59s/it]
Inference Embeddings:  50%|█████     | 7/14 [00:13<00:10,  1.52s/it]
Inference Embeddings:  57%|█████▋    | 8/14 [00:14<00:08,  1.41s/it]
Inference Embeddings:  64%|██████▍   | 9/14 [00:15<00:06,  1.31s/it]
Inference Embeddings:  71%|███████▏  | 10/14 [00:16<00:05,  1.25s/it]
Inference Embeddings:  79%|███████▊  | 11/14 [00:17<00:03,  1.16s/it]
Inference Embeddings:  86%|████████▌ | 12/14 [00:18<00:02,  1.07s/it]
Inference Embeddings:  93%|█████████▎| 13/14 [00:19<00:00,  1.02it/s]
Inference Embeddings: 100%|██████████| 14/14 [00:19<00:00,  1.38s/it]

pre tokenize:   0%|          | 0/19 [00:00<?, ?it/s]
pre tokenize:  42%|████▏     | 8/19 [00:00<00:00, 76.84it/s]
pre tokenize: 100%|██████████| 19/19 [00:00<00:00, 75.63it/s]

Inference Embeddings:   0%|          | 0/19 [00:00<?, ?it/s]
Inference Embeddings:   5%|▌         | 1/19 [00:04<01:18,  4.38s/it]
Inference Embeddings:  11%|█         | 2/19 [00:05<00:46,  2.74s/it]
Inference Embeddings:  16%|█▌        | 3/19 [00:07<00:33,  2.12s/it]
Inference Embeddings:  21%|██        | 4/19 [00:08<00:26,  1.74s/it]
Inference Embeddings:  26%|██▋       | 5/19 [00:09<00:21,  1.50s/it]
Inference Embeddings:  32%|███▏      | 6/19 [00:10<00:17,  1.38s/it]
Inference Embeddings:  37%|███▋      | 7/19 [00:11<00:14,  1.24s/it]
Inference Embeddings:  42%|████▏     | 8/19 [00:12<00:12,  1.13s/it]
Inference Embeddings:  47%|████▋     | 9/19 [00:13<00:10,  1.05s/it]
Inference Embeddings:  53%|█████▎    | 10/19 [00:14<00:09,  1.01s/it]
Inference Embeddings:  58%|█████▊    | 11/19 [00:15<00:07,  1.07it/s]
Inference Embeddings:  63%|██████▎   | 12/19 [00:15<00:06,  1.14it/s]
Inference Embeddings:  68%|██████▊   | 13/19 [00:16<00:04,  1.23it/s]
Inference Embeddings:  74%|███████▎  | 14/19 [00:17<00:03,  1.25it/s]
Inference Embeddings:  79%|███████▉  | 15/19 [00:17<00:03,  1.32it/s]
Inference Embeddings:  84%|████████▍ | 16/19 [00:18<00:02,  1.44it/s]
Inference Embeddings:  89%|████████▉ | 17/19 [00:19<00:01,  1.56it/s]
Inference Embeddings: 100%|██████████| 19/19 [00:19<00:00,  1.03s/it]

33065
7119
periti_2024
      0                                                  1  \
0  head  seen a complex and exquisitely balanced polity...
1  head  inculcated doctrines incompatible with the pla...
2  word  , during all this period , once entering those...
3  part  immaturity , and want of experience -- besides...
4  word  immaturity , and want of experience -- besides...

                                                   2
0            A superior or governing body or member.
1  The top of the head of a person, or the upper ...
2  A unit of language that native speakers can id...
3                             A fraction of a whole.
4  A single distinct conceptual unit of language,...

  0%|          | 0/37 [00:00<?, ?it/s]

pre tokenize: 100%|██████████| 4/4 [00:00<00:00, 73.00it/s]

Inference Embeddings:   0%|          | 0/12 [00:00<?, ?it/s]
Inference Embeddings:   8%|▊         | 1/12 [01:20<14:42, 80.23s/it]
Inference Embeddings:  17%|█▋        | 2/12 [01:20<05:33, 33.31s/it]
Inference Embeddings:  25%|██▌       | 3/12 [01:21<02:44, 18.28s/it]
Inference Embeddings:  33%|███▎      | 4/12 [01:21<01:29, 11.20s/it]
Inference Embeddings:  42%|████▏     | 5/12 [01:21<00:50,  7.27s/it]
Inference Embeddings:  50%|█████     | 6/12 [01:22<00:29,  4.89s/it]
Inference Embeddings:  58%|█████▊    | 7/12 [01:22<00:16,  3.38s/it]
Inference Embeddings:  67%|██████▋   | 8/12 [01:22<00:09,  2.38s/it]
Inference Embeddings:  75%|███████▌  | 9/12 [01:22<00:05,  1.71s/it]
Inference Embeddings:  83%|████████▎ | 10/12 [01:22<00:02,  1.24s/it]
Inference Embeddings: 100%|██████████| 12/12 [01:23<00:00,  6.93s/it]

pre tokenize: 100%|██████████| 4/4 [00:00<00:00, 71.91it/s]

Inference Embeddings:   0%|          | 0/4 [00:00<?, ?it/s]
Inference Embeddings:  25%|██▌       | 1/4 [00:08<00:24,  8.27s/it]
Inference Embeddings:  50%|█████     | 2/4 [00:09<00:08,  4.22s/it]
Inference Embeddings:  75%|███████▌  | 3/4 [00:10<00:02,  2.73s/it]
Inference Embeddings: 100%|██████████| 4/4 [00:10<00:00,  2.72s/it]

pre tokenize: 100%|██████████| 4/4 [00:00<00:00, 53.92it/s]

Inference Embeddings:   0%|          | 0/4 [00:00<?, ?it/s]
Inference Embeddings:  25%|██▌       | 1/4 [00:07<00:21,  7.13s/it]
Inference Embeddings:  50%|█████     | 2/4 [00:08<00:07,  3.59s/it]
Inference Embeddings:  75%|███████▌  | 3/4 [00:08<00:02,  2.25s/it]
Inference Embeddings: 100%|██████████| 4/4 [00:09<00:00,  2.28s/it]

pre tokenize:   0%|          | 0/4 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 4/4 [00:00<00:00, 24.88it/s]

Inference Embeddings:   0%|          | 0/10 [00:00<?, ?it/s]
Inference Embeddings:  10%|█         | 1/10 [01:21<12:12, 81.39s/it]
Inference Embeddings:  20%|██        | 2/10 [01:21<04:30, 33.85s/it]
Inference Embeddings:  30%|███       | 3/10 [01:22<02:10, 18.61s/it]
Inference Embeddings:  40%|████      | 4/10 [01:22<01:08, 11.44s/it]
Inference Embeddings:  50%|█████     | 5/10 [01:23<00:37,  7.43s/it]
Inference Embeddings:  60%|██████    | 6/10 [01:23<00:20,  5.01s/it]
Inference Embeddings:  70%|███████   | 7/10 [01:23<00:10,  3.45s/it]
Inference Embeddings:  80%|████████  | 8/10 [01:23<00:04,  2.42s/it]
Inference Embeddings:  90%|█████████ | 9/10 [01:24<00:01,  1.72s/it]
Inference Embeddings: 100%|██████████| 10/10 [01:24<00:00,  8.42s/it]

pre tokenize: 100%|██████████| 2/2 [00:00<00:00, 83.14it/s]

Inference Embeddings:   0%|          | 0/2 [00:00<?, ?it/s]
Inference Embeddings:  50%|█████     | 1/2 [00:05<00:05,  5.10s/it]
Inference Embeddings: 100%|██████████| 2/2 [00:05<00:00,  2.76s/it]

Inference Embeddings:   0%|          | 0/3 [00:00<?, ?it/s]
Inference Embeddings:  33%|███▎      | 1/3 [01:19<02:38, 79.44s/it]
Inference Embeddings: 100%|██████████| 3/3 [01:19<00:00, 26.61s/it]

pre tokenize: 100%|██████████| 4/4 [00:00<00:00, 92.95it/s]

Inference Embeddings:   0%|          | 0/4 [00:00<?, ?it/s]
Inference Embeddings:  25%|██▌       | 1/4 [00:04<00:12,  4.33s/it]
Inference Embeddings:  50%|█████     | 2/4 [00:05<00:04,  2.34s/it]
Inference Embeddings:  75%|███████▌  | 3/4 [00:05<00:01,  1.58s/it]
Inference Embeddings: 100%|██████████| 4/4 [00:06<00:00,  1.56s/it]

pre tokenize:   0%|          | 0/12 [00:00<?, ?it/s]
pre tokenize:  50%|█████     | 6/12 [00:00<00:00, 51.28it/s]
pre tokenize: 100%|██████████| 12/12 [00:00<00:00, 43.48it/s]

Inference Embeddings:   0%|          | 0/36 [00:00<?, ?it/s]
Inference Embeddings:   3%|▎         | 1/36 [01:20<47:12, 80.92s/it]
Inference Embeddings:   6%|▌         | 2/36 [01:21<19:10, 33.83s/it]
Inference Embeddings:   8%|▊         | 3/36 [01:22<10:20, 18.80s/it]
Inference Embeddings:  11%|█         | 4/36 [01:23<06:14, 11.71s/it]
Inference Embeddings:  14%|█▍        | 5/36 [01:24<04:00,  7.76s/it]
Inference Embeddings:  17%|█▋        | 6/36 [01:24<02:40,  5.34s/it]
Inference Embeddings:  19%|█▉        | 7/36 [01:25<01:51,  3.83s/it]
Inference Embeddings:  22%|██▏       | 8/36 [01:26<01:18,  2.81s/it]
Inference Embeddings:  25%|██▌       | 9/36 [01:26<00:56,  2.10s/it]
Inference Embeddings:  28%|██▊       | 10/36 [01:27<00:42,  1.63s/it]
Inference Embeddings:  31%|███       | 11/36 [01:27<00:32,  1.28s/it]
Inference Embeddings:  33%|███▎      | 12/36 [01:28<00:25,  1.05s/it]
Inference Embeddings:  36%|███▌      | 13/36 [01:28<00:19,  1.15it/s]
Inference Embeddings:  39%|███▉      | 14/36 [01:29<00:16,  1.33it/s]
Inference Embeddings:  42%|████▏     | 15/36 [01:29<00:14,  1.49it/s]
Inference Embeddings:  44%|████▍     | 16/36 [01:30<00:12,  1.66it/s]
Inference Embeddings:  47%|████▋     | 17/36 [01:30<00:10,  1.80it/s]
Inference Embeddings:  50%|█████     | 18/36 [01:31<00:09,  1.96it/s]
Inference Embeddings:  53%|█████▎    | 19/36 [01:31<00:08,  2.08it/s]
Inference Embeddings:  56%|█████▌    | 20/36 [01:31<00:07,  2.16it/s]
Inference Embeddings:  58%|█████▊    | 21/36 [01:32<00:06,  2.37it/s]
Inference Embeddings:  61%|██████    | 22/36 [01:32<00:05,  2.48it/s]
Inference Embeddings:  64%|██████▍   | 23/36 [01:33<00:05,  2.56it/s]
Inference Embeddings:  67%|██████▋   | 24/36 [01:33<00:04,  2.66it/s]
Inference Embeddings:  69%|██████▉   | 25/36 [01:33<00:03,  2.77it/s]
Inference Embeddings:  72%|███████▏  | 26/36 [01:34<00:03,  2.88it/s]
Inference Embeddings:  75%|███████▌  | 27/36 [01:34<00:02,  3.07it/s]
Inference Embeddings:  78%|███████▊  | 28/36 [01:34<00:02,  3.18it/s]
Inference Embeddings:  81%|████████  | 29/36 [01:34<00:02,  3.46it/s]
Inference Embeddings:  83%|████████▎ | 30/36 [01:35<00:01,  3.68it/s]
Inference Embeddings:  86%|████████▌ | 31/36 [01:35<00:01,  3.85it/s]
Inference Embeddings:  89%|████████▉ | 32/36 [01:35<00:00,  4.10it/s]
Inference Embeddings:  92%|█████████▏| 33/36 [01:35<00:00,  4.44it/s]
Inference Embeddings:  94%|█████████▍| 34/36 [01:35<00:00,  4.87it/s]
Inference Embeddings: 100%|██████████| 36/36 [01:35<00:00,  2.67s/it]

pre tokenize: 100%|██████████| 3/3 [00:00<00:00, 78.96it/s]

Inference Embeddings:   0%|          | 0/3 [00:00<?, ?it/s]
Inference Embeddings:  33%|███▎      | 1/3 [00:05<00:11,  5.97s/it]
Inference Embeddings:  67%|██████▋   | 2/3 [00:07<00:03,  3.10s/it]
Inference Embeddings: 100%|██████████| 3/3 [00:07<00:00,  2.43s/it]

pre tokenize:   0%|          | 0/11 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 11/11 [00:00<00:00, 44.23it/s]

Inference Embeddings:   0%|          | 0/33 [00:00<?, ?it/s]
Inference Embeddings:   3%|▎         | 1/33 [01:21<43:18, 81.19s/it]
Inference Embeddings:   6%|▌         | 2/33 [01:21<17:30, 33.87s/it]
Inference Embeddings:   9%|▉         | 3/33 [01:22<09:22, 18.75s/it]
Inference Embeddings:  12%|█▏        | 4/33 [01:23<05:37, 11.62s/it]
Inference Embeddings:  15%|█▌        | 5/33 [01:23<03:33,  7.63s/it]
Inference Embeddings:  18%|█▊        | 6/33 [01:24<02:21,  5.23s/it]
Inference Embeddings:  21%|██        | 7/33 [01:25<01:35,  3.68s/it]
Inference Embeddings:  24%|██▍       | 8/33 [01:25<01:06,  2.65s/it]
Inference Embeddings:  27%|██▋       | 9/33 [01:25<00:47,  1.97s/it]
Inference Embeddings:  30%|███       | 10/33 [01:26<00:34,  1.50s/it]
Inference Embeddings:  33%|███▎      | 11/33 [01:26<00:25,  1.18s/it]
Inference Embeddings:  36%|███▋      | 12/33 [01:27<00:19,  1.06it/s]
Inference Embeddings:  39%|███▉      | 13/33 [01:27<00:15,  1.32it/s]
Inference Embeddings:  42%|████▏     | 14/33 [01:27<00:12,  1.57it/s]
Inference Embeddings:  45%|████▌     | 15/33 [01:28<00:09,  1.81it/s]
Inference Embeddings:  48%|████▊     | 16/33 [01:28<00:08,  2.05it/s]
Inference Embeddings:  52%|█████▏    | 17/33 [01:28<00:07,  2.28it/s]
Inference Embeddings:  55%|█████▍    | 18/33 [01:29<00:06,  2.49it/s]
Inference Embeddings:  58%|█████▊    | 19/33 [01:29<00:05,  2.76it/s]
Inference Embeddings:  61%|██████    | 20/33 [01:29<00:04,  2.97it/s]
Inference Embeddings:  64%|██████▎   | 21/33 [01:30<00:03,  3.30it/s]
Inference Embeddings:  67%|██████▋   | 22/33 [01:30<00:03,  3.57it/s]
Inference Embeddings:  70%|██████▉   | 23/33 [01:30<00:02,  3.77it/s]
Inference Embeddings:  73%|███████▎  | 24/33 [01:30<00:02,  3.92it/s]
Inference Embeddings:  76%|███████▌  | 25/33 [01:30<00:01,  4.16it/s]
Inference Embeddings:  79%|███████▉  | 26/33 [01:31<00:01,  4.35it/s]
Inference Embeddings:  82%|████████▏ | 27/33 [01:31<00:01,  4.55it/s]
Inference Embeddings:  85%|████████▍ | 28/33 [01:31<00:01,  4.80it/s]
Inference Embeddings:  88%|████████▊ | 29/33 [01:31<00:00,  4.97it/s]
Inference Embeddings:  91%|█████████ | 30/33 [01:31<00:00,  5.31it/s]
Inference Embeddings:  94%|█████████▍| 31/33 [01:32<00:00,  5.65it/s]
Inference Embeddings: 100%|██████████| 33/33 [01:32<00:00,  2.79s/it]

pre tokenize:   0%|          | 0/8 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 8/8 [00:00<00:00, 54.78it/s]

Inference Embeddings:   0%|          | 0/24 [00:00<?, ?it/s]
Inference Embeddings:   4%|▍         | 1/24 [01:20<30:50, 80.46s/it]
Inference Embeddings:   8%|▊         | 2/24 [01:21<12:17, 33.54s/it]
Inference Embeddings:  12%|█▎        | 3/24 [01:21<06:28, 18.49s/it]
Inference Embeddings:  17%|█▋        | 4/24 [01:22<03:47, 11.38s/it]
Inference Embeddings:  21%|██        | 5/24 [01:22<02:21,  7.44s/it]
Inference Embeddings:  25%|██▌       | 6/24 [01:23<01:30,  5.04s/it]
Inference Embeddings:  29%|██▉       | 7/24 [01:23<00:59,  3.53s/it]
Inference Embeddings:  33%|███▎      | 8/24 [01:23<00:40,  2.51s/it]
Inference Embeddings:  38%|███▊      | 9/24 [01:24<00:27,  1.84s/it]
Inference Embeddings:  42%|████▏     | 10/24 [01:24<00:19,  1.37s/it]
Inference Embeddings:  46%|████▌     | 11/24 [01:24<00:13,  1.05s/it]
Inference Embeddings:  50%|█████     | 12/24 [01:25<00:09,  1.21it/s]
Inference Embeddings:  54%|█████▍    | 13/24 [01:25<00:07,  1.49it/s]
Inference Embeddings:  58%|█████▊    | 14/24 [01:25<00:05,  1.82it/s]
Inference Embeddings:  62%|██████▎   | 15/24 [01:25<00:04,  2.14it/s]
Inference Embeddings:  67%|██████▋   | 16/24 [01:26<00:03,  2.54it/s]
Inference Embeddings:  71%|███████   | 17/24 [01:26<00:02,  2.92it/s]
Inference Embeddings:  75%|███████▌  | 18/24 [01:26<00:01,  3.24it/s]
Inference Embeddings:  79%|███████▉  | 19/24 [01:26<00:01,  3.60it/s]
Inference Embeddings:  83%|████████▎ | 20/24 [01:27<00:01,  3.91it/s]
Inference Embeddings:  88%|████████▊ | 21/24 [01:27<00:00,  4.30it/s]
Inference Embeddings:  92%|█████████▏| 22/24 [01:27<00:00,  4.77it/s]
Inference Embeddings:  96%|█████████▌| 23/24 [01:27<00:00,  5.23it/s]
Inference Embeddings: 100%|██████████| 24/24 [01:27<00:00,  3.65s/it]

pre tokenize: 100%|██████████| 2/2 [00:00<00:00, 44.98it/s]

Inference Embeddings:   0%|          | 0/4 [00:00<?, ?it/s]
Inference Embeddings:  25%|██▌       | 1/4 [01:19<03:59, 79.84s/it]
Inference Embeddings:  50%|█████     | 2/4 [01:20<01:06, 33.37s/it]
Inference Embeddings:  75%|███████▌  | 3/4 [01:21<00:18, 18.37s/it]
Inference Embeddings: 100%|██████████| 4/4 [01:21<00:00, 20.32s/it]

pre tokenize:   0%|          | 0/18 [00:00<?, ?it/s]
pre tokenize:  33%|███▎      | 6/18 [00:00<00:00, 55.82it/s]
pre tokenize: 100%|██████████| 18/18 [00:00<00:00, 51.35it/s]

Inference Embeddings:   0%|          | 0/55 [00:00<?, ?it/s]
Inference Embeddings:   2%|▏         | 1/55 [01:20<1:12:46, 80.86s/it]
Inference Embeddings:   4%|▎         | 2/55 [01:21<29:47, 33.73s/it]
Inference Embeddings:   5%|▌         | 3/55 [01:22<16:06, 18.58s/it]
Inference Embeddings:   7%|▋         | 4/55 [01:22<09:45, 11.48s/it]
Inference Embeddings:   9%|▉         | 5/55 [01:23<06:15,  7.52s/it]
Inference Embeddings:  11%|█         | 6/55 [01:23<04:11,  5.14s/it]
Inference Embeddings:  13%|█▎        | 7/55 [01:24<02:53,  3.62s/it]
Inference Embeddings:  15%|█▍        | 8/55 [01:24<02:03,  2.62s/it]
Inference Embeddings:  16%|█▋        | 9/55 [01:25<01:29,  1.94s/it]
Inference Embeddings:  18%|█▊        | 10/55 [01:25<01:06,  1.48s/it]
Inference Embeddings:  20%|██        | 11/55 [01:26<00:50,  1.15s/it]
Inference Embeddings:  22%|██▏       | 12/55 [01:26<00:39,  1.09it/s]
Inference Embeddings:  24%|██▎       | 13/55 [01:26<00:32,  1.31it/s]
Inference Embeddings:  25%|██▌       | 14/55 [01:27<00:26,  1.58it/s]
Inference Embeddings:  27%|██▋       | 15/55 [01:27<00:21,  1.82it/s]
Inference Embeddings:  29%|██▉       | 16/55 [01:27<00:19,  2.03it/s]
Inference Embeddings:  31%|███       | 17/55 [01:28<00:17,  2.21it/s]
Inference Embeddings:  33%|███▎      | 18/55 [01:28<00:15,  2.39it/s]
Inference Embeddings:  35%|███▍      | 19/55 [01:28<00:14,  2.52it/s]
Inference Embeddings:  36%|███▋      | 20/55 [01:29<00:13,  2.67it/s]
Inference Embeddings:  38%|███▊      | 21/55 [01:29<00:12,  2.78it/s]
Inference Embeddings:  40%|████      | 22/55 [01:29<00:11,  2.90it/s]
Inference Embeddings:  42%|████▏     | 23/55 [01:30<00:10,  2.97it/s]
Inference Embeddings:  44%|████▎     | 24/55 [01:30<00:09,  3.15it/s]
Inference Embeddings:  45%|████▌     | 25/55 [01:30<00:09,  3.29it/s]
Inference Embeddings:  47%|████▋     | 26/55 [01:31<00:08,  3.39it/s]
Inference Embeddings:  49%|████▉     | 27/55 [01:31<00:08,  3.44it/s]
Inference Embeddings:  51%|█████     | 28/55 [01:31<00:07,  3.47it/s]
Inference Embeddings:  53%|█████▎    | 29/55 [01:31<00:07,  3.48it/s]
Inference Embeddings:  55%|█████▍    | 30/55 [01:32<00:06,  3.71it/s]
Inference Embeddings:  56%|█████▋    | 31/55 [01:32<00:06,  3.92it/s]
Inference Embeddings:  58%|█████▊    | 32/55 [01:32<00:05,  4.07it/s]
Inference Embeddings:  60%|██████    | 33/55 [01:32<00:05,  4.16it/s]
Inference Embeddings:  62%|██████▏   | 34/55 [01:32<00:04,  4.21it/s]
Inference Embeddings:  64%|██████▎   | 35/55 [01:33<00:04,  4.23it/s]
Inference Embeddings:  65%|██████▌   | 36/55 [01:33<00:04,  4.24it/s]
Inference Embeddings:  67%|██████▋   | 37/55 [01:33<00:04,  4.26it/s]
Inference Embeddings:  69%|██████▉   | 38/55 [01:33<00:04,  4.24it/s]
Inference Embeddings:  71%|███████   | 39/55 [01:34<00:03,  4.40it/s]
Inference Embeddings:  73%|███████▎  | 40/55 [01:34<00:03,  4.51it/s]
Inference Embeddings:  75%|███████▍  | 41/55 [01:34<00:03,  4.60it/s]
Inference Embeddings:  76%|███████▋  | 42/55 [01:34<00:02,  4.67it/s]
Inference Embeddings:  78%|███████▊  | 43/55 [01:34<00:02,  4.78it/s]
Inference Embeddings:  80%|████████  | 44/55 [01:35<00:02,  4.84it/s]
Inference Embeddings:  82%|████████▏ | 45/55 [01:35<00:01,  5.02it/s]
Inference Embeddings:  84%|████████▎ | 46/55 [01:35<00:01,  5.19it/s]
Inference Embeddings:  85%|████████▌ | 47/55 [01:35<00:01,  5.27it/s]
Inference Embeddings:  87%|████████▋ | 48/55 [01:35<00:01,  5.34it/s]
Inference Embeddings:  89%|████████▉ | 49/55 [01:36<00:01,  5.61it/s]
Inference Embeddings:  91%|█████████ | 50/55 [01:36<00:00,  5.88it/s]
Inference Embeddings:  93%|█████████▎| 51/55 [01:36<00:00,  6.10it/s]
Inference Embeddings:  95%|█████████▍| 52/55 [01:36<00:00,  6.21it/s]
Inference Embeddings:  96%|█████████▋| 53/55 [01:36<00:00,  6.72it/s]
Inference Embeddings: 100%|██████████| 55/55 [01:36<00:00,  1.76s/it]

Inference Embeddings:   0%|          | 0/3 [00:00<?, ?it/s]
Inference Embeddings:  33%|███▎      | 1/3 [01:20<02:40, 80.10s/it]
Inference Embeddings:  67%|██████▋   | 2/3 [01:20<00:33, 33.18s/it]
Inference Embeddings: 100%|██████████| 3/3 [01:20<00:00, 26.88s/it]

pre tokenize: 100%|██████████| 2/2 [00:00<00:00, 47.05it/s]

Inference Embeddings:   0%|          | 0/2 [00:00<?, ?it/s]
Inference Embeddings:  50%|█████     | 1/2 [00:26<00:26, 26.06s/it]
Inference Embeddings: 100%|██████████| 2/2 [00:26<00:00, 13.17s/it]

pre tokenize: 100%|██████████| 3/3 [00:00<00:00, 45.97it/s]

Inference Embeddings:   0%|          | 0/3 [00:00<?, ?it/s]
Inference Embeddings:  33%|███▎      | 1/3 [00:04<00:09,  4.88s/it]
Inference Embeddings:  67%|██████▋   | 2/3 [00:05<00:02,  2.53s/it]
Inference Embeddings: 100%|██████████| 3/3 [00:05<00:00,  1.96s/it]

pre tokenize: 100%|██████████| 2/2 [00:00<00:00, 47.96it/s]

Inference Embeddings:   0%|          | 0/2 [00:00<?, ?it/s]
Inference Embeddings:  50%|█████     | 1/2 [00:03<00:03,  3.61s/it]
Inference Embeddings: 100%|██████████| 2/2 [00:03<00:00,  1.86s/it]

pre tokenize: 100%|██████████| 5/5 [00:00<00:00, 61.17it/s]

Inference Embeddings:   0%|          | 0/5 [00:00<?, ?it/s]
Inference Embeddings:  20%|██        | 1/5 [00:07<00:30,  7.56s/it]
Inference Embeddings:  40%|████      | 2/5 [00:08<00:11,  3.82s/it]
Inference Embeddings:  60%|██████    | 3/5 [00:09<00:04,  2.48s/it]
Inference Embeddings:  80%|████████  | 4/5 [00:10<00:01,  1.76s/it]
Inference Embeddings: 100%|██████████| 5/5 [00:10<00:00,  2.11s/it]

pre tokenize: 100%|██████████| 2/2 [00:00<00:00, 34.80it/s]

Inference Embeddings:   0%|          | 0/2 [00:00<?, ?it/s]
Inference Embeddings:  50%|█████     | 1/2 [00:04<00:04,  4.53s/it]
Inference Embeddings: 100%|██████████| 2/2 [00:04<00:00,  2.48s/it]

pre tokenize: 100%|██████████| 2/2 [00:00<00:00, 61.45it/s]

Inference Embeddings:   0%|          | 0/2 [00:00<?, ?it/s]
Inference Embeddings:  50%|█████     | 1/2 [00:05<00:05,  5.13s/it]
Inference Embeddings: 100%|██████████| 2/2 [00:05<00:00,  2.68s/it]

pre tokenize: 100%|██████████| 2/2 [00:00<00:00, 61.46it/s]

Inference Embeddings:   0%|          | 0/2 [00:00<?, ?it/s]
Inference Embeddings:  50%|█████     | 1/2 [00:05<00:05,  5.37s/it]
Inference Embeddings: 100%|██████████| 2/2 [00:06<00:00,  3.06s/it]

Inference Embeddings:   0%|          | 0/3 [00:00<?, ?it/s]
Inference Embeddings:  33%|███▎      | 1/3 [01:21<02:42, 81.33s/it]
Inference Embeddings:  67%|██████▋   | 2/3 [01:21<00:33, 33.79s/it]
Inference Embeddings: 100%|██████████| 3/3 [01:22<00:00, 27.36s/it]

Inference Embeddings:   0%|          | 0/4 [00:00<?, ?it/s]
Inference Embeddings:  25%|██▌       | 1/4 [01:19<03:58, 79.59s/it]
Inference Embeddings:  50%|█████     | 2/4 [01:19<01:05, 32.97s/it]
Inference Embeddings: 100%|██████████| 4/4 [01:20<00:00, 20.05s/it]

pre tokenize:   0%|          | 0/11 [00:00<?, ?it/s]
pre tokenize:  36%|███▋      | 4/11 [00:00<00:00, 32.35it/s]
pre tokenize: 100%|██████████| 11/11 [00:00<00:00, 31.74it/s]

Inference Embeddings:   0%|          | 0/11 [00:00<?, ?it/s]
Inference Embeddings:   9%|▉         | 1/11 [00:14<02:26, 14.65s/it]
Inference Embeddings:  18%|█▊        | 2/11 [00:16<01:03,  7.03s/it]
Inference Embeddings:  27%|██▋       | 3/11 [00:17<00:36,  4.52s/it]
Inference Embeddings:  36%|███▋      | 4/11 [00:19<00:22,  3.28s/it]
Inference Embeddings:  45%|████▌     | 5/11 [00:20<00:15,  2.55s/it]
Inference Embeddings:  55%|█████▍    | 6/11 [00:21<00:10,  2.08s/it]
Inference Embeddings:  64%|██████▎   | 7/11 [00:22<00:07,  1.76s/it]
Inference Embeddings:  73%|███████▎  | 8/11 [00:23<00:04,  1.50s/it]
Inference Embeddings:  82%|████████▏ | 9/11 [00:24<00:02,  1.31s/it]
Inference Embeddings:  91%|█████████ | 10/11 [00:25<00:01,  1.11s/it]
Inference Embeddings: 100%|██████████| 11/11 [00:25<00:00,  2.31s/it]

pre tokenize:   0%|          | 0/15 [00:00<?, ?it/s]
pre tokenize:  33%|███▎      | 5/15 [00:00<00:00, 48.79it/s]
pre tokenize: 100%|██████████| 15/15 [00:00<00:00, 55.32it/s]

Inference Embeddings:   0%|          | 0/15 [00:00<?, ?it/s]
Inference Embeddings:   7%|▋         | 1/15 [00:18<04:16, 18.31s/it]
Inference Embeddings:  13%|█▎        | 2/15 [00:21<01:59,  9.17s/it]
Inference Embeddings:  20%|██        | 3/15 [00:23<01:12,  6.03s/it]
Inference Embeddings:  27%|██▋       | 4/15 [00:25<00:47,  4.33s/it]
Inference Embeddings:  33%|███▎      | 5/15 [00:26<00:33,  3.36s/it]
Inference Embeddings:  40%|████      | 6/15 [00:28<00:24,  2.69s/it]
Inference Embeddings:  47%|████▋     | 7/15 [00:29<00:17,  2.17s/it]
Inference Embeddings:  53%|█████▎    | 8/15 [00:30<00:12,  1.76s/it]
Inference Embeddings:  60%|██████    | 9/15 [00:31<00:08,  1.49s/it]
Inference Embeddings:  67%|██████▋   | 10/15 [00:31<00:06,  1.24s/it]
Inference Embeddings:  73%|███████▎  | 11/15 [00:32<00:04,  1.06s/it]
Inference Embeddings:  80%|████████  | 12/15 [00:32<00:02,  1.11it/s]

30089
7916
periti_2025
      0                                                  1  \
0  head  seen a complex and exquisitely balanced polity...
1  head  inculcated doctrines incompatible with the pla...
2  word  , during all this period , once entering those...
3  word  immaturity , and want of experience -- besides...
4  part  immaturity , and want of experience -- besides...

                                                   2
0                    (Figurative) A leader or chief.
1  (Figurative) The most important part or piece ...
2  The smallest discrete unit of written language...
3    (Obsolete) Something spoken; speech, discourse.
4  (Obsolete) A third; a third part; a share, a p...

  0%|          | 0/37 [00:00<?, ?it/s]

pre tokenize: 100%|██████████| 3/3 [00:00<00:00, 73.38it/s]

Inference Embeddings:   0%|          | 0/3 [00:00<?, ?it/s]
Inference Embeddings:  33%|███▎      | 1/3 [00:06<00:13,  6.57s/it]
Inference Embeddings: 100%|██████████| 3/3 [00:07<00:00,  2.58s/it]

pre tokenize: 100%|██████████| 4/4 [00:00<00:00, 73.56it/s]

Inference Embeddings:   0%|          | 0/4 [00:00<?, ?it/s]
Inference Embeddings:  25%|██▌       | 1/4 [00:07<00:22,  7.35s/it]
Inference Embeddings:  50%|█████     | 2/4 [00:08<00:07,  3.78s/it]
Inference Embeddings:  75%|███████▌  | 3/4 [00:09<00:02,  2.51s/it]
Inference Embeddings: 100%|██████████| 4/4 [00:10<00:00,  2.57s/it]

pre tokenize: 100%|██████████| 4/4 [00:00<00:00, 42.24it/s]

Inference Embeddings:   0%|          | 0/4 [00:00<?, ?it/s]
Inference Embeddings:  25%|██▌       | 1/4 [00:13<00:39, 13.07s/it]
Inference Embeddings:  50%|█████     | 2/4 [00:14<00:12,  6.15s/it]
Inference Embeddings:  75%|███████▌  | 3/4 [00:15<00:03,  3.76s/it]
Inference Embeddings: 100%|██████████| 4/4 [00:15<00:00,  3.90s/it]

pre tokenize: 100%|██████████| 3/3 [00:00<00:00, 113.34it/s]

Inference Embeddings:   0%|          | 0/3 [00:00<?, ?it/s]
Inference Embeddings:  33%|███▎      | 1/3 [00:05<00:10,  5.17s/it]
Inference Embeddings: 100%|██████████| 3/3 [00:06<00:00,  2.03s/it]

pre tokenize: 100%|██████████| 2/2 [00:00<00:00, 114.87it/s]

Inference Embeddings:   0%|          | 0/2 [00:00<?, ?it/s]
Inference Embeddings: 100%|██████████| 2/2 [00:06<00:00,  3.09s/it]

pre tokenize: 100%|██████████| 2/2 [00:00<00:00, 69.53it/s]

Inference Embeddings:   0%|          | 0/2 [00:00<?, ?it/s]
Inference Embeddings:  50%|█████     | 1/2 [00:06<00:06,  6.08s/it]
Inference Embeddings: 100%|██████████| 2/2 [00:07<00:00,  3.53s/it]

pre tokenize: 100%|██████████| 8/8 [00:00<00:00, 82.55it/s]

Inference Embeddings:   0%|          | 0/8 [00:00<?, ?it/s]
Inference Embeddings:  12%|█▎        | 1/8 [00:06<00:43,  6.18s/it]
Inference Embeddings:  25%|██▌       | 2/8 [00:07<00:20,  3.35s/it]
Inference Embeddings:  38%|███▊      | 3/8 [00:08<00:11,  2.34s/it]
Inference Embeddings:  50%|█████     | 4/8 [00:09<00:07,  1.86s/it]
Inference Embeddings:  62%|██████▎   | 5/8 [00:10<00:04,  1.50s/it]
Inference Embeddings:  75%|███████▌  | 6/8 [00:11<00:02,  1.29s/it]
Inference Embeddings:  88%|████████▊ | 7/8 [00:12<00:01,  1.08s/it]
Inference Embeddings: 100%|██████████| 8/8 [00:12<00:00,  1.55s/it]

pre tokenize: 100%|██████████| 2/2 [00:00<00:00, 60.57it/s]

Inference Embeddings:   0%|          | 0/2 [00:00<?, ?it/s]
Inference Embeddings:  50%|█████     | 1/2 [00:10<00:10, 10.03s/it]
Inference Embeddings: 100%|██████████| 2/2 [00:10<00:00,  5.36s/it]

pre tokenize:   0%|          | 0/11 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 11/11 [00:00<00:00, 75.34it/s]

Inference Embeddings:   0%|          | 0/11 [00:00<?, ?it/s]
Inference Embeddings:   9%|▉         | 1/11 [00:06<01:00,  6.02s/it]
Inference Embeddings:  18%|█▊        | 2/11 [00:07<00:30,  3.41s/it]
Inference Embeddings:  27%|██▋       | 3/11 [00:08<00:19,  2.48s/it]
Inference Embeddings:  36%|███▋      | 4/11 [00:10<00:13,  1.99s/it]
Inference Embeddings:  45%|████▌     | 5/11 [00:11<00:10,  1.67s/it]
Inference Embeddings:  55%|█████▍    | 6/11 [00:12<00:07,  1.48s/it]
Inference Embeddings:  64%|██████▎   | 7/11 [00:13<00:05,  1.31s/it]
Inference Embeddings:  73%|███████▎  | 8/11 [00:14<00:03,  1.17s/it]
Inference Embeddings:  82%|████████▏ | 9/11 [00:15<00:02,  1.04s/it]
Inference Embeddings:  91%|█████████ | 10/11 [00:15<00:00,  1.08it/s]
Inference Embeddings: 100%|██████████| 11/11 [00:16<00:00,  1.47s/it]

pre tokenize:   0%|          | 0/10 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 10/10 [00:00<00:00, 69.90it/s]

Inference Embeddings:   0%|          | 0/10 [00:00<?, ?it/s]
Inference Embeddings:  10%|█         | 1/10 [00:08<01:13,  8.18s/it]
Inference Embeddings:  20%|██        | 2/10 [00:09<00:34,  4.37s/it]
Inference Embeddings:  30%|███       | 3/10 [00:11<00:21,  3.04s/it]
Inference Embeddings:  40%|████      | 4/10 [00:12<00:14,  2.36s/it]
Inference Embeddings:  50%|█████     | 5/10 [00:13<00:09,  1.93s/it]
Inference Embeddings:  60%|██████    | 6/10 [00:14<00:06,  1.65s/it]
Inference Embeddings:  70%|███████   | 7/10 [00:15<00:04,  1.43s/it]
Inference Embeddings:  80%|████████  | 8/10 [00:16<00:02,  1.26s/it]
Inference Embeddings:  90%|█████████ | 9/10 [00:17<00:01,  1.11s/it]
Inference Embeddings: 100%|██████████| 10/10 [00:17<00:00,  1.79s/it]

pre tokenize: 100%|██████████| 2/2 [00:00<00:00, 81.52it/s]

Inference Embeddings:   0%|          | 0/2 [00:00<?, ?it/s]
Inference Embeddings: 100%|██████████| 2/2 [00:07<00:00,  3.55s/it]

pre tokenize:   0%|          | 0/12 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 12/12 [00:00<00:00, 71.86it/s]

Inference Embeddings:   0%|          | 0/12 [00:00<?, ?it/s]
Inference Embeddings:   8%|▊         | 1/12 [00:06<01:15,  6.87s/it]
Inference Embeddings:  17%|█▋        | 2/12 [00:08<00:36,  3.69s/it]
Inference Embeddings:  25%|██▌       | 3/12 [00:09<00:23,  2.58s/it]
Inference Embeddings:  33%|███▎      | 4/12 [00:10<00:16,  2.00s/it]
Inference Embeddings:  42%|████▏     | 5/12 [00:11<00:11,  1.70s/it]
Inference Embeddings:  50%|█████     | 6/12 [00:12<00:08,  1.45s/it]
Inference Embeddings:  58%|█████▊    | 7/12 [00:13<00:06,  1.27s/it]
Inference Embeddings:  67%|██████▋   | 8/12 [00:14<00:04,  1.15s/it]
Inference Embeddings:  75%|███████▌  | 9/12 [00:15<00:03,  1.02s/it]
Inference Embeddings:  83%|████████▎ | 10/12 [00:16<00:01,  1.07it/s]
Inference Embeddings: 100%|██████████| 12/12 [00:16<00:00,  1.39s/it]

pre tokenize: 100%|██████████| 3/3 [00:00<00:00, 38.99it/s]

Inference Embeddings:   0%|          | 0/3 [00:00<?, ?it/s]
Inference Embeddings:  33%|███▎      | 1/3 [00:08<00:16,  8.25s/it]
Inference Embeddings:  67%|██████▋   | 2/3 [00:09<00:04,  4.13s/it]
Inference Embeddings: 100%|██████████| 3/3 [00:09<00:00,  3.30s/it]

pre tokenize: 100%|██████████| 2/2 [00:00<00:00, 65.47it/s]

Inference Embeddings:   0%|          | 0/2 [00:00<?, ?it/s]
Inference Embeddings:  50%|█████     | 1/2 [00:06<00:06,  6.19s/it]
Inference Embeddings: 100%|██████████| 2/2 [00:07<00:00,  3.54s/it]

pre tokenize: 100%|██████████| 3/3 [00:00<00:00, 39.17it/s]

Inference Embeddings:   0%|          | 0/3 [00:00<?, ?it/s]
Inference Embeddings:  33%|███▎      | 1/3 [00:07<00:14,  7.32s/it]
Inference Embeddings:  67%|██████▋   | 2/3 [00:08<00:03,  3.67s/it]
Inference Embeddings: 100%|██████████| 3/3 [00:08<00:00,  2.98s/it]

pre tokenize: 100%|██████████| 2/2 [00:00<00:00, 48.66it/s]

Inference Embeddings:   0%|          | 0/2 [00:00<?, ?it/s]
Inference Embeddings:  50%|█████     | 1/2 [00:14<00:14, 14.06s/it]
Inference Embeddings: 100%|██████████| 2/2 [00:14<00:00,  7.44s/it]

pre tokenize: 100%|██████████| 2/2 [00:00<00:00, 87.85it/s]

Inference Embeddings:   0%|          | 0/2 [00:00<?, ?it/s]
Inference Embeddings: 100%|██████████| 2/2 [00:05<00:00,  2.99s/it]

pre tokenize:   0%|          | 0/7 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 7/7 [00:00<00:00, 51.67it/s]

Inference Embeddings:   0%|          | 0/7 [00:00<?, ?it/s]
Inference Embeddings:  14%|█▍        | 1/7 [00:08<00:50,  8.44s/it]
Inference Embeddings:  29%|██▊       | 2/7 [00:10<00:23,  4.68s/it]
Inference Embeddings:  43%|████▎     | 3/7 [00:12<00:12,  3.24s/it]
Inference Embeddings:  57%|█████▋    | 4/7 [00:13<00:07,  2.48s/it]
Inference Embeddings:  71%|███████▏  | 5/7 [00:14<00:03,  1.98s/it]
Inference Embeddings:  86%|████████▌ | 6/7 [00:15<00:01,  1.61s/it]
Inference Embeddings: 100%|██████████| 7/7 [00:15<00:00,  2.20s/it]

pre tokenize:   0%|          | 0/8 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 8/8 [00:00<00:00, 62.02it/s]

Inference Embeddings:   0%|          | 0/8 [00:00<?, ?it/s]
Inference Embeddings:  12%|█▎        | 1/8 [00:07<00:54,  7.77s/it]
Inference Embeddings:  25%|██▌       | 2/8 [00:09<00:24,  4.14s/it]
Inference Embeddings:  38%|███▊      | 3/8 [00:10<00:14,  2.88s/it]
Inference Embeddings:  50%|█████     | 4/8 [00:11<00:08,  2.17s/it]
Inference Embeddings:  62%|██████▎   | 5/8 [00:12<00:05,  1.74s/it]
Inference Embeddings:  75%|███████▌  | 6/8 [00:13<00:02,  1.45s/it]
Inference Embeddings:  88%|████████▊ | 7/8 [00:14<00:01,  1.27s/it]
Inference Embeddings: 100%|██████████| 8/8 [00:15<00:00,  1.91s/it]

22924
6577

In [ ]:
method = "greedy"
new_dir = os.path.join(eng_path, f"{method}-clustered-sep/")
os.makedirs(new_dir, exist_ok=True)
for n in (1, 2):
    print(n)
    method_result = cluster_sep(method, eng_path, n)
    method_result["2"] = method_result["labels"]
    method_result.drop("labels", inplace=True, axis=1)
    method_result.to_csv(f"{new_dir}english-corpus{n}.tsv.gz", sep='\t', index=False, compression="gzip")
    method_result.head()

1

  0%|          | 0/37 [00:00<?, ?it/s]

pre tokenize: 100%|██████████| 2/2 [00:00<00:00, 109.92it/s]

Inference Embeddings:   0%|          | 0/2 [00:00<?, ?it/s]
Inference Embeddings:  50%|█████     | 1/2 [00:03<00:03,  3.17s/it]
Inference Embeddings: 100%|██████████| 2/2 [00:03<00:00,  1.66s/it]

pre tokenize: 100%|██████████| 2/2 [00:00<00:00, 109.89it/s]

Inference Embeddings:   0%|          | 0/2 [00:00<?, ?it/s]
Inference Embeddings:  50%|█████     | 1/2 [00:03<00:03,  3.10s/it]
Inference Embeddings: 100%|██████████| 2/2 [00:03<00:00,  1.70s/it]

pre tokenize: 100%|██████████| 2/2 [00:00<00:00, 126.94it/s]

Inference Embeddings:   0%|          | 0/2 [00:00<?, ?it/s]
Inference Embeddings:  50%|█████     | 1/2 [00:03<00:03,  3.15s/it]
Inference Embeddings: 100%|██████████| 2/2 [00:03<00:00,  1.68s/it]

pre tokenize: 100%|██████████| 5/5 [00:00<00:00, 84.74it/s]

Inference Embeddings:   0%|          | 0/5 [00:00<?, ?it/s]
Inference Embeddings:  20%|██        | 1/5 [00:03<00:14,  3.73s/it]
Inference Embeddings:  40%|████      | 2/5 [00:04<00:06,  2.18s/it]
Inference Embeddings:  60%|██████    | 3/5 [00:05<00:03,  1.59s/it]
Inference Embeddings:  80%|████████  | 4/5 [00:06<00:01,  1.23s/it]
Inference Embeddings: 100%|██████████| 5/5 [00:06<00:00,  1.35s/it]

pre tokenize:   0%|          | 0/11 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 11/11 [00:00<00:00, 84.34it/s]

Inference Embeddings:   0%|          | 0/11 [00:00<?, ?it/s]
Inference Embeddings:   9%|▉         | 1/11 [00:04<00:46,  4.65s/it]
Inference Embeddings:  18%|█▊        | 2/11 [00:06<00:25,  2.80s/it]
Inference Embeddings:  27%|██▋       | 3/11 [00:07<00:16,  2.08s/it]
Inference Embeddings:  36%|███▋      | 4/11 [00:08<00:11,  1.70s/it]
Inference Embeddings:  45%|████▌     | 5/11 [00:09<00:08,  1.44s/it]
Inference Embeddings:  55%|█████▍    | 6/11 [00:10<00:06,  1.26s/it]
Inference Embeddings:  64%|██████▎   | 7/11 [00:11<00:04,  1.10s/it]
Inference Embeddings:  73%|███████▎  | 8/11 [00:11<00:02,  1.03it/s]
Inference Embeddings:  82%|████████▏ | 9/11 [00:12<00:01,  1.14it/s]
Inference Embeddings:  91%|█████████ | 10/11 [00:12<00:00,  1.34it/s]
Inference Embeddings: 100%|██████████| 11/11 [00:13<00:00,  1.19s/it]

pre tokenize: 100%|██████████| 7/7 [00:00<00:00, 86.34it/s]

Inference Embeddings:   0%|          | 0/7 [00:00<?, ?it/s]
Inference Embeddings:  14%|█▍        | 1/7 [00:03<00:23,  3.84s/it]
Inference Embeddings:  29%|██▊       | 2/7 [00:05<00:12,  2.40s/it]
Inference Embeddings:  43%|████▎     | 3/7 [00:06<00:07,  1.81s/it]
Inference Embeddings:  57%|█████▋    | 4/7 [00:07<00:04,  1.45s/it]
Inference Embeddings:  71%|███████▏  | 5/7 [00:07<00:02,  1.20s/it]
Inference Embeddings:  86%|████████▌ | 6/7 [00:08<00:01,  1.01s/it]
Inference Embeddings: 100%|██████████| 7/7 [00:08<00:00,  1.25s/it]

pre tokenize:   0%|          | 0/7 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 7/7 [00:00<00:00, 68.39it/s]

Inference Embeddings:   0%|          | 0/7 [00:00<?, ?it/s]
Inference Embeddings:  14%|█▍        | 1/7 [00:03<00:22,  3.68s/it]
Inference Embeddings:  29%|██▊       | 2/7 [00:04<00:09,  1.95s/it]
Inference Embeddings:  43%|████▎     | 3/7 [00:05<00:05,  1.36s/it]
Inference Embeddings:  57%|█████▋    | 4/7 [00:05<00:03,  1.02s/it]
Inference Embeddings:  71%|███████▏  | 5/7 [00:06<00:01,  1.22it/s]
Inference Embeddings: 100%|██████████| 7/7 [00:06<00:00,  1.08it/s]

pre tokenize: 100%|██████████| 2/2 [00:00<00:00, 91.05it/s]

Inference Embeddings:   0%|          | 0/2 [00:00<?, ?it/s]
Inference Embeddings:  50%|█████     | 1/2 [00:03<00:03,  3.94s/it]
Inference Embeddings: 100%|██████████| 2/2 [00:04<00:00,  2.14s/it]

pre tokenize: 100%|██████████| 2/2 [00:00<00:00, 121.52it/s]

Inference Embeddings:   0%|          | 0/2 [00:00<?, ?it/s]
Inference Embeddings: 100%|██████████| 2/2 [00:03<00:00,  1.66s/it]

pre tokenize:   0%|          | 0/9 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 9/9 [00:00<00:00, 63.90it/s]

Inference Embeddings:   0%|          | 0/9 [00:00<?, ?it/s]
Inference Embeddings:  11%|█         | 1/9 [00:04<00:35,  4.47s/it]
Inference Embeddings:  22%|██▏       | 2/9 [00:06<00:19,  2.78s/it]
Inference Embeddings:  33%|███▎      | 3/9 [00:07<00:13,  2.18s/it]
Inference Embeddings:  44%|████▍     | 4/9 [00:08<00:09,  1.84s/it]
Inference Embeddings:  56%|█████▌    | 5/9 [00:10<00:06,  1.63s/it]
Inference Embeddings:  67%|██████▋   | 6/9 [00:11<00:04,  1.45s/it]
Inference Embeddings:  78%|███████▊  | 7/9 [00:12<00:02,  1.29s/it]
Inference Embeddings: 100%|██████████| 9/9 [00:13<00:00,  1.46s/it]

pre tokenize:   0%|          | 0/11 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 11/11 [00:00<00:00, 74.22it/s]

Inference Embeddings:   0%|          | 0/11 [00:00<?, ?it/s]
Inference Embeddings:   9%|▉         | 1/11 [00:04<00:44,  4.41s/it]
Inference Embeddings:  18%|█▊        | 2/11 [00:05<00:23,  2.62s/it]
Inference Embeddings:  27%|██▋       | 3/11 [00:06<00:15,  1.92s/it]
Inference Embeddings:  36%|███▋      | 4/11 [00:07<00:10,  1.55s/it]
Inference Embeddings:  45%|████▌     | 5/11 [00:08<00:07,  1.31s/it]
Inference Embeddings:  55%|█████▍    | 6/11 [00:09<00:05,  1.16s/it]
Inference Embeddings:  64%|██████▎   | 7/11 [00:10<00:04,  1.03s/it]
Inference Embeddings:  73%|███████▎  | 8/11 [00:11<00:02,  1.10it/s]
Inference Embeddings:  82%|████████▏ | 9/11 [00:11<00:01,  1.17it/s]
Inference Embeddings:  91%|█████████ | 10/11 [00:12<00:00,  1.32it/s]
Inference Embeddings: 100%|██████████| 11/11 [00:12<00:00,  1.16s/it]

16420
3718
2

  0%|          | 0/37 [00:00<?, ?it/s]

pre tokenize: 100%|██████████| 3/3 [00:00<00:00, 111.88it/s]

Inference Embeddings:   0%|          | 0/3 [00:00<?, ?it/s]
Inference Embeddings:  33%|███▎      | 1/3 [00:03<00:07,  3.54s/it]
Inference Embeddings:  67%|██████▋   | 2/3 [00:04<00:01,  1.87s/it]
Inference Embeddings: 100%|██████████| 3/3 [00:04<00:00,  1.47s/it]

pre tokenize: 100%|██████████| 3/3 [00:00<00:00, 53.04it/s]

Inference Embeddings:   0%|          | 0/3 [00:00<?, ?it/s]
Inference Embeddings:  33%|███▎      | 1/3 [00:03<00:07,  3.99s/it]
Inference Embeddings:  67%|██████▋   | 2/3 [00:04<00:02,  2.16s/it]
Inference Embeddings: 100%|██████████| 3/3 [00:05<00:00,  1.73s/it]

pre tokenize: 100%|██████████| 3/3 [00:00<00:00, 118.55it/s]

Inference Embeddings:   0%|          | 0/3 [00:00<?, ?it/s]
Inference Embeddings:  33%|███▎      | 1/3 [00:04<00:08,  4.02s/it]
Inference Embeddings:  67%|██████▋   | 2/3 [00:04<00:02,  2.08s/it]
Inference Embeddings: 100%|██████████| 3/3 [00:04<00:00,  1.65s/it]

pre tokenize: 100%|██████████| 2/2 [00:00<00:00, 112.42it/s]

Inference Embeddings:   0%|          | 0/2 [00:00<?, ?it/s]
Inference Embeddings:  50%|█████     | 1/2 [00:03<00:03,  3.95s/it]
Inference Embeddings: 100%|██████████| 2/2 [00:04<00:00,  2.14s/it]

pre tokenize: 100%|██████████| 2/2 [00:00<00:00, 145.66it/s]

Inference Embeddings:   0%|          | 0/2 [00:00<?, ?it/s]
Inference Embeddings: 100%|██████████| 2/2 [00:02<00:00,  1.14s/it]

pre tokenize: 100%|██████████| 3/3 [00:00<00:00, 88.88it/s]

Inference Embeddings:   0%|          | 0/3 [00:00<?, ?it/s]
Inference Embeddings:  33%|███▎      | 1/3 [00:03<00:06,  3.11s/it]
Inference Embeddings:  67%|██████▋   | 2/3 [00:03<00:01,  1.74s/it]
Inference Embeddings: 100%|██████████| 3/3 [00:04<00:00,  1.49s/it]

pre tokenize:   0%|          | 0/6 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 6/6 [00:00<00:00, 45.11it/s]

Inference Embeddings:   0%|          | 0/6 [00:00<?, ?it/s]
Inference Embeddings:  17%|█▋        | 1/6 [00:03<00:19,  3.82s/it]
Inference Embeddings:  33%|███▎      | 2/6 [00:04<00:08,  2.23s/it]
Inference Embeddings:  50%|█████     | 3/6 [00:05<00:04,  1.65s/it]
Inference Embeddings:  67%|██████▋   | 4/6 [00:06<00:02,  1.30s/it]
Inference Embeddings:  83%|████████▎ | 5/6 [00:07<00:01,  1.07s/it]
Inference Embeddings: 100%|██████████| 6/6 [00:07<00:00,  1.26s/it]

pre tokenize: 100%|██████████| 2/2 [00:00<00:00, 107.50it/s]

Inference Embeddings:   0%|          | 0/2 [00:00<?, ?it/s]
Inference Embeddings: 100%|██████████| 2/2 [00:04<00:00,  2.20s/it]

pre tokenize: 100%|██████████| 3/3 [00:00<00:00, 44.90it/s]

Inference Embeddings:   0%|          | 0/3 [00:00<?, ?it/s]
Inference Embeddings:  33%|███▎      | 1/3 [00:04<00:09,  4.58s/it]
Inference Embeddings:  67%|██████▋   | 2/3 [00:05<00:02,  2.53s/it]
Inference Embeddings: 100%|██████████| 3/3 [00:05<00:00,  1.97s/it]

pre tokenize:   0%|          | 0/11 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 11/11 [00:00<00:00, 79.09it/s]

Inference Embeddings:   0%|          | 0/11 [00:00<?, ?it/s]
Inference Embeddings:   9%|▉         | 1/11 [00:04<00:45,  4.60s/it]
Inference Embeddings:  18%|█▊        | 2/11 [00:06<00:24,  2.76s/it]
Inference Embeddings:  27%|██▋       | 3/11 [00:07<00:16,  2.08s/it]
Inference Embeddings:  36%|███▋      | 4/11 [00:08<00:12,  1.72s/it]
Inference Embeddings:  45%|████▌     | 5/11 [00:09<00:09,  1.50s/it]
Inference Embeddings:  55%|█████▍    | 6/11 [00:10<00:06,  1.31s/it]
Inference Embeddings:  64%|██████▎   | 7/11 [00:11<00:04,  1.17s/it]
Inference Embeddings:  73%|███████▎  | 8/11 [00:12<00:03,  1.08s/it]
Inference Embeddings:  82%|████████▏ | 9/11 [00:12<00:01,  1.05it/s]
Inference Embeddings:  91%|█████████ | 10/11 [00:13<00:00,  1.21it/s]
Inference Embeddings: 100%|██████████| 11/11 [00:13<00:00,  1.26s/it]

pre tokenize:   0%|          | 0/5 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 5/5 [00:00<00:00, 12.85it/s]

Inference Embeddings:   0%|          | 0/5 [00:00<?, ?it/s]
Inference Embeddings:  20%|██        | 1/5 [00:03<00:14,  3.67s/it]
Inference Embeddings:  40%|████      | 2/5 [00:04<00:06,  2.15s/it]
Inference Embeddings:  60%|██████    | 3/5 [00:05<00:03,  1.56s/it]
Inference Embeddings:  80%|████████  | 4/5 [00:06<00:01,  1.20s/it]
Inference Embeddings: 100%|██████████| 5/5 [00:06<00:00,  1.28s/it]

pre tokenize: 100%|██████████| 5/5 [00:00<00:00, 110.37it/s]

Inference Embeddings:   0%|          | 0/5 [00:00<?, ?it/s]
Inference Embeddings:  20%|██        | 1/5 [00:03<00:12,  3.17s/it]
Inference Embeddings:  40%|████      | 2/5 [00:03<00:05,  1.70s/it]
Inference Embeddings:  60%|██████    | 3/5 [00:04<00:02,  1.17s/it]
Inference Embeddings:  80%|████████  | 4/5 [00:04<00:00,  1.13it/s]
Inference Embeddings: 100%|██████████| 5/5 [00:05<00:00,  1.03s/it]

pre tokenize: 100%|██████████| 2/2 [00:00<00:00, 155.26it/s]

Inference Embeddings:   0%|          | 0/2 [00:00<?, ?it/s]
Inference Embeddings: 100%|██████████| 2/2 [00:03<00:00,  1.53s/it]

pre tokenize: 100%|██████████| 4/4 [00:00<00:00, 70.40it/s]

Inference Embeddings:   0%|          | 0/4 [00:00<?, ?it/s]
Inference Embeddings:  25%|██▌       | 1/4 [00:04<00:12,  4.11s/it]
Inference Embeddings:  50%|█████     | 2/4 [00:05<00:04,  2.25s/it]
Inference Embeddings:  75%|███████▌  | 3/4 [00:05<00:01,  1.57s/it]
Inference Embeddings: 100%|██████████| 4/4 [00:06<00:00,  1.62s/it]

pre tokenize: 100%|██████████| 2/2 [00:00<00:00, 81.40it/s]

Inference Embeddings:   0%|          | 0/2 [00:00<?, ?it/s]
Inference Embeddings:  50%|█████     | 1/2 [00:03<00:03,  3.86s/it]
Inference Embeddings: 100%|██████████| 2/2 [00:04<00:00,  2.08s/it]

pre tokenize: 100%|██████████| 2/2 [00:00<00:00, 52.45it/s]

Inference Embeddings:   0%|          | 0/2 [00:00<?, ?it/s]
Inference Embeddings:  50%|█████     | 1/2 [00:03<00:03,  3.26s/it]
Inference Embeddings: 100%|██████████| 2/2 [00:03<00:00,  1.85s/it]

pre tokenize:   0%|          | 0/6 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 6/6 [00:00<00:00, 32.28it/s]

Inference Embeddings:   0%|          | 0/6 [00:00<?, ?it/s]
Inference Embeddings:  17%|█▋        | 1/6 [00:04<00:21,  4.21s/it]
Inference Embeddings:  33%|███▎      | 2/6 [00:05<00:10,  2.68s/it]
Inference Embeddings:  50%|█████     | 3/6 [00:07<00:06,  2.08s/it]
Inference Embeddings:  67%|██████▋   | 4/6 [00:08<00:03,  1.72s/it]
Inference Embeddings:  83%|████████▎ | 5/6 [00:09<00:01,  1.44s/it]
Inference Embeddings: 100%|██████████| 6/6 [00:09<00:00,  1.62s/it]

pre tokenize:   0%|          | 0/9 [00:00<?, ?it/s]
pre tokenize:  44%|████▍     | 4/9 [00:00<00:00, 32.97it/s]
pre tokenize: 100%|██████████| 9/9 [00:00<00:00, 34.93it/s]

Inference Embeddings:   0%|          | 0/9 [00:00<?, ?it/s]
Inference Embeddings:  11%|█         | 1/9 [00:03<00:29,  3.71s/it]
Inference Embeddings:  22%|██▏       | 2/9 [00:04<00:15,  2.26s/it]
Inference Embeddings:  33%|███▎      | 3/9 [00:06<00:10,  1.74s/it]
Inference Embeddings:  44%|████▍     | 4/9 [00:06<00:06,  1.40s/it]
Inference Embeddings:  56%|█████▌    | 5/9 [00:07<00:04,  1.21s/it]
Inference Embeddings:  67%|██████▋   | 6/9 [00:08<00:03,  1.05s/it]
Inference Embeddings:  78%|███████▊  | 7/9 [00:09<00:01,  1.06it/s]
Inference Embeddings:  89%|████████▉ | 8/9 [00:09<00:00,  1.23it/s]
Inference Embeddings: 100%|██████████| 9/9 [00:10<00:00,  1.12s/it]

18672
4640

In [ ]:
for method in ("greedy", "periti_2024", "periti_2025"):
    print(method)
    new_dir = os.path.join(eng_path, f"{method}-clustered-freq/")
    os.makedirs(new_dir, exist_ok=True)

    data1, data2 = cluster(method, eng_path)
    data1["2"] = data1["labels"]
    data1 = data1[["0", "1", "2"]]
    data1.to_csv(f"{new_dir}english-corpus1.tsv.gz", sep='\t', index=False, compression="gzip")

    data2["2"] = data2["labels"]
    data2 = data2[["0", "1", "2"]]
    data2.to_csv(f"{new_dir}english-corpus2.tsv.gz", sep='\t', index=False, compression="gzip")

greedy
      0                                                  1  \
0  part  Most of the asp * ing men of that part of Alab...
1  face  The faces are umajured , except that the color...
2   tip  The moon was in its western field , white and ...
3  tree  The well known fact that we may have a hundred...
4  face  Rising upon the instant in his stirrups , the ...

                                                   2
0              A portion ; some portion ; a section.
1                   The front surface of a painting.
2                  To cover the top of ; to overlay.
3  A plant that bears a given fruit or seed ; spe...
4  The front of the skull, especially the front o...

  0%|          | 0/37 [00:00<?, ?it/s]

pre tokenize: 100%|██████████| 4/4 [00:00<00:00, 108.94it/s]

Inference Embeddings:   0%|          | 0/4 [00:00<?, ?it/s]
Inference Embeddings:  25%|██▌       | 1/4 [00:03<00:09,  3.07s/it]
Inference Embeddings:  50%|█████     | 2/4 [00:03<00:03,  1.72s/it]
Inference Embeddings:  75%|███████▌  | 3/4 [00:04<00:01,  1.23s/it]
Inference Embeddings: 100%|██████████| 4/4 [00:04<00:00,  1.16s/it]

pre tokenize: 100%|██████████| 4/4 [00:00<00:00, 98.42it/s]

Inference Embeddings:   0%|          | 0/4 [00:00<?, ?it/s]
Inference Embeddings:  25%|██▌       | 1/4 [00:03<00:10,  3.63s/it]
Inference Embeddings:  50%|█████     | 2/4 [00:04<00:04,  2.02s/it]
Inference Embeddings:  75%|███████▌  | 3/4 [00:05<00:01,  1.41s/it]
Inference Embeddings: 100%|██████████| 4/4 [00:05<00:00,  1.34s/it]

pre tokenize: 100%|██████████| 4/4 [00:00<00:00, 54.91it/s]

Inference Embeddings:   0%|          | 0/4 [00:00<?, ?it/s]
Inference Embeddings:  25%|██▌       | 1/4 [00:03<00:11,  3.67s/it]
Inference Embeddings:  50%|█████     | 2/4 [00:04<00:03,  1.99s/it]
Inference Embeddings:  75%|███████▌  | 3/4 [00:05<00:01,  1.39s/it]
Inference Embeddings: 100%|██████████| 4/4 [00:05<00:00,  1.37s/it]

pre tokenize: 100%|██████████| 3/3 [00:00<00:00, 132.63it/s]

Inference Embeddings:   0%|          | 0/3 [00:00<?, ?it/s]
Inference Embeddings:  33%|███▎      | 1/3 [00:03<00:07,  3.66s/it]
Inference Embeddings:  67%|██████▋   | 2/3 [00:04<00:01,  1.81s/it]
Inference Embeddings: 100%|██████████| 3/3 [00:04<00:00,  1.45s/it]

pre tokenize: 100%|██████████| 2/2 [00:00<00:00, 105.98it/s]

Inference Embeddings:   0%|          | 0/2 [00:00<?, ?it/s]
Inference Embeddings: 100%|██████████| 2/2 [00:02<00:00,  1.12s/it]

pre tokenize: 100%|██████████| 4/4 [00:00<00:00, 94.74it/s]

Inference Embeddings:   0%|          | 0/4 [00:00<?, ?it/s]
Inference Embeddings:  25%|██▌       | 1/4 [00:03<00:09,  3.13s/it]
Inference Embeddings:  50%|█████     | 2/4 [00:03<00:03,  1.79s/it]
Inference Embeddings:  75%|███████▌  | 3/4 [00:04<00:01,  1.26s/it]
Inference Embeddings: 100%|██████████| 4/4 [00:05<00:00,  1.29s/it]

pre tokenize:   0%|          | 0/9 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 9/9 [00:00<00:00, 44.03it/s]

Inference Embeddings:   0%|          | 0/9 [00:00<?, ?it/s]
Inference Embeddings:  11%|█         | 1/9 [00:03<00:29,  3.63s/it]
Inference Embeddings:  22%|██▏       | 2/9 [00:04<00:15,  2.28s/it]
Inference Embeddings:  33%|███▎      | 3/9 [00:06<00:10,  1.72s/it]
Inference Embeddings:  44%|████▍     | 4/9 [00:06<00:07,  1.42s/it]
Inference Embeddings:  56%|█████▌    | 5/9 [00:07<00:04,  1.22s/it]
Inference Embeddings:  67%|██████▋   | 6/9 [00:08<00:03,  1.05s/it]
Inference Embeddings:  78%|███████▊  | 7/9 [00:09<00:01,  1.08it/s]
Inference Embeddings:  89%|████████▉ | 8/9 [00:09<00:00,  1.25it/s]
Inference Embeddings: 100%|██████████| 9/9 [00:10<00:00,  1.13s/it]

pre tokenize: 100%|██████████| 2/2 [00:00<00:00, 51.46it/s]

Inference Embeddings:   0%|          | 0/2 [00:00<?, ?it/s]
Inference Embeddings:  50%|█████     | 1/2 [00:04<00:04,  4.28s/it]
Inference Embeddings: 100%|██████████| 2/2 [00:04<00:00,  2.36s/it]

pre tokenize: 100%|██████████| 3/3 [00:00<00:00, 65.20it/s]

Inference Embeddings:   0%|          | 0/3 [00:00<?, ?it/s]
Inference Embeddings:  33%|███▎      | 1/3 [00:04<00:09,  4.56s/it]
Inference Embeddings:  67%|██████▋   | 2/3 [00:05<00:02,  2.58s/it]
Inference Embeddings: 100%|██████████| 3/3 [00:06<00:00,  2.20s/it]

pre tokenize:   0%|          | 0/20 [00:00<?, ?it/s]
pre tokenize:  25%|██▌       | 5/20 [00:00<00:00, 47.57it/s]
pre tokenize:  50%|█████     | 10/20 [00:00<00:00, 43.94it/s]
pre tokenize:  75%|███████▌  | 15/20 [00:00<00:00, 42.05it/s]
pre tokenize: 100%|██████████| 20/20 [00:00<00:00, 42.45it/s]

Inference Embeddings:   0%|          | 0/20 [00:00<?, ?it/s]
Inference Embeddings:   5%|▌         | 1/20 [00:04<01:29,  4.70s/it]
Inference Embeddings:  10%|█         | 2/20 [00:06<00:55,  3.07s/it]
Inference Embeddings:  15%|█▌        | 3/20 [00:08<00:40,  2.36s/it]
Inference Embeddings:  20%|██        | 4/20 [00:09<00:31,  1.96s/it]
Inference Embeddings:  25%|██▌       | 5/20 [00:10<00:25,  1.72s/it]
Inference Embeddings:  30%|███       | 6/20 [00:11<00:21,  1.54s/it]
Inference Embeddings:  35%|███▌      | 7/20 [00:13<00:18,  1.41s/it]
Inference Embeddings:  40%|████      | 8/20 [00:14<00:15,  1.32s/it]
Inference Embeddings:  45%|████▌     | 9/20 [00:15<00:13,  1.27s/it]
Inference Embeddings:  50%|█████     | 10/20 [00:16<00:11,  1.18s/it]
Inference Embeddings:  55%|█████▌    | 11/20 [00:17<00:09,  1.10s/it]
Inference Embeddings:  60%|██████    | 12/20 [00:18<00:08,  1.04s/it]
Inference Embeddings:  65%|██████▌   | 13/20 [00:19<00:07,  1.00s/it]
Inference Embeddings:  70%|███████   | 14/20 [00:19<00:05,  1.07it/s]
Inference Embeddings:  75%|███████▌  | 15/20 [00:20<00:04,  1.16it/s]
Inference Embeddings:  80%|████████  | 16/20 [00:21<00:03,  1.21it/s]
Inference Embeddings:  85%|████████▌ | 17/20 [00:21<00:02,  1.34it/s]
Inference Embeddings:  90%|█████████ | 18/20 [00:22<00:01,  1.47it/s]
Inference Embeddings:  95%|█████████▌| 19/20 [00:22<00:00,  1.63it/s]
Inference Embeddings: 100%|██████████| 20/20 [00:23<00:00,  1.16s/it]

pre tokenize:   0%|          | 0/11 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 11/11 [00:00<00:00, 79.05it/s]

Inference Embeddings:   0%|          | 0/11 [00:00<?, ?it/s]
Inference Embeddings:   9%|▉         | 1/11 [00:03<00:36,  3.70s/it]
Inference Embeddings:  18%|█▊        | 2/11 [00:05<00:21,  2.37s/it]
Inference Embeddings:  27%|██▋       | 3/11 [00:06<00:14,  1.85s/it]
Inference Embeddings:  36%|███▋      | 4/11 [00:07<00:10,  1.55s/it]
Inference Embeddings:  45%|████▌     | 5/11 [00:08<00:08,  1.34s/it]
Inference Embeddings:  55%|█████▍    | 6/11 [00:09<00:05,  1.18s/it]
Inference Embeddings:  64%|██████▎   | 7/11 [00:10<00:04,  1.09s/it]
Inference Embeddings:  73%|███████▎  | 8/11 [00:10<00:02,  1.03it/s]
Inference Embeddings:  82%|████████▏ | 9/11 [00:11<00:01,  1.11it/s]
Inference Embeddings: 100%|██████████| 11/11 [00:12<00:00,  1.11s/it]

pre tokenize: 100%|██████████| 2/2 [00:00<00:00, 137.60it/s]

Inference Embeddings:   0%|          | 0/2 [00:00<?, ?it/s]
Inference Embeddings: 100%|██████████| 2/2 [00:03<00:00,  1.97s/it]

pre tokenize: 100%|██████████| 2/2 [00:00<00:00, 119.86it/s]

Inference Embeddings:   0%|          | 0/2 [00:00<?, ?it/s]
Inference Embeddings: 100%|██████████| 2/2 [00:04<00:00,  2.12s/it]

pre tokenize: 100%|██████████| 10/10 [00:00<00:00, 111.25it/s]

Inference Embeddings:   0%|          | 0/10 [00:00<?, ?it/s]
Inference Embeddings:  10%|█         | 1/10 [00:03<00:34,  3.81s/it]
Inference Embeddings:  20%|██        | 2/10 [00:04<00:16,  2.11s/it]
Inference Embeddings:  30%|███       | 3/10 [00:05<00:10,  1.46s/it]
Inference Embeddings:  40%|████      | 4/10 [00:06<00:07,  1.18s/it]
Inference Embeddings:  50%|█████     | 5/10 [00:06<00:04,  1.04it/s]
Inference Embeddings:  60%|██████    | 6/10 [00:07<00:03,  1.23it/s]
Inference Embeddings:  70%|███████   | 7/10 [00:07<00:02,  1.43it/s]
Inference Embeddings:  80%|████████  | 8/10 [00:08<00:01,  1.59it/s]
Inference Embeddings:  90%|█████████ | 9/10 [00:08<00:00,  1.78it/s]
Inference Embeddings: 100%|██████████| 10/10 [00:08<00:00,  1.11it/s]

pre tokenize: 100%|██████████| 2/2 [00:00<00:00, 77.66it/s]

Inference Embeddings:   0%|          | 0/2 [00:00<?, ?it/s]
Inference Embeddings:  50%|█████     | 1/2 [00:04<00:04,  4.08s/it]
Inference Embeddings: 100%|██████████| 2/2 [00:04<00:00,  2.22s/it]

pre tokenize: 100%|██████████| 2/2 [00:00<00:00, 57.41it/s]

Inference Embeddings:   0%|          | 0/2 [00:00<?, ?it/s]
Inference Embeddings:  50%|█████     | 1/2 [00:03<00:03,  3.05s/it]
Inference Embeddings: 100%|██████████| 2/2 [00:03<00:00,  1.61s/it]

pre tokenize: 100%|██████████| 2/2 [00:00<00:00, 109.38it/s]

Inference Embeddings:   0%|          | 0/2 [00:00<?, ?it/s]
Inference Embeddings:  50%|█████     | 1/2 [00:03<00:03,  3.61s/it]
Inference Embeddings: 100%|██████████| 2/2 [00:03<00:00,  1.90s/it]

pre tokenize:   0%|          | 0/6 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 6/6 [00:00<00:00, 42.48it/s]

Inference Embeddings:   0%|          | 0/6 [00:00<?, ?it/s]
Inference Embeddings:  17%|█▋        | 1/6 [00:04<00:20,  4.10s/it]
Inference Embeddings:  33%|███▎      | 2/6 [00:05<00:09,  2.35s/it]
Inference Embeddings:  50%|█████     | 3/6 [00:06<00:05,  1.68s/it]
Inference Embeddings:  67%|██████▋   | 4/6 [00:06<00:02,  1.30s/it]
Inference Embeddings:  83%|████████▎ | 5/6 [00:07<00:01,  1.07s/it]
Inference Embeddings: 100%|██████████| 6/6 [00:07<00:00,  1.28s/it]

pre tokenize: 100%|██████████| 2/2 [00:00<00:00, 68.42it/s]

Inference Embeddings:   0%|          | 0/2 [00:00<?, ?it/s]
Inference Embeddings:  50%|█████     | 1/2 [00:03<00:03,  3.84s/it]
Inference Embeddings: 100%|██████████| 2/2 [00:04<00:00,  2.22s/it]

pre tokenize: 100%|██████████| 3/3 [00:00<00:00, 48.45it/s]

Inference Embeddings:   0%|          | 0/3 [00:00<?, ?it/s]
Inference Embeddings:  33%|███▎      | 1/3 [00:03<00:06,  3.24s/it]
Inference Embeddings: 100%|██████████| 3/3 [00:04<00:00,  1.40s/it]

pre tokenize: 100%|██████████| 2/2 [00:00<00:00, 94.14it/s]

Inference Embeddings:   0%|          | 0/2 [00:00<?, ?it/s]
Inference Embeddings:  50%|█████     | 1/2 [00:03<00:03,  3.23s/it]
Inference Embeddings: 100%|██████████| 2/2 [00:03<00:00,  1.72s/it]

pre tokenize: 100%|██████████| 2/2 [00:00<00:00, 64.15it/s]

Inference Embeddings:   0%|          | 0/2 [00:00<?, ?it/s]
Inference Embeddings:  50%|█████     | 1/2 [00:03<00:03,  3.21s/it]
Inference Embeddings: 100%|██████████| 2/2 [00:03<00:00,  1.66s/it]

pre tokenize:   0%|          | 0/14 [00:00<?, ?it/s]
pre tokenize:  50%|█████     | 7/14 [00:00<00:00, 60.64it/s]
pre tokenize: 100%|██████████| 14/14 [00:00<00:00, 60.79it/s]

Inference Embeddings:   0%|          | 0/14 [00:00<?, ?it/s]
Inference Embeddings:   7%|▋         | 1/14 [00:04<00:57,  4.42s/it]
Inference Embeddings:  14%|█▍        | 2/14 [00:06<00:33,  2.78s/it]
Inference Embeddings:  21%|██▏       | 3/14 [00:07<00:24,  2.20s/it]
Inference Embeddings:  29%|██▊       | 4/14 [00:09<00:19,  1.91s/it]
Inference Embeddings:  36%|███▌      | 5/14 [00:10<00:15,  1.73s/it]
Inference Embeddings:  43%|████▎     | 6/14 [00:11<00:12,  1.58s/it]
Inference Embeddings:  50%|█████     | 7/14 [00:13<00:10,  1.51s/it]
Inference Embeddings:  57%|█████▋    | 8/14 [00:14<00:08,  1.41s/it]
Inference Embeddings:  64%|██████▍   | 9/14 [00:15<00:06,  1.30s/it]
Inference Embeddings:  71%|███████▏  | 10/14 [00:16<00:04,  1.24s/it]
Inference Embeddings:  79%|███████▊  | 11/14 [00:17<00:03,  1.15s/it]
Inference Embeddings:  86%|████████▌ | 12/14 [00:18<00:02,  1.07s/it]
Inference Embeddings:  93%|█████████▎| 13/14 [00:19<00:00,  1.03it/s]
Inference Embeddings: 100%|██████████| 14/14 [00:19<00:00,  1.37s/it]

pre tokenize:   0%|          | 0/19 [00:00<?, ?it/s]
pre tokenize:  42%|████▏     | 8/19 [00:00<00:00, 75.97it/s]
pre tokenize: 100%|██████████| 19/19 [00:00<00:00, 76.38it/s]

Inference Embeddings:   0%|          | 0/19 [00:00<?, ?it/s]
Inference Embeddings:   5%|▌         | 1/19 [00:04<01:18,  4.36s/it]
Inference Embeddings:  11%|█         | 2/19 [00:05<00:46,  2.73s/it]
Inference Embeddings:  16%|█▌        | 3/19 [00:07<00:33,  2.10s/it]
Inference Embeddings:  21%|██        | 4/19 [00:08<00:25,  1.73s/it]
Inference Embeddings:  26%|██▋       | 5/19 [00:09<00:20,  1.50s/it]
Inference Embeddings:  32%|███▏      | 6/19 [00:10<00:17,  1.37s/it]
Inference Embeddings:  37%|███▋      | 7/19 [00:11<00:14,  1.24s/it]
Inference Embeddings:  42%|████▏     | 8/19 [00:12<00:12,  1.13s/it]
Inference Embeddings:  47%|████▋     | 9/19 [00:13<00:10,  1.05s/it]
Inference Embeddings:  53%|█████▎    | 10/19 [00:14<00:09,  1.01s/it]
Inference Embeddings:  58%|█████▊    | 11/19 [00:15<00:07,  1.07it/s]
Inference Embeddings:  63%|██████▎   | 12/19 [00:15<00:06,  1.15it/s]
Inference Embeddings:  68%|██████▊   | 13/19 [00:16<00:04,  1.23it/s]
Inference Embeddings:  74%|███████▎  | 14/19 [00:17<00:03,  1.26it/s]
Inference Embeddings:  79%|███████▉  | 15/19 [00:17<00:03,  1.32it/s]
Inference Embeddings:  84%|████████▍ | 16/19 [00:18<00:02,  1.44it/s]
Inference Embeddings:  89%|████████▉ | 17/19 [00:18<00:01,  1.56it/s]
Inference Embeddings: 100%|██████████| 19/19 [00:19<00:00,  1.03s/it]

33065
7119
periti_2024
      0                                                  1  \
0  head  seen a complex and exquisitely balanced polity...
1  head  inculcated doctrines incompatible with the pla...
2  word  , during all this period , once entering those...
3  part  immaturity , and want of experience -- besides...
4  word  immaturity , and want of experience -- besides...

                                                   2
0            A superior or governing body or member.
1  The top of the head of a person, or the upper ...
2  A unit of language that native speakers can id...
3                             A fraction of a whole.
4  A single distinct conceptual unit of language,...

  0%|          | 0/37 [00:00<?, ?it/s]

pre tokenize: 100%|██████████| 4/4 [00:00<00:00, 70.68it/s]

Inference Embeddings:   0%|          | 0/12 [00:00<?, ?it/s]
Inference Embeddings:   8%|▊         | 1/12 [01:20<14:42, 80.20s/it]
Inference Embeddings:  17%|█▋        | 2/12 [01:20<05:32, 33.29s/it]
Inference Embeddings:  25%|██▌       | 3/12 [01:21<02:44, 18.28s/it]
Inference Embeddings:  33%|███▎      | 4/12 [01:21<01:29, 11.19s/it]
Inference Embeddings:  42%|████▏     | 5/12 [01:21<00:50,  7.27s/it]
Inference Embeddings:  50%|█████     | 6/12 [01:21<00:29,  4.89s/it]
Inference Embeddings:  58%|█████▊    | 7/12 [01:22<00:16,  3.38s/it]
Inference Embeddings:  67%|██████▋   | 8/12 [01:22<00:09,  2.37s/it]
Inference Embeddings:  75%|███████▌  | 9/12 [01:22<00:05,  1.70s/it]
Inference Embeddings:  83%|████████▎ | 10/12 [01:22<00:02,  1.24s/it]
Inference Embeddings: 100%|██████████| 12/12 [01:23<00:00,  6.93s/it]

pre tokenize: 100%|██████████| 4/4 [00:00<00:00, 43.05it/s]

Inference Embeddings:   0%|          | 0/4 [00:00<?, ?it/s]
Inference Embeddings:  25%|██▌       | 1/4 [00:08<00:24,  8.28s/it]
Inference Embeddings:  50%|█████     | 2/4 [00:09<00:08,  4.22s/it]
Inference Embeddings:  75%|███████▌  | 3/4 [00:10<00:02,  2.73s/it]
Inference Embeddings: 100%|██████████| 4/4 [00:10<00:00,  2.72s/it]

pre tokenize: 100%|██████████| 4/4 [00:00<00:00, 58.19it/s]

Inference Embeddings:   0%|          | 0/4 [00:00<?, ?it/s]
Inference Embeddings:  25%|██▌       | 1/4 [00:07<00:21,  7.12s/it]
Inference Embeddings:  50%|█████     | 2/4 [00:08<00:07,  3.59s/it]
Inference Embeddings:  75%|███████▌  | 3/4 [00:08<00:02,  2.25s/it]
Inference Embeddings: 100%|██████████| 4/4 [00:09<00:00,  2.27s/it]

pre tokenize:   0%|          | 0/4 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 4/4 [00:00<00:00, 22.90it/s]

Inference Embeddings:   0%|          | 0/10 [00:00<?, ?it/s]
Inference Embeddings:  10%|█         | 1/10 [01:21<12:10, 81.20s/it]
Inference Embeddings:  20%|██        | 2/10 [01:21<04:30, 33.78s/it]
Inference Embeddings:  30%|███       | 3/10 [01:22<02:10, 18.57s/it]
Inference Embeddings:  40%|████      | 4/10 [01:22<01:08, 11.41s/it]
Inference Embeddings:  50%|█████     | 5/10 [01:23<00:37,  7.42s/it]
Inference Embeddings:  60%|██████    | 6/10 [01:23<00:20,  5.00s/it]
Inference Embeddings:  70%|███████   | 7/10 [01:23<00:10,  3.44s/it]
Inference Embeddings:  80%|████████  | 8/10 [01:23<00:04,  2.41s/it]
Inference Embeddings:  90%|█████████ | 9/10 [01:23<00:01,  1.71s/it]
Inference Embeddings: 100%|██████████| 10/10 [01:24<00:00,  8.41s/it]

pre tokenize: 100%|██████████| 2/2 [00:00<00:00, 81.63it/s]

Inference Embeddings:   0%|          | 0/2 [00:00<?, ?it/s]
Inference Embeddings:  50%|█████     | 1/2 [00:05<00:05,  5.12s/it]
Inference Embeddings: 100%|██████████| 2/2 [00:05<00:00,  2.77s/it]

Inference Embeddings:   0%|          | 0/3 [00:00<?, ?it/s]
Inference Embeddings:  33%|███▎      | 1/3 [01:19<02:39, 79.51s/it]
Inference Embeddings: 100%|██████████| 3/3 [01:19<00:00, 26.63s/it]

pre tokenize: 100%|██████████| 4/4 [00:00<00:00, 53.69it/s]

Inference Embeddings:   0%|          | 0/4 [00:00<?, ?it/s]
Inference Embeddings:  25%|██▌       | 1/4 [00:04<00:12,  4.28s/it]
Inference Embeddings:  50%|█████     | 2/4 [00:05<00:04,  2.31s/it]
Inference Embeddings:  75%|███████▌  | 3/4 [00:05<00:01,  1.56s/it]
Inference Embeddings: 100%|██████████| 4/4 [00:06<00:00,  1.55s/it]

pre tokenize:   0%|          | 0/12 [00:00<?, ?it/s]
pre tokenize:  50%|█████     | 6/12 [00:00<00:00, 50.61it/s]
pre tokenize: 100%|██████████| 12/12 [00:00<00:00, 39.88it/s]

Inference Embeddings:   0%|          | 0/36 [00:00<?, ?it/s]
Inference Embeddings:   3%|▎         | 1/36 [01:21<47:21, 81.18s/it]
Inference Embeddings:   6%|▌         | 2/36 [01:22<19:13, 33.94s/it]
Inference Embeddings:   8%|▊         | 3/36 [01:22<10:22, 18.86s/it]
Inference Embeddings:  11%|█         | 4/36 [01:23<06:15, 11.74s/it]
Inference Embeddings:  14%|█▍        | 5/36 [01:24<04:01,  7.78s/it]
Inference Embeddings:  17%|█▋        | 6/36 [01:25<02:40,  5.36s/it]
Inference Embeddings:  19%|█▉        | 7/36 [01:25<01:51,  3.84s/it]
Inference Embeddings:  22%|██▏       | 8/36 [01:26<01:19,  2.82s/it]
Inference Embeddings:  25%|██▌       | 9/36 [01:27<00:56,  2.11s/it]
Inference Embeddings:  28%|██▊       | 10/36 [01:27<00:42,  1.64s/it]
Inference Embeddings:  31%|███       | 11/36 [01:28<00:32,  1.29s/it]
Inference Embeddings:  33%|███▎      | 12/36 [01:28<00:25,  1.05s/it]
Inference Embeddings:  36%|███▌      | 13/36 [01:29<00:19,  1.15it/s]
Inference Embeddings:  39%|███▉      | 14/36 [01:29<00:16,  1.33it/s]
Inference Embeddings:  42%|████▏     | 15/36 [01:30<00:14,  1.50it/s]
Inference Embeddings:  44%|████▍     | 16/36 [01:30<00:12,  1.66it/s]
Inference Embeddings:  47%|████▋     | 17/36 [01:31<00:10,  1.80it/s]
Inference Embeddings:  50%|█████     | 18/36 [01:31<00:09,  1.97it/s]
Inference Embeddings:  53%|█████▎    | 19/36 [01:31<00:08,  2.08it/s]
Inference Embeddings:  56%|█████▌    | 20/36 [01:32<00:07,  2.17it/s]
Inference Embeddings:  58%|█████▊    | 21/36 [01:32<00:06,  2.37it/s]
Inference Embeddings:  61%|██████    | 22/36 [01:32<00:05,  2.49it/s]
Inference Embeddings:  64%|██████▍   | 23/36 [01:33<00:05,  2.57it/s]
Inference Embeddings:  67%|██████▋   | 24/36 [01:33<00:04,  2.66it/s]
Inference Embeddings:  69%|██████▉   | 25/36 [01:33<00:03,  2.77it/s]
Inference Embeddings:  72%|███████▏  | 26/36 [01:34<00:03,  2.89it/s]
Inference Embeddings:  75%|███████▌  | 27/36 [01:34<00:02,  3.07it/s]
Inference Embeddings:  78%|███████▊  | 28/36 [01:34<00:02,  3.19it/s]
Inference Embeddings:  81%|████████  | 29/36 [01:35<00:02,  3.48it/s]
Inference Embeddings:  83%|████████▎ | 30/36 [01:35<00:01,  3.69it/s]
Inference Embeddings:  86%|████████▌ | 31/36 [01:35<00:01,  3.85it/s]
Inference Embeddings:  89%|████████▉ | 32/36 [01:35<00:00,  4.09it/s]
Inference Embeddings:  92%|█████████▏| 33/36 [01:35<00:00,  4.43it/s]
Inference Embeddings:  94%|█████████▍| 34/36 [01:36<00:00,  4.87it/s]
Inference Embeddings: 100%|██████████| 36/36 [01:36<00:00,  2.67s/it]

pre tokenize: 100%|██████████| 3/3 [00:00<00:00, 78.40it/s]

Inference Embeddings:   0%|          | 0/3 [00:00<?, ?it/s]
Inference Embeddings:  33%|███▎      | 1/3 [00:05<00:11,  5.98s/it]
Inference Embeddings:  67%|██████▋   | 2/3 [00:07<00:03,  3.10s/it]
Inference Embeddings: 100%|██████████| 3/3 [00:07<00:00,  2.43s/it]

pre tokenize:   0%|          | 0/11 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 11/11 [00:00<00:00, 44.75it/s]

Inference Embeddings:   0%|          | 0/33 [00:00<?, ?it/s]
Inference Embeddings:   3%|▎         | 1/33 [01:21<43:15, 81.10s/it]
Inference Embeddings:   6%|▌         | 2/33 [01:21<17:29, 33.84s/it]
Inference Embeddings:   9%|▉         | 3/33 [01:22<09:21, 18.73s/it]
Inference Embeddings:  12%|█▏        | 4/33 [01:23<05:36, 11.61s/it]
Inference Embeddings:  15%|█▌        | 5/33 [01:23<03:33,  7.62s/it]
Inference Embeddings:  18%|█▊        | 6/33 [01:24<02:21,  5.23s/it]
Inference Embeddings:  21%|██        | 7/33 [01:24<01:35,  3.68s/it]
Inference Embeddings:  24%|██▍       | 8/33 [01:25<01:06,  2.65s/it]
Inference Embeddings:  27%|██▋       | 9/33 [01:25<00:47,  1.97s/it]
Inference Embeddings:  30%|███       | 10/33 [01:26<00:34,  1.50s/it]
Inference Embeddings:  33%|███▎      | 11/33 [01:26<00:25,  1.17s/it]
Inference Embeddings:  36%|███▋      | 12/33 [01:27<00:19,  1.06it/s]
Inference Embeddings:  39%|███▉      | 13/33 [01:27<00:15,  1.32it/s]
Inference Embeddings:  42%|████▏     | 14/33 [01:27<00:12,  1.57it/s]
Inference Embeddings:  45%|████▌     | 15/33 [01:28<00:09,  1.81it/s]
Inference Embeddings:  48%|████▊     | 16/33 [01:28<00:08,  2.05it/s]
Inference Embeddings:  52%|█████▏    | 17/33 [01:28<00:07,  2.28it/s]
Inference Embeddings:  55%|█████▍    | 18/33 [01:29<00:06,  2.49it/s]
Inference Embeddings:  58%|█████▊    | 19/33 [01:29<00:05,  2.76it/s]
Inference Embeddings:  61%|██████    | 20/33 [01:29<00:04,  2.97it/s]
Inference Embeddings:  64%|██████▎   | 21/33 [01:29<00:03,  3.29it/s]
Inference Embeddings:  67%|██████▋   | 22/33 [01:30<00:03,  3.56it/s]
Inference Embeddings:  70%|██████▉   | 23/33 [01:30<00:02,  3.77it/s]
Inference Embeddings:  73%|███████▎  | 24/33 [01:30<00:02,  3.92it/s]
Inference Embeddings:  76%|███████▌  | 25/33 [01:30<00:01,  4.16it/s]
Inference Embeddings:  79%|███████▉  | 26/33 [01:31<00:01,  4.35it/s]
Inference Embeddings:  82%|████████▏ | 27/33 [01:31<00:01,  4.54it/s]
Inference Embeddings:  85%|████████▍ | 28/33 [01:31<00:01,  4.80it/s]
Inference Embeddings:  88%|████████▊ | 29/33 [01:31<00:00,  5.01it/s]
Inference Embeddings:  91%|█████████ | 30/33 [01:31<00:00,  5.35it/s]
Inference Embeddings:  94%|█████████▍| 31/33 [01:31<00:00,  5.67it/s]
Inference Embeddings: 100%|██████████| 33/33 [01:32<00:00,  2.79s/it]

pre tokenize:   0%|          | 0/8 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 8/8 [00:00<00:00, 55.17it/s]

Inference Embeddings:   0%|          | 0/24 [00:00<?, ?it/s]
Inference Embeddings:   4%|▍         | 1/24 [01:20<30:47, 80.33s/it]
Inference Embeddings:   8%|▊         | 2/24 [01:21<12:16, 33.49s/it]
Inference Embeddings:  12%|█▎        | 3/24 [01:21<06:27, 18.46s/it]
Inference Embeddings:  17%|█▋        | 4/24 [01:22<03:47, 11.36s/it]
Inference Embeddings:  21%|██        | 5/24 [01:22<02:21,  7.42s/it]
Inference Embeddings:  25%|██▌       | 6/24 [01:22<01:30,  5.03s/it]
Inference Embeddings:  29%|██▉       | 7/24 [01:23<00:59,  3.52s/it]
Inference Embeddings:  33%|███▎      | 8/24 [01:23<00:40,  2.51s/it]
Inference Embeddings:  38%|███▊      | 9/24 [01:24<00:27,  1.83s/it]
Inference Embeddings:  42%|████▏     | 10/24 [01:24<00:19,  1.37s/it]
Inference Embeddings:  46%|████▌     | 11/24 [01:24<00:13,  1.05s/it]
Inference Embeddings:  50%|█████     | 12/24 [01:24<00:09,  1.21it/s]
Inference Embeddings:  54%|█████▍    | 13/24 [01:25<00:07,  1.49it/s]
Inference Embeddings:  58%|█████▊    | 14/24 [01:25<00:05,  1.82it/s]
Inference Embeddings:  62%|██████▎   | 15/24 [01:25<00:04,  2.14it/s]
Inference Embeddings:  67%|██████▋   | 16/24 [01:26<00:03,  2.54it/s]
Inference Embeddings:  71%|███████   | 17/24 [01:26<00:02,  2.90it/s]
Inference Embeddings:  75%|███████▌  | 18/24 [01:26<00:01,  3.22it/s]
Inference Embeddings:  79%|███████▉  | 19/24 [01:26<00:01,  3.59it/s]
Inference Embeddings:  83%|████████▎ | 20/24 [01:26<00:01,  3.90it/s]
Inference Embeddings:  88%|████████▊ | 21/24 [01:27<00:00,  4.30it/s]
Inference Embeddings:  92%|█████████▏| 22/24 [01:27<00:00,  4.77it/s]
Inference Embeddings:  96%|█████████▌| 23/24 [01:27<00:00,  5.21it/s]
Inference Embeddings: 100%|██████████| 24/24 [01:27<00:00,  3.65s/it]

pre tokenize: 100%|██████████| 2/2 [00:00<00:00, 43.47it/s]

Inference Embeddings:   0%|          | 0/4 [00:00<?, ?it/s]
Inference Embeddings:  25%|██▌       | 1/4 [01:19<03:58, 79.67s/it]
Inference Embeddings:  50%|█████     | 2/4 [01:20<01:06, 33.30s/it]
Inference Embeddings:  75%|███████▌  | 3/4 [01:21<00:18, 18.32s/it]
Inference Embeddings: 100%|██████████| 4/4 [01:21<00:00, 20.28s/it]

pre tokenize:   0%|          | 0/18 [00:00<?, ?it/s]
pre tokenize:  33%|███▎      | 6/18 [00:00<00:00, 57.52it/s]
pre tokenize: 100%|██████████| 18/18 [00:00<00:00, 44.61it/s]

Inference Embeddings:   0%|          | 0/55 [00:00<?, ?it/s]
Inference Embeddings:   2%|▏         | 1/55 [01:20<1:12:51, 80.96s/it]
Inference Embeddings:   4%|▎         | 2/55 [01:21<29:49, 33.77s/it]
Inference Embeddings:   5%|▌         | 3/55 [01:22<16:07, 18.60s/it]
Inference Embeddings:   7%|▋         | 4/55 [01:22<09:45, 11.49s/it]
Inference Embeddings:   9%|▉         | 5/55 [01:23<06:16,  7.53s/it]
Inference Embeddings:  11%|█         | 6/55 [01:23<04:12,  5.15s/it]
Inference Embeddings:  13%|█▎        | 7/55 [01:24<02:53,  3.62s/it]
Inference Embeddings:  15%|█▍        | 8/55 [01:24<02:03,  2.62s/it]
Inference Embeddings:  16%|█▋        | 9/55 [01:25<01:29,  1.94s/it]
Inference Embeddings:  18%|█▊        | 10/55 [01:25<01:06,  1.48s/it]
Inference Embeddings:  20%|██        | 11/55 [01:26<00:50,  1.15s/it]
Inference Embeddings:  22%|██▏       | 12/55 [01:26<00:39,  1.09it/s]
Inference Embeddings:  24%|██▎       | 13/55 [01:26<00:32,  1.30it/s]
Inference Embeddings:  25%|██▌       | 14/55 [01:27<00:26,  1.58it/s]
Inference Embeddings:  27%|██▋       | 15/55 [01:27<00:21,  1.82it/s]
Inference Embeddings:  29%|██▉       | 16/55 [01:27<00:19,  2.03it/s]
Inference Embeddings:  31%|███       | 17/55 [01:28<00:17,  2.21it/s]
Inference Embeddings:  33%|███▎      | 18/55 [01:28<00:15,  2.39it/s]
Inference Embeddings:  35%|███▍      | 19/55 [01:29<00:14,  2.53it/s]
Inference Embeddings:  36%|███▋      | 20/55 [01:29<00:13,  2.67it/s]
Inference Embeddings:  38%|███▊      | 21/55 [01:29<00:12,  2.78it/s]
Inference Embeddings:  40%|████      | 22/55 [01:29<00:11,  2.90it/s]
Inference Embeddings:  42%|████▏     | 23/55 [01:30<00:10,  2.97it/s]
Inference Embeddings:  44%|████▎     | 24/55 [01:30<00:09,  3.15it/s]
Inference Embeddings:  45%|████▌     | 25/55 [01:30<00:09,  3.29it/s]
Inference Embeddings:  47%|████▋     | 26/55 [01:31<00:08,  3.39it/s]
Inference Embeddings:  49%|████▉     | 27/55 [01:31<00:08,  3.44it/s]
Inference Embeddings:  51%|█████     | 28/55 [01:31<00:07,  3.47it/s]
Inference Embeddings:  53%|█████▎    | 29/55 [01:31<00:07,  3.48it/s]
Inference Embeddings:  55%|█████▍    | 30/55 [01:32<00:06,  3.72it/s]
Inference Embeddings:  56%|█████▋    | 31/55 [01:32<00:06,  3.92it/s]
Inference Embeddings:  58%|█████▊    | 32/55 [01:32<00:05,  4.08it/s]
Inference Embeddings:  60%|██████    | 33/55 [01:32<00:05,  4.16it/s]
Inference Embeddings:  62%|██████▏   | 34/55 [01:33<00:04,  4.22it/s]
Inference Embeddings:  64%|██████▎   | 35/55 [01:33<00:04,  4.25it/s]
Inference Embeddings:  65%|██████▌   | 36/55 [01:33<00:04,  4.27it/s]
Inference Embeddings:  67%|██████▋   | 37/55 [01:33<00:04,  4.27it/s]
Inference Embeddings:  69%|██████▉   | 38/55 [01:34<00:03,  4.25it/s]
Inference Embeddings:  71%|███████   | 39/55 [01:34<00:03,  4.42it/s]
Inference Embeddings:  73%|███████▎  | 40/55 [01:34<00:03,  4.54it/s]
Inference Embeddings:  75%|███████▍  | 41/55 [01:34<00:03,  4.63it/s]
Inference Embeddings:  76%|███████▋  | 42/55 [01:34<00:02,  4.67it/s]
Inference Embeddings:  78%|███████▊  | 43/55 [01:35<00:02,  4.78it/s]
Inference Embeddings:  80%|████████  | 44/55 [01:35<00:02,  4.83it/s]
Inference Embeddings:  82%|████████▏ | 45/55 [01:35<00:01,  5.01it/s]
Inference Embeddings:  84%|████████▎ | 46/55 [01:35<00:01,  5.15it/s]
Inference Embeddings:  85%|████████▌ | 47/55 [01:35<00:01,  5.26it/s]
Inference Embeddings:  87%|████████▋ | 48/55 [01:35<00:01,  5.32it/s]
Inference Embeddings:  89%|████████▉ | 49/55 [01:36<00:01,  5.60it/s]
Inference Embeddings:  91%|█████████ | 50/55 [01:36<00:00,  5.87it/s]
Inference Embeddings:  93%|█████████▎| 51/55 [01:36<00:00,  6.08it/s]
Inference Embeddings:  95%|█████████▍| 52/55 [01:36<00:00,  6.23it/s]
Inference Embeddings:  96%|█████████▋| 53/55 [01:36<00:00,  6.74it/s]
Inference Embeddings: 100%|██████████| 55/55 [01:36<00:00,  1.76s/it]

Inference Embeddings:   0%|          | 0/3 [00:00<?, ?it/s]
Inference Embeddings:  33%|███▎      | 1/3 [01:20<02:40, 80.02s/it]
Inference Embeddings:  67%|██████▋   | 2/3 [01:20<00:33, 33.15s/it]
Inference Embeddings: 100%|██████████| 3/3 [01:20<00:00, 26.85s/it]

pre tokenize: 100%|██████████| 2/2 [00:00<00:00, 46.02it/s]

Inference Embeddings:   0%|          | 0/2 [00:00<?, ?it/s]
Inference Embeddings:  50%|█████     | 1/2 [00:26<00:26, 26.06s/it]
Inference Embeddings: 100%|██████████| 2/2 [00:26<00:00, 13.17s/it]

pre tokenize: 100%|██████████| 3/3 [00:00<00:00, 49.38it/s]

Inference Embeddings:   0%|          | 0/3 [00:00<?, ?it/s]
Inference Embeddings:  33%|███▎      | 1/3 [00:04<00:09,  4.90s/it]
Inference Embeddings:  67%|██████▋   | 2/3 [00:05<00:02,  2.54s/it]
Inference Embeddings: 100%|██████████| 3/3 [00:05<00:00,  1.97s/it]

pre tokenize: 100%|██████████| 2/2 [00:00<00:00, 106.29it/s]

Inference Embeddings:   0%|          | 0/2 [00:00<?, ?it/s]
Inference Embeddings:  50%|█████     | 1/2 [00:03<00:03,  3.63s/it]
Inference Embeddings: 100%|██████████| 2/2 [00:03<00:00,  1.87s/it]

pre tokenize:   0%|          | 0/5 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 5/5 [00:00<00:00, 38.70it/s]

Inference Embeddings:   0%|          | 0/5 [00:00<?, ?it/s]
Inference Embeddings:  20%|██        | 1/5 [00:07<00:30,  7.56s/it]
Inference Embeddings:  40%|████      | 2/5 [00:08<00:11,  3.82s/it]
Inference Embeddings:  60%|██████    | 3/5 [00:09<00:04,  2.48s/it]
Inference Embeddings:  80%|████████  | 4/5 [00:10<00:01,  1.77s/it]
Inference Embeddings: 100%|██████████| 5/5 [00:10<00:00,  2.11s/it]

pre tokenize: 100%|██████████| 2/2 [00:00<00:00, 51.63it/s]

Inference Embeddings:   0%|          | 0/2 [00:00<?, ?it/s]
Inference Embeddings:  50%|█████     | 1/2 [00:04<00:04,  4.54s/it]
Inference Embeddings: 100%|██████████| 2/2 [00:04<00:00,  2.49s/it]

pre tokenize: 100%|██████████| 2/2 [00:00<00:00, 85.93it/s]

Inference Embeddings:   0%|          | 0/2 [00:00<?, ?it/s]
Inference Embeddings:  50%|█████     | 1/2 [00:05<00:05,  5.09s/it]
Inference Embeddings: 100%|██████████| 2/2 [00:05<00:00,  2.66s/it]

pre tokenize: 100%|██████████| 2/2 [00:00<00:00, 56.84it/s]

Inference Embeddings:   0%|          | 0/2 [00:00<?, ?it/s]
Inference Embeddings:  50%|█████     | 1/2 [00:05<00:05,  5.36s/it]
Inference Embeddings: 100%|██████████| 2/2 [00:06<00:00,  3.05s/it]

Inference Embeddings:   0%|          | 0/3 [00:00<?, ?it/s]
Inference Embeddings:  33%|███▎      | 1/3 [01:21<02:42, 81.22s/it]
Inference Embeddings:  67%|██████▋   | 2/3 [01:21<00:33, 33.75s/it]
Inference Embeddings: 100%|██████████| 3/3 [01:21<00:00, 27.32s/it]

Inference Embeddings:   0%|          | 0/4 [00:00<?, ?it/s]
Inference Embeddings:  25%|██▌       | 1/4 [01:19<03:58, 79.48s/it]
Inference Embeddings:  50%|█████     | 2/4 [01:19<01:05, 32.93s/it]
Inference Embeddings: 100%|██████████| 4/4 [01:20<00:00, 20.02s/it]

pre tokenize:   0%|          | 0/11 [00:00<?, ?it/s]
pre tokenize:  27%|██▋       | 3/11 [00:00<00:00, 29.97it/s]
pre tokenize:  64%|██████▎   | 7/11 [00:00<00:00, 31.42it/s]
pre tokenize: 100%|██████████| 11/11 [00:00<00:00, 32.83it/s]

Inference Embeddings:   0%|          | 0/11 [00:00<?, ?it/s]
Inference Embeddings:   9%|▉         | 1/11 [00:14<02:25, 14.54s/it]
Inference Embeddings:  18%|█▊        | 2/11 [00:16<01:02,  6.99s/it]
Inference Embeddings:  27%|██▋       | 3/11 [00:17<00:35,  4.50s/it]
Inference Embeddings:  36%|███▋      | 4/11 [00:19<00:22,  3.27s/it]
Inference Embeddings:  45%|████▌     | 5/11 [00:20<00:15,  2.54s/it]
Inference Embeddings:  55%|█████▍    | 6/11 [00:21<00:10,  2.07s/it]
Inference Embeddings:  64%|██████▎   | 7/11 [00:22<00:07,  1.76s/it]
Inference Embeddings:  73%|███████▎  | 8/11 [00:23<00:04,  1.50s/it]
Inference Embeddings:  82%|████████▏ | 9/11 [00:24<00:02,  1.31s/it]
Inference Embeddings:  91%|█████████ | 10/11 [00:25<00:01,  1.11s/it]
Inference Embeddings: 100%|██████████| 11/11 [00:25<00:00,  2.31s/it]

pre tokenize:   0%|          | 0/15 [00:00<?, ?it/s]
pre tokenize:  33%|███▎      | 5/15 [00:00<00:00, 49.82it/s]
pre tokenize: 100%|██████████| 15/15 [00:00<00:00, 51.93it/s]

Inference Embeddings:   0%|          | 0/15 [00:00<?, ?it/s]
Inference Embeddings:   7%|▋         | 1/15 [00:18<04:17, 18.37s/it]
Inference Embeddings:  13%|█▎        | 2/15 [00:21<01:59,  9.20s/it]
Inference Embeddings:  20%|██        | 3/15 [00:23<01:12,  6.05s/it]
Inference Embeddings:  27%|██▋       | 4/15 [00:25<00:47,  4.35s/it]
Inference Embeddings:  33%|███▎      | 5/15 [00:26<00:33,  3.37s/it]
Inference Embeddings:  40%|████      | 6/15 [00:28<00:24,  2.70s/it]
Inference Embeddings:  47%|████▋     | 7/15 [00:29<00:17,  2.18s/it]
Inference Embeddings:  53%|█████▎    | 8/15 [00:30<00:12,  1.77s/it]
Inference Embeddings:  60%|██████    | 9/15 [00:31<00:08,  1.50s/it]
Inference Embeddings:  67%|██████▋   | 10/15 [00:31<00:06,  1.24s/it]

30089
7916
periti_2025
      0                                                  1  \
0  head  seen a complex and exquisitely balanced polity...
1  head  inculcated doctrines incompatible with the pla...
2  word  , during all this period , once entering those...
3  word  immaturity , and want of experience -- besides...
4  part  immaturity , and want of experience -- besides...

                                                   2
0                    (Figurative) A leader or chief.
1  (Figurative) The most important part or piece ...
2  The smallest discrete unit of written language...
3    (Obsolete) Something spoken; speech, discourse.
4  (Obsolete) A third; a third part; a share, a p...

  0%|          | 0/37 [00:00<?, ?it/s]

pre tokenize: 100%|██████████| 3/3 [00:00<00:00, 89.39it/s]

Inference Embeddings:   0%|          | 0/3 [00:00<?, ?it/s]
Inference Embeddings:  33%|███▎      | 1/3 [00:06<00:13,  6.58s/it]
Inference Embeddings: 100%|██████████| 3/3 [00:07<00:00,  2.58s/it]

pre tokenize: 100%|██████████| 4/4 [00:00<00:00, 44.74it/s]

Inference Embeddings:   0%|          | 0/4 [00:00<?, ?it/s]
Inference Embeddings:  25%|██▌       | 1/4 [00:07<00:21,  7.33s/it]
Inference Embeddings:  50%|█████     | 2/4 [00:08<00:07,  3.77s/it]
Inference Embeddings:  75%|███████▌  | 3/4 [00:09<00:02,  2.50s/it]
Inference Embeddings: 100%|██████████| 4/4 [00:10<00:00,  2.57s/it]

pre tokenize: 100%|██████████| 4/4 [00:00<00:00, 48.53it/s]

Inference Embeddings:   0%|          | 0/4 [00:00<?, ?it/s]
Inference Embeddings:  25%|██▌       | 1/4 [00:13<00:39, 13.08s/it]
Inference Embeddings:  50%|█████     | 2/4 [00:14<00:12,  6.15s/it]
Inference Embeddings:  75%|███████▌  | 3/4 [00:15<00:03,  3.76s/it]
Inference Embeddings: 100%|██████████| 4/4 [00:15<00:00,  3.90s/it]

pre tokenize: 100%|██████████| 3/3 [00:00<00:00, 65.86it/s]

Inference Embeddings:   0%|          | 0/3 [00:00<?, ?it/s]
Inference Embeddings:  33%|███▎      | 1/3 [00:05<00:10,  5.16s/it]
Inference Embeddings: 100%|██████████| 3/3 [00:06<00:00,  2.03s/it]

pre tokenize: 100%|██████████| 2/2 [00:00<00:00, 109.95it/s]

Inference Embeddings:   0%|          | 0/2 [00:00<?, ?it/s]
Inference Embeddings: 100%|██████████| 2/2 [00:06<00:00,  3.09s/it]

pre tokenize: 100%|██████████| 2/2 [00:00<00:00, 67.23it/s]

Inference Embeddings:   0%|          | 0/2 [00:00<?, ?it/s]
Inference Embeddings:  50%|█████     | 1/2 [00:06<00:06,  6.07s/it]
Inference Embeddings: 100%|██████████| 2/2 [00:07<00:00,  3.52s/it]

pre tokenize: 100%|██████████| 8/8 [00:00<00:00, 86.01it/s]

Inference Embeddings:   0%|          | 0/8 [00:00<?, ?it/s]
Inference Embeddings:  12%|█▎        | 1/8 [00:06<00:43,  6.19s/it]
Inference Embeddings:  25%|██▌       | 2/8 [00:07<00:20,  3.35s/it]
Inference Embeddings:  38%|███▊      | 3/8 [00:08<00:11,  2.34s/it]
Inference Embeddings:  50%|█████     | 4/8 [00:09<00:07,  1.86s/it]
Inference Embeddings:  62%|██████▎   | 5/8 [00:10<00:04,  1.50s/it]
Inference Embeddings:  75%|███████▌  | 6/8 [00:11<00:02,  1.29s/it]
Inference Embeddings:  88%|████████▊ | 7/8 [00:12<00:01,  1.08s/it]
Inference Embeddings: 100%|██████████| 8/8 [00:12<00:00,  1.55s/it]

pre tokenize: 100%|██████████| 2/2 [00:00<00:00, 58.39it/s]

Inference Embeddings:   0%|          | 0/2 [00:00<?, ?it/s]
Inference Embeddings:  50%|█████     | 1/2 [00:10<00:10, 10.01s/it]
Inference Embeddings: 100%|██████████| 2/2 [00:10<00:00,  5.35s/it]

pre tokenize:   0%|          | 0/11 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 11/11 [00:00<00:00, 75.10it/s]

Inference Embeddings:   0%|          | 0/11 [00:00<?, ?it/s]
Inference Embeddings:   9%|▉         | 1/11 [00:06<01:00,  6.03s/it]
Inference Embeddings:  18%|█▊        | 2/11 [00:07<00:30,  3.42s/it]
Inference Embeddings:  27%|██▋       | 3/11 [00:08<00:19,  2.49s/it]
Inference Embeddings:  36%|███▋      | 4/11 [00:10<00:13,  2.00s/it]
Inference Embeddings:  45%|████▌     | 5/11 [00:11<00:10,  1.67s/it]
Inference Embeddings:  55%|█████▍    | 6/11 [00:12<00:07,  1.49s/it]
Inference Embeddings:  64%|██████▎   | 7/11 [00:13<00:05,  1.31s/it]
Inference Embeddings:  73%|███████▎  | 8/11 [00:14<00:03,  1.17s/it]
Inference Embeddings:  82%|████████▏ | 9/11 [00:15<00:02,  1.04s/it]
Inference Embeddings:  91%|█████████ | 10/11 [00:15<00:00,  1.08it/s]
Inference Embeddings: 100%|██████████| 11/11 [00:16<00:00,  1.48s/it]

pre tokenize:   0%|          | 0/10 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 10/10 [00:00<00:00, 62.78it/s]

Inference Embeddings:   0%|          | 0/10 [00:00<?, ?it/s]
Inference Embeddings:  10%|█         | 1/10 [00:08<01:13,  8.17s/it]
Inference Embeddings:  20%|██        | 2/10 [00:09<00:34,  4.37s/it]
Inference Embeddings:  30%|███       | 3/10 [00:11<00:21,  3.04s/it]
Inference Embeddings:  40%|████      | 4/10 [00:12<00:14,  2.36s/it]
Inference Embeddings:  50%|█████     | 5/10 [00:13<00:09,  1.93s/it]
Inference Embeddings:  60%|██████    | 6/10 [00:14<00:06,  1.65s/it]
Inference Embeddings:  70%|███████   | 7/10 [00:15<00:04,  1.43s/it]
Inference Embeddings:  80%|████████  | 8/10 [00:16<00:02,  1.26s/it]
Inference Embeddings:  90%|█████████ | 9/10 [00:17<00:01,  1.11s/it]
Inference Embeddings: 100%|██████████| 10/10 [00:17<00:00,  1.79s/it]

pre tokenize: 100%|██████████| 2/2 [00:00<00:00, 58.30it/s]

Inference Embeddings:   0%|          | 0/2 [00:00<?, ?it/s]
Inference Embeddings: 100%|██████████| 2/2 [00:07<00:00,  3.54s/it]

pre tokenize:   0%|          | 0/12 [00:00<?, ?it/s]
pre tokenize:  33%|███▎      | 4/12 [00:00<00:00, 39.12it/s]
pre tokenize: 100%|██████████| 12/12 [00:00<00:00, 17.33it/s]

Inference Embeddings:   0%|          | 0/12 [00:00<?, ?it/s]
Inference Embeddings:   8%|▊         | 1/12 [00:06<01:15,  6.82s/it]
Inference Embeddings:  17%|█▋        | 2/12 [00:08<00:36,  3.66s/it]
Inference Embeddings:  25%|██▌       | 3/12 [00:09<00:23,  2.57s/it]
Inference Embeddings:  33%|███▎      | 4/12 [00:10<00:15,  1.99s/it]
Inference Embeddings:  42%|████▏     | 5/12 [00:11<00:11,  1.68s/it]
Inference Embeddings:  50%|█████     | 6/12 [00:12<00:08,  1.44s/it]
Inference Embeddings:  58%|█████▊    | 7/12 [00:13<00:06,  1.27s/it]
Inference Embeddings:  67%|██████▋   | 8/12 [00:14<00:04,  1.15s/it]
Inference Embeddings:  75%|███████▌  | 9/12 [00:15<00:03,  1.02s/it]
Inference Embeddings:  83%|████████▎ | 10/12 [00:16<00:01,  1.07it/s]
Inference Embeddings: 100%|██████████| 12/12 [00:16<00:00,  1.39s/it]

pre tokenize: 100%|██████████| 3/3 [00:00<00:00, 33.72it/s]

Inference Embeddings:   0%|          | 0/3 [00:00<?, ?it/s]
Inference Embeddings:  33%|███▎      | 1/3 [00:08<00:16,  8.31s/it]
Inference Embeddings:  67%|██████▋   | 2/3 [00:09<00:04,  4.16s/it]
Inference Embeddings: 100%|██████████| 3/3 [00:09<00:00,  3.32s/it]

pre tokenize: 100%|██████████| 2/2 [00:00<00:00, 67.85it/s]

Inference Embeddings:   0%|          | 0/2 [00:00<?, ?it/s]
Inference Embeddings:  50%|█████     | 1/2 [00:06<00:06,  6.21s/it]
Inference Embeddings: 100%|██████████| 2/2 [00:07<00:00,  3.55s/it]

pre tokenize: 100%|██████████| 3/3 [00:00<00:00, 37.74it/s]

Inference Embeddings:   0%|          | 0/3 [00:00<?, ?it/s]
Inference Embeddings:  33%|███▎      | 1/3 [00:07<00:14,  7.32s/it]
Inference Embeddings:  67%|██████▋   | 2/3 [00:08<00:03,  3.67s/it]
Inference Embeddings: 100%|██████████| 3/3 [00:08<00:00,  2.98s/it]

pre tokenize: 100%|██████████| 2/2 [00:00<00:00, 51.34it/s]

Inference Embeddings:   0%|          | 0/2 [00:00<?, ?it/s]
Inference Embeddings:  50%|█████     | 1/2 [00:14<00:14, 14.09s/it]
Inference Embeddings: 100%|██████████| 2/2 [00:14<00:00,  7.46s/it]

pre tokenize: 100%|██████████| 2/2 [00:00<00:00, 73.73it/s]

Inference Embeddings:   0%|          | 0/2 [00:00<?, ?it/s]
Inference Embeddings: 100%|██████████| 2/2 [00:05<00:00,  3.00s/it]

pre tokenize:   0%|          | 0/7 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 7/7 [00:00<00:00, 57.26it/s]

Inference Embeddings:   0%|          | 0/7 [00:00<?, ?it/s]
Inference Embeddings:  14%|█▍        | 1/7 [00:08<00:50,  8.39s/it]
Inference Embeddings:  29%|██▊       | 2/7 [00:10<00:23,  4.64s/it]
Inference Embeddings:  43%|████▎     | 3/7 [00:11<00:12,  3.22s/it]
Inference Embeddings:  57%|█████▋    | 4/7 [00:13<00:07,  2.47s/it]
Inference Embeddings:  71%|███████▏  | 5/7 [00:14<00:03,  1.97s/it]
Inference Embeddings:  86%|████████▌ | 6/7 [00:15<00:01,  1.60s/it]
Inference Embeddings: 100%|██████████| 7/7 [00:15<00:00,  2.19s/it]

pre tokenize:   0%|          | 0/8 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 8/8 [00:00<00:00, 63.83it/s]

Inference Embeddings:   0%|          | 0/8 [00:00<?, ?it/s]
Inference Embeddings:  12%|█▎        | 1/8 [00:07<00:54,  7.73s/it]
Inference Embeddings:  25%|██▌       | 2/8 [00:09<00:24,  4.12s/it]
Inference Embeddings:  38%|███▊      | 3/8 [00:10<00:14,  2.87s/it]
Inference Embeddings:  50%|█████     | 4/8 [00:11<00:08,  2.17s/it]
Inference Embeddings:  62%|██████▎   | 5/8 [00:12<00:05,  1.74s/it]
Inference Embeddings:  75%|███████▌  | 6/8 [00:13<00:02,  1.44s/it]
Inference Embeddings:  88%|████████▊ | 7/8 [00:14<00:01,  1.26s/it]
Inference Embeddings: 100%|██████████| 8/8 [00:15<00:00,  1.90s/it]

22924
6577

In [ ]:
method = "dpo"
new_dir = os.path.join(eng_path, f"{method}-clustered-freq/")
os.makedirs(new_dir, exist_ok=True)

data1, data2 = cluster(method, eng_path)
data1["2"] = data1["labels"]
data1 = data1[["0", "1", "2"]]
data1.to_csv(f"{new_dir}english-corpus1.tsv.gz", sep='\t', index=False, compression="gzip")

data2["2"] = data2["labels"]
data2 = data2[["0", "1", "2"]]
data2.to_csv(f"{new_dir}english-corpus2.tsv.gz", sep='\t', index=False, compression="gzip")

      0                                                  1  \
0  head  seen a complex and exquisitely balanced polity...
1  head  inculcated doctrines incompatible with the pla...
2  word  , during all this period , once entering those...
3  word  immaturity , and want of experience -- besides...
4  part  immaturity , and want of experience -- besides...

                                                   2
0            The topmost, foremost, or leading part.
1  (Figurative) The most important part or one of...
2  The smallest discrete unit of written language...
3                     (Obsolete) A proverb or motto.
4                  A fragment of something; a piece.

  0%|          | 0/37 [00:00<?, ?it/s]

pre tokenize: 100%|██████████| 2/2 [00:00<00:00, 78.72it/s]

Inference Embeddings:   0%|          | 0/2 [00:00<?, ?it/s]
Inference Embeddings:  50%|█████     | 1/2 [00:05<00:05,  5.01s/it]
Inference Embeddings: 100%|██████████| 2/2 [00:05<00:00,  2.94s/it]

pre tokenize: 100%|██████████| 4/4 [00:00<00:00, 87.38it/s]

Inference Embeddings:   0%|          | 0/4 [00:00<?, ?it/s]
Inference Embeddings:  25%|██▌       | 1/4 [00:06<00:20,  6.91s/it]
Inference Embeddings:  50%|█████     | 2/4 [00:07<00:06,  3.49s/it]
Inference Embeddings:  75%|███████▌  | 3/4 [00:08<00:02,  2.30s/it]
Inference Embeddings: 100%|██████████| 4/4 [00:09<00:00,  2.33s/it]

pre tokenize: 100%|██████████| 4/4 [00:00<00:00, 105.25it/s]

Inference Embeddings:   0%|          | 0/4 [00:00<?, ?it/s]
Inference Embeddings:  25%|██▌       | 1/4 [00:07<00:22,  7.59s/it]
Inference Embeddings:  50%|█████     | 2/4 [00:08<00:07,  3.80s/it]
Inference Embeddings: 100%|██████████| 4/4 [00:09<00:00,  2.37s/it]

pre tokenize: 100%|██████████| 2/2 [00:00<00:00, 111.68it/s]

Inference Embeddings:   0%|          | 0/2 [00:00<?, ?it/s]
Inference Embeddings:  50%|█████     | 1/2 [00:04<00:04,  4.60s/it]
Inference Embeddings: 100%|██████████| 2/2 [00:05<00:00,  2.55s/it]

pre tokenize: 100%|██████████| 2/2 [00:00<00:00, 52.17it/s]

Inference Embeddings:   0%|          | 0/2 [00:00<?, ?it/s]
Inference Embeddings:  50%|█████     | 1/2 [00:04<00:04,  4.84s/it]
Inference Embeddings: 100%|██████████| 2/2 [00:05<00:00,  2.72s/it]

pre tokenize: 100%|██████████| 6/6 [00:00<00:00, 100.59it/s]

Inference Embeddings:   0%|          | 0/6 [00:00<?, ?it/s]
Inference Embeddings:  17%|█▋        | 1/6 [00:05<00:27,  5.45s/it]
Inference Embeddings:  33%|███▎      | 2/6 [00:06<00:11,  2.89s/it]
Inference Embeddings:  50%|█████     | 3/6 [00:07<00:06,  2.01s/it]
Inference Embeddings:  67%|██████▋   | 4/6 [00:08<00:03,  1.52s/it]
Inference Embeddings:  83%|████████▎ | 5/6 [00:08<00:01,  1.21s/it]
Inference Embeddings: 100%|██████████| 6/6 [00:09<00:00,  1.56s/it]

pre tokenize: 100%|██████████| 2/2 [00:00<00:00, 62.05it/s]

Inference Embeddings:   0%|          | 0/2 [00:00<?, ?it/s]
Inference Embeddings:  50%|█████     | 1/2 [00:07<00:07,  7.73s/it]
Inference Embeddings: 100%|██████████| 2/2 [00:07<00:00,  3.98s/it]

pre tokenize: 100%|██████████| 9/9 [00:00<00:00, 94.40it/s]

Inference Embeddings:   0%|          | 0/9 [00:00<?, ?it/s]
Inference Embeddings:  11%|█         | 1/9 [00:07<01:03,  7.90s/it]
Inference Embeddings:  22%|██▏       | 2/9 [00:09<00:28,  4.02s/it]
Inference Embeddings:  33%|███▎      | 3/9 [00:10<00:16,  2.68s/it]
Inference Embeddings:  44%|████▍     | 4/9 [00:11<00:10,  2.01s/it]
Inference Embeddings:  56%|█████▌    | 5/9 [00:12<00:06,  1.60s/it]
Inference Embeddings:  67%|██████▋   | 6/9 [00:12<00:03,  1.31s/it]
Inference Embeddings:  78%|███████▊  | 7/9 [00:13<00:02,  1.10s/it]
Inference Embeddings:  89%|████████▉ | 8/9 [00:14<00:00,  1.05it/s]
Inference Embeddings: 100%|██████████| 9/9 [00:14<00:00,  1.63s/it]

pre tokenize: 100%|██████████| 8/8 [00:00<00:00, 91.23it/s]

Inference Embeddings:   0%|          | 0/8 [00:00<?, ?it/s]
Inference Embeddings:  12%|█▎        | 1/8 [00:06<00:43,  6.22s/it]
Inference Embeddings:  25%|██▌       | 2/8 [00:07<00:20,  3.36s/it]
Inference Embeddings:  38%|███▊      | 3/8 [00:08<00:11,  2.35s/it]
Inference Embeddings:  50%|█████     | 4/8 [00:09<00:07,  1.80s/it]
Inference Embeddings:  62%|██████▎   | 5/8 [00:10<00:04,  1.46s/it]
Inference Embeddings:  75%|███████▌  | 6/8 [00:11<00:02,  1.26s/it]
Inference Embeddings:  88%|████████▊ | 7/8 [00:12<00:01,  1.06s/it]
Inference Embeddings: 100%|██████████| 8/8 [00:12<00:00,  1.53s/it]

pre tokenize: 100%|██████████| 8/8 [00:00<00:00, 92.63it/s]

Inference Embeddings:   0%|          | 0/8 [00:00<?, ?it/s]
Inference Embeddings:  12%|█▎        | 1/8 [00:04<00:34,  4.98s/it]
Inference Embeddings:  25%|██▌       | 2/8 [00:06<00:16,  2.69s/it]
Inference Embeddings:  38%|███▊      | 3/8 [00:07<00:09,  1.89s/it]
Inference Embeddings:  50%|█████     | 4/8 [00:07<00:05,  1.50s/it]
Inference Embeddings:  62%|██████▎   | 5/8 [00:08<00:03,  1.22s/it]
Inference Embeddings:  75%|███████▌  | 6/8 [00:09<00:02,  1.06s/it]
Inference Embeddings:  88%|████████▊ | 7/8 [00:09<00:00,  1.12it/s]
Inference Embeddings: 100%|██████████| 8/8 [00:10<00:00,  1.28s/it]

pre tokenize: 100%|██████████| 3/3 [00:00<00:00, 86.08it/s]

Inference Embeddings:   0%|          | 0/3 [00:00<?, ?it/s]
Inference Embeddings:  33%|███▎      | 1/3 [00:07<00:15,  7.72s/it]
Inference Embeddings:  67%|██████▋   | 2/3 [00:08<00:03,  3.74s/it]
Inference Embeddings: 100%|██████████| 3/3 [00:08<00:00,  2.98s/it]

pre tokenize: 100%|██████████| 2/2 [00:00<00:00, 66.15it/s]

Inference Embeddings:   0%|          | 0/2 [00:00<?, ?it/s]
Inference Embeddings:  50%|█████     | 1/2 [00:04<00:04,  4.60s/it]
Inference Embeddings: 100%|██████████| 2/2 [00:04<00:00,  2.44s/it]

pre tokenize: 100%|██████████| 3/3 [00:00<00:00, 40.85it/s]

Inference Embeddings:   0%|          | 0/3 [00:00<?, ?it/s]
Inference Embeddings:  33%|███▎      | 1/3 [00:04<00:09,  4.68s/it]
Inference Embeddings:  67%|██████▋   | 2/3 [00:05<00:02,  2.45s/it]
Inference Embeddings: 100%|██████████| 3/3 [00:06<00:00,  2.00s/it]

pre tokenize: 100%|██████████| 2/2 [00:00<00:00, 82.53it/s]

Inference Embeddings:   0%|          | 0/2 [00:00<?, ?it/s]
Inference Embeddings:  50%|█████     | 1/2 [00:09<00:09,  9.39s/it]
Inference Embeddings: 100%|██████████| 2/2 [00:09<00:00,  4.81s/it]

pre tokenize: 100%|██████████| 5/5 [00:00<00:00, 71.30it/s]

Inference Embeddings:   0%|          | 0/5 [00:00<?, ?it/s]
Inference Embeddings:  20%|██        | 1/5 [00:06<00:25,  6.28s/it]
Inference Embeddings:  40%|████      | 2/5 [00:07<00:10,  3.39s/it]
Inference Embeddings:  60%|██████    | 3/5 [00:08<00:04,  2.34s/it]
Inference Embeddings:  80%|████████  | 4/5 [00:09<00:01,  1.77s/it]
Inference Embeddings: 100%|██████████| 5/5 [00:10<00:00,  2.04s/it]

pre tokenize: 100%|██████████| 8/8 [00:00<00:00, 86.08it/s]

Inference Embeddings:   0%|          | 0/8 [00:00<?, ?it/s]
Inference Embeddings:  12%|█▎        | 1/8 [00:06<00:48,  6.89s/it]
Inference Embeddings:  25%|██▌       | 2/8 [00:08<00:21,  3.64s/it]
Inference Embeddings:  38%|███▊      | 3/8 [00:09<00:12,  2.47s/it]
Inference Embeddings:  50%|█████     | 4/8 [00:10<00:07,  1.87s/it]
Inference Embeddings:  62%|██████▎   | 5/8 [00:11<00:04,  1.51s/it]
Inference Embeddings:  75%|███████▌  | 6/8 [00:11<00:02,  1.25s/it]
Inference Embeddings: 100%|██████████| 8/8 [00:12<00:00,  1.59s/it]

18869
5777